/** Bounded ZIP reader/writer for documented design archives. No network or filesystem extraction. */
const encoder=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true});
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(bytes){let crc=0xffffffff;for(const n of bytes)crc=table[(crc^n)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
function validPath(name){return !!name&&name.length<=300&&!name.startsWith('/')&&!name.includes('\\')&&!name.split('/').some(p=>p==='..'||p==='.')&&!/[\0-\x1f:]/.test(name);}
export async function readZip(input,{maxBytes=80000000,maxEntries=5000}={}){
 const data=input instanceof Uint8Array?input:new Uint8Array(input),view=new DataView(data.buffer,data.byteOffset,data.byteLength);if(data.length>maxBytes||data.length<22)throw Error('Archive exceeds limits or is incomplete');
 let end=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--)if(view.getUint32(i,true)===0x06054b50&&i+22+view.getUint16(i+20,true)===data.length){end=i;break;}if(end<0)throw Error('ZIP directory not found');
 const count=view.getUint16(end+10,true),size=view.getUint32(end+12,true),offset=view.getUint32(end+16,true);if(view.getUint16(end+4,true)||view.getUint16(end+6,true)||count===65535||offset===0xffffffff||count>maxEntries||offset+size>end)throw Error('Multi-volume, ZIP64 or oversized archives are not supported');
 const entries=new Map(),ranges=[],index=[];let p=offset,total=0;
 for(let i=0;i<count;i++){if(p+46>end||view.getUint32(p,true)!==0x02014b50)throw Error('Corrupt ZIP directory');const flags=view.getUint16(p+8,true),method=view.getUint16(p+10,true),crc=view.getUint32(p+16,true),compressed=view.getUint32(p+20,true),length=view.getUint32(p+24,true),nl=view.getUint16(p+28,true),extra=view.getUint16(p+30,true),comment=view.getUint16(p+32,true),local=view.getUint32(p+42,true);if(p+46+nl+extra+comment>offset+size)throw Error('ZIP directory entry exceeds bounds');const name=decoder.decode(data.subarray(p+46,p+46+nl));p+=46+nl+extra+comment;
  if(!validPath(name)||entries.has(name)||index.some(e=>e.name===name))throw Error('Unsafe or duplicate ZIP path');if(flags&1||![0,8].includes(method))throw Error('Encrypted archives and unsupported compression methods are rejected');if(local+30>offset||view.getUint32(local,true)!==0x04034b50)throw Error('Corrupt ZIP member');const start=local+30+view.getUint16(local+26,true)+view.getUint16(local+28,true);if(start+compressed>offset)throw Error('ZIP member exceeds bounds');if(view.getUint16(local+8,true)!==method||view.getUint16(local+6,true)!==flags)throw Error('Inconsistent ZIP headers');const localName=decoder.decode(data.subarray(local+30,local+30+view.getUint16(local+26,true)));if(localName!==name)throw Error('Inconsistent ZIP filenames');
  total+=length;if(length>30000000||total>maxBytes||compressed&&length/compressed>250)throw Error('Archive expansion exceeds its resource budget');ranges.push([local,start+compressed]);index.push({name,method,crc,compressed,length,start});
 }
 ranges.sort((a,b)=>a[0]-b[0]);for(let i=1;i<ranges.length;i++)if(ranges[i][0]<ranges[i-1][1])throw Error('ZIP entries overlap');
 for(const e of index){let bytes=data.slice(e.start,e.start+e.compressed);if(e.method===8){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')),reader=stream.getReader(),chunks=[];let length=0;try{for(;;){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>e.length||length>maxBytes)throw Error('Archive decompressed size is invalid');chunks.push(value);}}catch(error){await reader.cancel().catch(()=>{});throw error;}bytes=new Uint8Array(length);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.length;}}
  if(bytes.length!==e.length||crc32(bytes)!==e.crc)throw Error('Archive member integrity check failed: '+e.name);entries.set(e.name,bytes);
 }return entries;
}
export function writeZip(files){const entries=files instanceof Map?[...files]:Object.entries(files);if(entries.length>5000)throw Error('Too many archive entries');const chunks=[],directory=[];let offset=0,total=0;
 for(const [name,value]of entries){if(!validPath(name))throw Error('Unsafe archive path');const path=encoder.encode(name),bytes=typeof value==='string'?encoder.encode(value):value;if(!(bytes instanceof Uint8Array))throw Error('Archive content must be text or bytes');total+=bytes.length;if(total>80000000)throw Error('Archive exceeds 80 MB');const crc=crc32(bytes),header=new Uint8Array(30+path.length),h=new DataView(header.buffer);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint16(6,0x800,true);h.setUint16(12,33,true);h.setUint32(14,crc,true);h.setUint32(18,bytes.length,true);h.setUint32(22,bytes.length,true);h.setUint16(26,path.length,true);header.set(path,30);chunks.push(header,bytes);
  const central=new Uint8Array(46+path.length),c=new DataView(central.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint16(14,33,true);c.setUint32(16,crc,true);c.setUint32(20,bytes.length,true);c.setUint32(24,bytes.length,true);c.setUint16(28,path.length,true);c.setUint32(42,offset,true);central.set(path,46);directory.push(central);offset+=header.length+bytes.length;
 }const directorySize=directory.reduce((n,a)=>n+a.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,directorySize,true);v.setUint32(16,offset,true);const result=new Uint8Array(offset+directorySize+22);let pos=0;for(const a of [...chunks,...directory,end]){result.set(a,pos);pos+=a.length;}return result;
}
export function archiveJSON(entries,name){const bytes=entries.get(name);if(!bytes)throw Error('Archive is missing '+name);if(bytes.length>30000000)throw Error('JSON member exceeds 30 MB');return JSON.parse(decoder.decode(bytes));}
