import {decodeSVG} from './svg-import.js';
import {node,uid,validateValues,validateSnapshot} from '../core/schema.js';
export async function readImage(file,{maxSize=1800}={}){if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('Choose a PNG, JPEG, WebP, or GIF image');if(file.size>30_000_000)throw Error('Use an image smaller than 30 MB');const bitmap=await createImageBitmap(file),s=Math.min(1,maxSize/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*s));canvas.height=Math.max(1,Math.round(bitmap.height*s));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return{src:canvas.toDataURL(file.type==='image/png'?'image/png':'image/jpeg',.9),w:canvas.width,h:canvas.height};}
export function applyGenerated(store,design,offsetX=0){if(!Array.isArray(design.nodes)||design.nodes.length>30000)throw Error('Invalid design response');const ids=new Map(design.nodes.map(n=>[n.id,uid()]));if(ids.size!==design.nodes.length)throw Error('Generated IDs must be unique');const roots=[];store.transact('Import generated design',()=>{for(const raw of design.nodes){const{id,...v}=raw;validateValues(v);if(v.parent&&!ids.has(v.parent))throw Error('Generated parent not found');v.parent=ids.get(v.parent)||'';if(v.target)v.target=ids.get(v.target)||'';if(v.componentId)v.componentId=ids.get(v.componentId)||'';if(!v.parent){if(v.transform){v.transform=[...v.transform];v.transform[4]+=offsetX;}else v.x=(v.x||0)+offsetX;roots.push(ids.get(id));}store.add(node(v.type||'rect',v),ids.get(id));}});return roots;}
/** Import sanitized editable SVG data. Parsing never attaches foreign DOM to the page. */
export function importSVG(store,source,{x=0,y=0}={}){const design=decodeSVG(source);if(y)for(const n of design.nodes)if(!n.parent){if(n.transform)n.transform[5]+=y;else n.y=(n.y||0)+y;}const roots=applyGenerated(store,design,x);return{root:roots[0],roots,warnings:design.warnings};}
/** K-means-like palette quantization, in a worker; no external uploads. */
const SCAN_WORKER=`onmessage=e=>{const{pixels,w,h}=e.data,bins=new Map();for(let i=0;i<pixels.length;i+=16){if(pixels[i+3]<128)continue;const r=Math.round(pixels[i]/32)*32,g=Math.round(pixels[i+1]/32)*32,b=Math.round(pixels[i+2]/32)*32,k=[r,g,b].join(',');bins.set(k,(bins.get(k)||0)+1);}const colors=[...bins].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,count])=>({color:'#'+k.split(',').map(v=>Math.min(255,+v).toString(16).padStart(2,'0')).join(''),count}));postMessage({colors});};`;
export async function extractPalette(src){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=src;});const canvas=document.createElement('canvas');canvas.width=160;canvas.height=160;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,160,160);const data=ctx.getImageData(0,0,160,160),url=URL.createObjectURL(new Blob([SCAN_WORKER],{type:'text/javascript'})),worker=new Worker(url);return new Promise((resolve,reject)=>{worker.onmessage=e=>{worker.terminate();URL.revokeObjectURL(url);resolve(e.data.colors);};worker.onerror=e=>{worker.terminate();URL.revokeObjectURL(url);reject(Error('Palette extraction failed'));};worker.postMessage({pixels:data.data,w:160,h:160},[data.data.buffer]);});}
