import {node,uid,validateValues,validateSnapshot} from '../core/schema.js';
import {createRichText,richAtoms,validateMarks} from '../core/richtext.js';
import {Vector} from '../core/vector.js';
import {mul,point,inverse,localMatrix} from '../core/geometry.js';
import {readZip,archiveJSON,writeZip} from './archive.js';
const ID=[1,0,0,1,0,0],clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
export function rgba(color,opacity=1){if(!color)return'transparent';const vals=[color.r??color.red,color.g??color.green,color.b??color.blue,color.a??color.alpha??1].map((v,i)=>Math.round(clamp(v??(i===3?1:0),0,1)*(i===3?clamp(opacity,0,1):1)*255));return'#'+vals.map(v=>v.toString(16).padStart(2,'0')).join('');}
export function importedRichText(text,ranges){const state=createRichText(text),atoms=richAtoms(state);for(const r of ranges){validateMarks(r.marks);const start=[...text.slice(0,r.start)].length,end=[...text.slice(0,r.start+r.length)].length;for(let i=start;i<Math.min(end,atoms.length);i++)for(const[k,v]of Object.entries(r.marks)){atoms[i].marks[k]=v;atoms[i].ms[k]=[1,'importer'];}}return state;}
function sourceId(raw,map){const key=String(raw||uid('source'));if(map.has(key))return map.get(key);const id=uid('import');map.set(key,id);return id;}
function safeNodes(nodes){if(nodes.length>30000)throw Error('Import exceeds 30,000 layers');const ids=new Set();for(const n of nodes){if(ids.has(n.id))throw Error('Duplicate imported layer');ids.add(n.id);const{id,...v}=n;validateValues(v);}return nodes;}
/** Public REST JSON, not the undocumented binary .fig format. geometry=paths preserves curves. */
export function decodeFigma(json){const root=json.document||json;if(!root||!['DOCUMENT','CANVAS','FRAME','COMPONENT','GROUP','SECTION'].includes(root.type))throw Error('Not a documented design REST JSON document');const nodes=[],warnings=new Set(),ids=new Map();let count=0;
 const walk=(raw,parent='',parentWorld=ID,depth=0)=>{if(++count>30000||depth>128)throw Error('Design hierarchy exceeds import limits');if(['DOCUMENT','CANVAS'].includes(raw.type)){for(const child of raw.children||[])walk(child,parent,parentWorld,depth+1);return;}
  const map={FRAME:'frame',SECTION:'frame',COMPONENT:'frame',COMPONENT_SET:'group',INSTANCE:'frame',GROUP:'group',TRANSFORM_GROUP:'group',RECTANGLE:'rect',ELLIPSE:'ellipse',TEXT:'text',LINE:'line',VECTOR:'path',BOOLEAN_OPERATION:'path',STAR:'path',REGULAR_POLYGON:'path'};let type=map[raw.type];if(!type){warnings.add('Unsupported node: '+raw.type);for(const c of raw.children||[])walk(c,parent,parentWorld,depth+1);return;}
  const box=raw.absoluteBoundingBox||{x:0,y:0,width:100,height:100},w=clamp(raw.size?.x??box.width,.1,20000),h=clamp(raw.size?.y??box.height,.1,20000),rt=raw.relativeTransform;let matrix;
  if(Array.isArray(rt)&&rt.length===2&&rt.every(r=>Array.isArray(r)&&r.length===3))matrix=[rt[0][0],rt[1][0],rt[0][1],rt[1][1],rt[0][2],rt[1][2]];else{const q=point(inverse(parentWorld),box.x||0,box.y||0);matrix=[1,0,0,1,q.x,q.y];if(raw.rotation)warnings.add('Rotated layer lacks relativeTransform; export geometry=paths');}
  const id=sourceId(raw.id,ids),fill=(raw.fills||[]).filter(p=>p.visible!==false),stroke=(raw.strokes||[]).find(p=>p.visible!==false),style=raw.style||{};const v={id,...node(type,{parent,name:String(raw.name||raw.type).slice(0,100),x:0,y:0,w,h,transform:matrix,fill:fill[0]?.type==='SOLID'?rgba(fill[0].color,fill[0].opacity??1):'transparent',stroke:stroke?.type==='SOLID'?rgba(stroke.color,stroke.opacity??1):'transparent',strokeWidth:clamp(raw.strokeWeight,0,1000),strokeDash:(raw.strokeDashes||[]).join(' '),radius:clamp(raw.cornerRadius,0,10000),opacity:clamp(raw.opacity??1,0,1),hidden:raw.visible===false,locked:!!raw.locked,clip:!!raw.clipsContent,order:count,sourceId:String(raw.id||''),fontFamily:String(style.fontFamily||'Inter').slice(0,100),fontSize:clamp(style.fontSize||16,4,512),fontWeight:clamp(style.fontWeight||400,100,1000),italic:!!style.italic,underline:style.textDecoration==='UNDERLINE',align:{CENTER:'center',RIGHT:'right'}[style.textAlignHorizontal]||'left',verticalAlign:{CENTER:'middle',BOTTOM:'bottom'}[style.textAlignVertical]||'top',lineHeight:style.lineHeightPx?clamp(style.lineHeightPx/(style.fontSize||16),.1,10):1.35,letterSpacing:clamp(style.letterSpacing,-100,100),layout:{HORIZONTAL:'row',VERTICAL:'column'}[raw.layoutMode]||'none',layoutWrap:raw.layoutWrap==='WRAP',layoutJustify:{CENTER:'center',MAX:'end',SPACE_BETWEEN:'space-between'}[raw.primaryAxisAlignItems]||'start',layoutAlign:{CENTER:'center',MAX:'end',STRETCH:'stretch'}[raw.counterAxisAlignItems]||'start',padding:clamp(raw.paddingLeft??raw.horizontalPadding,0,1000),gap:clamp(raw.itemSpacing,-1000,1000),component:raw.type==='COMPONENT',componentId:raw.componentId?sourceId(raw.componentId,ids):'',sizeX:(raw.layoutSizingHorizontal||'FIXED').toLowerCase(),sizeY:(raw.layoutSizingVertical||'FIXED').toLowerCase()})};
  if(fill.length>1)warnings.add('Multiple paints: first visible paint retained');if(raw.effects?.length)warnings.add('Effects approximated; only drop shadow presence is retained');v.shadow=!!raw.effects?.some(e=>e.type==='DROP_SHADOW'&&e.visible!==false);
  if(fill[0]?.type==='GRADIENT_LINEAR'){v.gradient='vertical';v.gradientStops=(fill[0].gradientStops||[]).slice(0,32).map(s=>({offset:clamp(s.position,0,1),color:rgba(s.color)}));if(v.gradientStops.length>=2){v.fill=v.gradientStops[0].color;v.fill2=v.gradientStops.at(-1).color;}else delete v.gradientStops;warnings.add('Gradient orientation reduced to vertical');}
  if(fill.some(f=>f.type==='IMAGE'))warnings.add('Remote image references require embedded image assets or SVG export');if(raw.isMask)warnings.add('Sibling alpha/luminance masks require SVG export');
  if(type==='text'){v.text=String(raw.characters||'').slice(0,20000);v.color=v.fill==='transparent'?'#252236':v.fill;v.fill='transparent';const overrides=raw.characterStyleOverrides||[],table=raw.styleOverrideTable||{},ranges=[];let start=0;for(let i=1;i<=v.text.length;i++)if(i===v.text.length||overrides[i]!==overrides[start]){const st=table[String(overrides[start])];if(st){const marks={};if(st.fontWeight!==undefined)marks.bold=st.fontWeight>=600;if(st.italic!==undefined)marks.italic=st.italic;if(st.fontSize)marks.fontSize=clamp(st.fontSize,4,512);if(st.fontFamily)marks.fontFamily=String(st.fontFamily).slice(0,100);if(st.textDecoration)marks.underline=st.textDecoration==='UNDERLINE';if(st.fills?.[0]?.color)marks.color=rgba(st.fills[0].color);if(st.hyperlink?.url&&/^(https?:\/\/|mailto:)/i.test(st.hyperlink.url))marks.link=st.hyperlink.url;ranges.push({start,length:i-start,marks});}start=i;}if(ranges.length)v.richText=importedRichText(v.text,ranges);}
  if(type==='path'){const paths=raw.fillGeometry||raw.strokeGeometry||[];if(paths.length){v.path=paths.map(p=>Vector.serialize(Vector.parse(p.path))).join(' ');v.pathW=w;v.pathH=h;v.fillRule=paths[0].windingRule==='EVENODD'?'evenodd':'nonzero';}else{warnings.add('Vector path data absent; request geometry=paths');v.type=raw.children?.length?'group':'rect';v.fill='transparent';v.stroke='#c97588';v.strokeWidth=1;}}
  if(raw.transitionNodeID){v.action='navigate';v.target=sourceId(raw.transitionNodeID,ids);v.trigger='click';v.duration=raw.transitionDuration||250;}nodes.push(v);if(type!=='path'||!raw.fillGeometry?.length)for(const child of raw.children||[])walk(child,id,mul(parentWorld,matrix),depth+1);
 };walk(root);const present=new Set(nodes.map(n=>n.id));for(const n of nodes){if(n.target&&!present.has(n.target))n.target='';if(n.componentId&&!present.has(n.componentId)){n.componentId='';warnings.add('External component master not included');}}
 return{nodes:safeNodes(nodes),warnings:[...warnings],name:json.name||'Imported design'};
}
function pair(value){const p=String(value||'{0,0}').match(/[-+]?(?:\d*\.\d+|\d+)(?:e[-+]?\d+)?/gi)||[];return{x:Number(p[0])||0,y:Number(p[1])||0};}
function sketchStyle(raw){const style=raw.style||{},fills=(style.fills||[]).filter(f=>f.isEnabled!==false),border=(style.borders||[]).find(f=>f.isEnabled!==false),font=style.textStyle?.encodedAttributes||{},desc=font.MSAttributedStringFontAttribute?.attributes||{};return{fill:fills[0]?.fillType===0?rgba(fills[0].color):'transparent',stroke:border?rgba(border.color):'transparent',strokeWidth:border?.thickness||0,color:font.MSAttributedStringColorAttribute?rgba(font.MSAttributedStringColorAttribute):'#252236',fontFamily:desc.name||'Inter',fontSize:desc.size||16,fontWeight:/bold|semibold/i.test(desc.name||'')?700:400,italic:/italic/i.test(desc.name||''),align:['left','right','center','left'][font.paragraphStyle?.alignment||0]||'left',opacity:style.contextSettings?.opacity??1,radius:raw.fixedRadius||raw.points?.[0]?.cornerRadius||0,shadow:!!style.shadows?.some(s=>s.isEnabled!==false)};}
export async function decodeSketch(input){const entries=input instanceof Map?input:await readZip(input),document=archiveJSON(entries,'document.json'),nodes=[],warnings=new Set(),ids=new Map();const pages=(document.pages||[]).map(p=>p._ref?archiveJSON(entries,p._ref.endsWith('.json')?p._ref:p._ref+'.json'):p),symbols=new Map();let count=0;
 let collected=0;const collect=(layers,depth=0)=>{if(depth>128)throw Error('Sketch hierarchy exceeds limits');for(const l of layers||[]){if(++collected>30000)throw Error('Sketch hierarchy exceeds limits');if(l._class==='symbolMaster')symbols.set(l.symbolID,l);collect(l.layers,depth+1);}};for(const p of pages)collect(p.layers);
 const walk=(raw,parent='',depth=0,remap=false)=>{if(++count>30000||depth>128)throw Error('Sketch hierarchy exceeds limits');const map={artboard:'frame',symbolMaster:'group',symbolInstance:'group',group:'group',shapeGroup:'group',rectangle:'rect',oval:'ellipse',text:'text',bitmap:'image',shapePath:'path'};let type=map[raw._class];if(!type){warnings.add('Unsupported layer: '+raw._class);return;}const frame=raw.frame||{},w=clamp(frame.width||100,.1,20000),h=clamp(frame.height||100,.1,20000),id=remap?uid():sourceId(raw.do_objectID,ids),v={id,...node(type,{...sketchStyle(raw),parent,name:String(raw.name||raw._class).slice(0,100),sourceId:String(raw.do_objectID||''),x:frame.x||0,y:frame.y||0,w,h,rotation:-(raw.rotation||0),order:count,hidden:raw.isVisible===false,locked:!!raw.isLocked,clip:raw._class==='artboard'&&raw.hasClippingMask!==false,component:raw._class==='symbolMaster'})};
  if(raw.isFlippedHorizontal||raw.isFlippedVertical)v.transform=[raw.isFlippedHorizontal?-1:1,0,0,raw.isFlippedVertical?-1:1,raw.isFlippedHorizontal?(frame.x||0)*2+w:0,raw.isFlippedVertical?(frame.y||0)*2+h:0];
  if(raw._class==='artboard'&&raw.hasBackgroundColor)v.fill=rgba(raw.backgroundColor);
  if(type==='path'){const points=(raw.points||[]).map(p=>{const a=pair(p.point),i=pair(p.curveTo),o=pair(p.curveFrom);return{x:a.x*w,y:a.y*h,inX:(p.hasCurveTo?i.x:a.x)*w,inY:(p.hasCurveTo?i.y:a.y)*h,outX:(p.hasCurveFrom?o.x:a.x)*w,outY:(p.hasCurveFrom?o.y:a.y)*h,mode:p.curveMode===2?'symmetric':p.curveMode===3?'smooth':'corner'};});v.path=Vector.serialize([{closed:!!raw.isClosed,points}]);v.pathW=w;v.pathH=h;v.fillRule=raw.style?.windingRule===0?'nonzero':'evenodd';}
  if(type==='text'){const attr=raw.attributedString||{};v.text=String(attr.string||'').slice(0,20000);v.fill='transparent';const ranges=(attr.attributes||[]).map(r=>{const a=r.attributes||{},font=a.MSAttributedStringFontAttribute?.attributes,marks={};if(font){marks.fontFamily=String(font.name||'Inter').slice(0,100);marks.fontSize=clamp(font.size||16,4,512);marks.bold=/bold|semibold/i.test(font.name||'');marks.italic=/italic/i.test(font.name||'');}if(a.MSAttributedStringColorAttribute)marks.color=rgba(a.MSAttributedStringColorAttribute);if(a.underlineStyle!==undefined)marks.underline=!!a.underlineStyle;return{start:r.location||0,length:r.length||0,marks};});if(ranges.length)v.richText=importedRichText(v.text,ranges);}
  if(type==='image'){const reference=raw.image?._ref,bytes=entries.get(reference);if(bytes){const png=bytes[0]===137&&bytes[1]===80,jpeg=bytes[0]===255&&bytes[1]===216,webp=bytes[0]===82&&bytes[8]===87;if(!png&&!jpeg&&!webp){warnings.add('Unsupported embedded bitmap encoding');v.type='rect';}else if(bytes.length>5500000){warnings.add('Image exceeds embedded resource quota');v.type='rect';}else{let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));v.src='data:image/'+(png?'png':jpeg?'jpeg':'webp')+';base64,'+btoa(binary);}}else{warnings.add('Missing embedded bitmap');v.type='rect';}}
  if(raw.style?.fills?.some(f=>f.isEnabled&&f.fillType!==0))warnings.add('Pattern and gradient fills reduced to the supported solid paint subset');if(raw.hasClippingMask)warnings.add('Sibling clipping masks require SVG export');
  if(raw.flow?.destinationArtboardID){v.action='navigate';v.target=sourceId(raw.flow.destinationArtboardID,ids);v.trigger='click';}nodes.push(v);
  if(raw._class==='symbolInstance'){const master=symbols.get(raw.symbolID);if(master){v.componentId=sourceId(master.do_objectID,ids);const root=uid('symbol');nodes.push({id:root,...node('group',{parent:id,w:master.frame.width,h:master.frame.height,fill:'transparent',transform:[w/master.frame.width,0,0,h/master.frame.height,0,0]})});for(const child of master.layers||[])walk(child,root,depth+1,true);if(raw.overrideValues?.length)warnings.add('Symbol overrides are retained only where represented in explicit child layers');}else warnings.add('External symbol library is not embedded');}
  else for(const child of raw.layers||[])walk(child,id,depth+1,remap);
 };let x=0;for(const page of pages){const before=nodes.length;for(const layer of page.layers||[])walk(layer);const roots=nodes.slice(before).filter(n=>!n.parent);if(x)for(const n of roots)n.x+=x;x=Math.max(x,...roots.map(n=>n.x+n.w))+100;}const present=new Set(nodes.map(n=>n.id));for(const n of nodes){if(n.target&&!present.has(n.target))n.target='';if(n.componentId&&!present.has(n.componentId))n.componentId='';}return{nodes:safeNodes(nodes),warnings:[...warnings],name:document.name||'Imported archive'};
}
export function portableArchive(store){return writeZip({'manifest.json':JSON.stringify({format:'mireva-package',version:1,document:'document.mireva'}),'document.mireva':JSON.stringify(store.snapshot())});}
export async function decodePackage(input){const entries=await readZip(input),manifest=archiveJSON(entries,'manifest.json');if(manifest.format!=='mireva-package'||manifest.version!==1||manifest.document!=='document.mireva')throw Error('Not a supported portable package');return validateSnapshot(archiveJSON(entries,'document.mireva'));}
