import {node,uid,validateValues} from '../core/schema.js';
import {Vector} from '../core/vector.js';
import {mul} from '../core/geometry.js';
import {importedRichText} from './interchange.js';
const ID=[1,0,0,1,0,0],clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
export function svgTransform(value){let m=ID;const leftover=String(value||'').replace(/([a-z]+)\s*\(([^)]*)\)/gi,(_,name,args)=>{const a=args.trim().split(/[\s,]+/).filter(Boolean).map(Number);if(a.some(n=>!Number.isFinite(n)))throw Error('Invalid SVG transform');let n;switch(name){case'matrix':if(a.length!==6)throw Error('Invalid matrix');n=a;break;case'translate':n=[1,0,0,1,a[0]||0,a[1]||0];break;case'scale':n=[a[0]??1,0,0,a[1]??a[0]??1,0,0];break;case'rotate':{const r=(a[0]||0)*Math.PI/180,c=Math.cos(r),s=Math.sin(r),x=a[1]||0,y=a[2]||0;n=[c,s,-s,c,x-c*x+s*y,y-s*x-c*y];break;}case'skewX':n=[1,0,Math.tan((a[0]||0)*Math.PI/180),1,0,0];break;case'skewY':n=[1,Math.tan((a[0]||0)*Math.PI/180),0,1,0,0];break;default:throw Error('Unknown SVG transform '+name);}m=mul(m,n);return'';});if(leftover.replace(/[\s,]/g,''))throw Error('Invalid transform syntax');return m;}
function styles(doc){const rules=[];for(const style of doc.querySelectorAll('style')){const text=style.textContent.replace(/\/\*[\s\S]*?\*\//g,'');for(const m of text.matchAll(/([^{}]+)\{([^{}]*)\}/g)){if(m[1].includes('@'))continue;rules.push({selector:m[1].trim(),values:declarations(m[2])});}}return rules.slice(0,500);}
function declarations(text){const result={};for(const part of String(text||'').split(';')){const at=part.indexOf(':');if(at>0)result[part.slice(0,at).trim()]=part.slice(at+1).trim().replace(/\s*!important$/,'');}return result;}
export function decodeSVG(source){if(source.length>40000000)throw Error('SVG exceeds 40 MB');if(/<!DOCTYPE|<!ENTITY/i.test(source))throw Error('External declarations are not accepted');const doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror'))throw Error('Invalid SVG');const svg=doc.documentElement;if(svg.localName!=='svg')throw Error('Not an SVG document');const warnings=new Set(),nodes=[],rules=styles(doc),elements=new Map([...doc.querySelectorAll('[id]')].map(e=>[e.id,e])),ctx=document.createElement('canvas').getContext('2d');let order=0;
 const vb=(svg.getAttribute('viewBox')||'').trim().split(/[\s,]+/).filter(Boolean).map(Number),w=clamp(parseFloat(svg.getAttribute('width'))||vb[2]||400,.1,20000),h=clamp(parseFloat(svg.getAttribute('height'))||vb[3]||300,.1,20000),meta=svg.querySelector('metadata#mireva-editable');
 if(meta){try{const portable=JSON.parse(meta.textContent);if(portable.format==='mireva-svg'&&portable.version===1&&Array.isArray(portable.nodes)&&portable.nodes.length<=30000){const ids=new Set();for(const n of portable.nodes){if(!n||typeof n.id!=='string'||ids.has(n.id))throw Error('Duplicate metadata layer');ids.add(n.id);const{id,...v}=n;validateValues(v);}return{nodes:portable.nodes,warnings:[],name:portable.name||'Editable SVG',editable:true};}}catch(e){throw Error('Invalid embedded editable data: '+e.message);}}
 if(vb.length&& (vb.length!==4||vb.some(n=>!Number.isFinite(n))||vb[2]<=0||vb[3]<=0))throw Error('Invalid SVG viewBox');const root=uid('svg');let view=vb.length===4?[w/vb[2],0,0,h/vb[3],-vb[0]*w/vb[2],-vb[1]*h/vb[3]]:ID;if(vb.length===4&&svg.getAttribute('preserveAspectRatio')!=='none'){const pa=svg.getAttribute('preserveAspectRatio')||'xMidYMid meet',scale=pa.includes('slice')?Math.max(w/vb[2],h/vb[3]):Math.min(w/vb[2],h/vb[3]),ax=pa.includes('xMin')?0:pa.includes('xMax')?1:.5,ay=pa.includes('YMin')?0:pa.includes('YMax')?1:.5;view=[scale,0,0,scale,-vb[0]*scale+(w-vb[2]*scale)*ax,-vb[1]*scale+(h-vb[3]*scale)*ay];}nodes.push({id:root,...node('frame',{name:svg.querySelector('title')?.textContent?.slice(0,100)||'Imported SVG',w,h,fill:'transparent'})});
 const computed=(el,parent={})=>{const out={};for(const k of ['fill','fill-opacity','fill-rule','stroke','stroke-width','stroke-opacity','stroke-linecap','stroke-linejoin','stroke-dasharray','color','font-size','font-family','font-weight','font-style','text-anchor','text-decoration','letter-spacing','visibility'])if(parent[k]!==undefined)out[k]=parent[k];for(const a of el.attributes)out[a.name]=a.value;for(const rule of rules)try{if(el.matches(rule.selector))Object.assign(out,rule.values);}catch{warnings.add('Unsupported CSS selector');}Object.assign(out,declarations(el.getAttribute('style')));return out;};
 const color=(value,fallback='#000000')=>{if(value==='none')return'transparent';if(!value)return fallback;if(/url\s*\(/i.test(value))return fallback;ctx.fillStyle='#010203';ctx.fillStyle=value;let out=ctx.fillStyle;if(out.startsWith('#'))return out;const m=out.match(/^rgba?\(([^)]+)\)/);if(m){const a=m[1].split(/[, /]+/).map(Number);return'#'+a.slice(0,3).map(v=>Math.round(v).toString(16).padStart(2,'0')).join('')+(a[3]!==undefined?Math.round(a[3]*255).toString(16).padStart(2,'0'):'');}return fallback;};
 const paint=(v,s)=>{v.fill=color(s.fill||'#000000');v.stroke=color(s.stroke||'none','transparent');v.strokeWidth=clamp(s['stroke-width']===undefined?(s.stroke&&s.stroke!=='none'?1:0):parseFloat(s['stroke-width'])||0,0,2000);v.strokeCap=['butt','round','square'].includes(s['stroke-linecap'])?s['stroke-linecap']:'butt';v.strokeJoin=['miter','round','bevel'].includes(s['stroke-linejoin'])?s['stroke-linejoin']:'miter';v.strokeDash=(s['stroke-dasharray']||'').replace(/,/g,' ');if(v.strokeDash==='none')v.strokeDash='';v.fillRule=s['fill-rule']==='evenodd'?'evenodd':'nonzero';v.opacity=clamp(parseFloat(s.opacity??1),0,1);const match=s.fill?.match(/^url\(["']?#([^\s)'"#]+)["']?\)$/),g=match&&elements.get(match[1]);if(g?.localName==='linearGradient'){v.gradient=Math.abs(parseFloat(g.getAttribute('x2')||1)-parseFloat(g.getAttribute('x1')||0))>Math.abs(parseFloat(g.getAttribute('y2')||0)-parseFloat(g.getAttribute('y1')||0))?'horizontal':'vertical';const stops=[...g.querySelectorAll('stop')].slice(0,32).map(el=>{const st=computed(el),o=el.getAttribute('offset')||'0';return{offset:clamp(parseFloat(o)/(o.includes('%')?100:1),0,1),color:color(st['stop-color'])};});if(stops.length>=2){v.gradientStops=stops;v.fill=stops[0].color;v.fill2=stops.at(-1).color;}if(g.hasAttribute('gradientTransform'))warnings.add('Gradient transforms reduced to principal-axis gradient');}else if(match)warnings.add('Unsupported paint server');if(s['fill-opacity']&&s['fill-opacity']!=='1'){const c=v.fill;if(/^#[a-f0-9]{6}$/i.test(c))v.fill=c+Math.round(clamp(s['fill-opacity'],0,1)*255).toString(16).padStart(2,'0');}if(s.filter)warnings.add('Filter effects are not interpreted');};
 const pathFor=(el,s)=>{const a=k=>parseFloat(s[k])||0,t=el.localName;if(t==='path')return s.d||'';if(t==='rect')return Vector.shapePath({type:'rect',w:Math.max(.1,a('width')),h:Math.max(.1,a('height')),radius:a('rx')});if(t==='circle'||t==='ellipse')return Vector.shapePath({type:'ellipse',w:2*(t==='circle'?a('r'):a('rx')),h:2*(t==='circle'?a('r'):a('ry'))});if(t==='line')return`M ${a('x1')} ${a('y1')} L ${a('x2')} ${a('y2')}`;if(t==='polygon'||t==='polyline'){const p=(s.points||'').match(/[-+]?(?:\d*\.\d+|\d+)(?:e[-+]?\d+)?/gi)||[];if(p.length%2)throw Error('Invalid polygon coordinates');return p.reduce((r,v,i)=>r+(i%2?' ':i?' L ':'M ')+v,'')+(t==='polygon'?' Z':'');}return'';};
 const walk=(el,parent,inherit={},extra=ID,depth=0,uses=new Set())=>{if(++order>30000||depth>128)throw Error('SVG complexity limit reached');const tag=el.localName,s=computed(el,inherit);if(['defs','style','metadata','title','desc','clipPath','linearGradient','radialGradient'].includes(tag))return;if(['script','foreignObject','animate','animateTransform','set','filter','mask'].includes(tag)){warnings.add(tag+' omitted');return;}const a=k=>parseFloat(s[k])||0;
  if(tag==='use'){const href=el.getAttribute('href')||el.getAttributeNS('http://www.w3.org/1999/xlink','href');if(!href?.startsWith('#')||uses.has(href)){warnings.add('External or recursive use reference omitted');return;}const target=elements.get(href.slice(1));if(target)walk(target,parent,s,mul(extra,mul(svgTransform(s.transform),[1,0,0,1,a('x'),a('y')])),depth+1,new Set([...uses,href]));return;}
  const matrix=mul(extra,svgTransform(s.transform)),v={parent,name:el.id||s['data-name']||'SVG '+tag,order,hidden:s.display==='none'||s.visibility==='hidden',transform:matrix};paint(v,s);let type=tag;
  if(['svg','g','a','symbol'].includes(tag)){if(tag==='svg')warnings.add('Nested SVG viewports imported as transformed groups');const id=uid('svg');nodes.push({id,...node('group',{...v,w,h,fill:'transparent'})});const clipRef=s['clip-path']?.match(/^url\(#([^)]*)\)$/)?.[1],clip=clipRef&&elements.get(clipRef);if(clip){if(clip.getAttribute('clipPathUnits')==='objectBoundingBox')warnings.add('Object bounding box clips require SVG flattening');else{let parts=[];for(const child of clip.children){const st=computed(child),path=pathFor(child,st);if(path)parts.push(...Vector.transform(Vector.parse(path),mul(svgTransform(st.transform),['rect','circle','ellipse'].includes(child.localName)?[1,0,0,1,child.localName==='rect'?parseFloat(st.x)||0:(parseFloat(st.cx)||0)-(parseFloat(st.rx)||parseFloat(st.r)||0),child.localName==='rect'?parseFloat(st.y)||0:(parseFloat(st.cy)||0)-(parseFloat(st.ry)||parseFloat(st.r)||0)]:ID)));}if(parts.length)nodes.at(-1).maskPath=Vector.serialize(parts);}}
   for(const child of el.children)walk(child,id,s,ID,depth+1,uses);return;}
  if(tag==='rect')Object.assign(v,{x:a('x'),y:a('y'),w:Math.max(.1,a('width')),h:Math.max(.1,a('height')),radius:a('rx')});
  else if(tag==='circle'||tag==='ellipse'){type='ellipse';const rx=tag==='circle'?a('r'):a('rx'),ry=tag==='circle'?a('r'):a('ry');Object.assign(v,{x:a('cx')-rx,y:a('cy')-ry,w:Math.max(.1,rx*2),h:Math.max(.1,ry*2)});}
  else if(['path','line','polygon','polyline'].includes(tag)){type='path';const parts=Vector.parse(pathFor(el,s));if(!parts.length)return;Object.assign(v,Vector.normalizeNode({x:0,y:0,w:1,h:1,rotation:0},parts));if(['line','polyline'].includes(tag))v.fill='transparent';}
  else if(tag==='image'){const href=el.getAttribute('href')||el.getAttributeNS('http://www.w3.org/1999/xlink','href');if(!/^data:image\/(png|jpeg|webp|gif);base64,[a-zA-Z0-9+/=]+$/.test(href||'')){warnings.add('External images omitted');return;}Object.assign(v,{x:a('x'),y:a('y'),w:Math.max(.1,a('width')),h:Math.max(.1,a('height')),src:href});}
  else if(tag==='text'){const fs=clamp(a('font-size')||16,4,512),text=el.textContent.slice(0,20000),runs=[];let cursor=0,spanCount=0;const scan=(e,style,spanDepth=0)=>{if(spanDepth>128||++spanCount>30000)throw Error('SVG text complexity limit reached');for(const child of e.childNodes){if(cursor>=text.length)break;if(child.nodeType===3){const value=child.textContent.slice(0,text.length-cursor),marks={color:color(style.fill),fontSize:clamp(parseFloat(style['font-size'])||fs,4,512),bold:style['font-weight']==='bold'||+style['font-weight']>=600,italic:style['font-style']==='italic',underline:(style['text-decoration']||'').includes('underline')};if(style['font-family'])marks.fontFamily=style['font-family'].replace(/["']/g,'').slice(0,100);runs.push({start:cursor,length:value.length,marks});cursor+=value.length;}else if(child.nodeType===1)scan(child,computed(child,style),spanDepth+1);}};scan(el,s);ctx.font=fs+'px '+(s['font-family']||'sans-serif');let width=Math.min(20000,Math.max(1,ctx.measureText(text).width+2)),x=a('x');if(s['text-anchor']==='middle')x-=width/2;else if(s['text-anchor']==='end')x-=width;Object.assign(v,{x,y:a('y')-(s['dominant-baseline']==='text-before-edge'?0:fs*.8),w:width,h:fs*1.5,fontSize:fs,fontWeight:s['font-weight']==='bold'?700:a('font-weight')||400,fontFamily:(s['font-family']||'Inter').replace(/["']/g,'').slice(0,100),color:v.fill,fill:'transparent',text,richText:importedRichText(text,runs)});if(el.querySelector('tspan[x],tspan[y],tspan[dx],tspan[dy]'))warnings.add('Positioned text spans become one editable text flow');}
  else{warnings.add(tag+' omitted');return;}
  nodes.push({id:uid('svg'),...node(type,v)});
 };for(const el of svg.children)walk(el,root,computed(svg),view);return{nodes,warnings:[...warnings],name:nodes[0].name};
}
