import test from 'node:test';
import assert from 'node:assert/strict';
import {deflateRawSync} from 'node:zlib';
import {readZip,writeZip,archiveJSON,crc32} from '../src/services/archive.js';
import {decodeFigma,decodeSketch,portableArchive,decodePackage} from '../src/services/interchange.js';
import {DocumentStore} from '../src/core/store.js';
import {node,validateValues,validateSnapshot} from '../src/core/schema.js';
import {richRuns,richString} from '../src/core/richtext.js';
import {restoreAsEdits} from '../src/services/persistence.js';
import {applyGenerated} from '../src/services/import.js';
const frame={x:20,y:30,width:300,height:200};
function fixtureStore(){const s=new DocumentStore('alice');s.add({entity:'project',name:'Fixture'},'project');s.add(node('frame',{w:300,h:200}),'frame');s.add(node('text',{parent:'frame',text:'Hello world'}),'text');s.formatText('text',6,5,{bold:true,color:'#6655aa'});return s;}
function compressedZip(name,text){const nb=Buffer.from(name),src=Buffer.from(text),data=deflateRawSync(src),h=Buffer.alloc(30+nb.length),c=Buffer.alloc(46+nb.length),e=Buffer.alloc(22);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(8,8);h.writeUInt32LE(crc32(src),14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(src.length,22);h.writeUInt16LE(nb.length,26);nb.copy(h,30);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(8,10);c.writeUInt32LE(crc32(src),16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(src.length,24);c.writeUInt16LE(nb.length,28);nb.copy(c,46);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(1,8);e.writeUInt16LE(1,10);e.writeUInt32LE(c.length,12);e.writeUInt32LE(h.length+data.length,16);return Buffer.concat([h,data,c,e]);}
test('portable ZIP preserves complete native document, Unicode and rich text',async()=>{const s=fixtureStore();s.set('project',{name:'Διαδρομή 🌱'});assert.deepEqual(await decodePackage(portableArchive(s)),s.snapshot());const zip=await readZip(writeZip({'folder/é.txt':'🌿', 'manifest.json':'{"version":1}'}));assert.equal(new TextDecoder().decode(zip.get('folder/é.txt')),'🌿');assert.equal(archiveJSON(zip,'manifest.json').version,1);});
test('ZIP accepts bounded deflate and rejects CRC damage, expansion bombs and unsafe paths',async()=>{const z=compressedZip('a.json','{"value":"some fixture text"}');assert.equal(archiveJSON(await readZip(z),'a.json').value,'some fixture text');const bad=z.slice();bad[31]^=1;await assert.rejects(readZip(bad));await assert.rejects(readZip(compressedZip('a','a'.repeat(1000000))),/budget/);for(const n of ['../secrets','/etc/passwd','a\\b','a/../b','a:b'])assert.throws(()=>writeZip({[n]:'x'}),/Unsafe/);const broken=writeZip({'a':'abcdef'});broken[31]^=1;await assert.rejects(readZip(broken),/integrity/);});
test('public REST JSON imports nested transforms, curved paths and mixed text with stable remapping',()=>{const design=decodeFigma({name:'REST fixture',document:{type:'DOCUMENT',children:[{type:'CANVAS',children:[{id:'1:0',name:'Frame',type:'FRAME',size:{x:300,y:200},relativeTransform:[[1,0,20],[0,1,30]],children:[{id:'1:1',type:'TEXT',name:'Title',characters:'Hi 🌿',size:{x:140,y:30},relativeTransform:[[1,0,12],[0,1,18]],style:{fontFamily:'Inter',fontSize:20},fills:[{type:'SOLID',color:{r:0,g:0,b:0}}],characterStyleOverrides:[0,0,1,1,1],styleOverrideTable:{1:{fontWeight:700,fontSize:24}}},{id:'1:2',type:'VECTOR',size:{x:60,y:60},relativeTransform:[[1,0,4],[0,1,6]],fillGeometry:[{path:'M0 0 C0 60 60 0 60 60 L0 60Z',windingRule:'EVENODD'}],fills:[{type:'SOLID',color:{r:1,g:0,b:0}}]}]}]}]}});assert.equal(design.nodes.length,3);const text=design.nodes.find(n=>n.type==='text');assert.equal(richString(text.richText),'Hi 🌿');assert.equal(richRuns(text).at(-1).marks.bold,true);assert.ok(design.nodes.find(n=>n.type==='path').path.includes('C'));const store=new DocumentStore();applyGenerated(store,design,100);validateSnapshot(store.snapshot());assert.equal(store.children('')[0].transform[4],120);assert.equal(store.all().find(n=>n.type==='text').parent,store.children('')[0].id);});
test('documented Sketch ZIP imports pages, attributed text, paths and embedded raster assets',async()=>{const document={name:'Archive fixture',pages:[{_ref:'pages/page'}]};const page={layers:[{_class:'artboard',do_objectID:'FRAME',name:'Artboard',frame,layers:[{_class:'text',do_objectID:'TEXT',name:'Text',frame:{x:10,y:20,width:200,height:30},attributedString:{string:'Design',attributes:[{location:0,length:6,attributes:{MSAttributedStringFontAttribute:{attributes:{name:'Inter-Bold',size:20}},MSAttributedStringColorAttribute:{red:.2,green:.3,blue:.4,alpha:1}}}]}},{_class:'shapePath',do_objectID:'PATH',frame:{x:0,y:0,width:100,height:100},isClosed:true,points:[{point:'{0,0}',hasCurveFrom:true,curveFrom:'{0.3,0.5}'},{point:'{1,0}',hasCurveTo:true,curveTo:'{0.7,0.5}'},{point:'{1,1}'}]},{_class:'bitmap',do_objectID:'IMAGE',frame:{x:0,y:0,width:10,height:10},image:{_ref:'images/a'}}]}]};const data=writeZip({'document.json':JSON.stringify(document),'pages/page.json':JSON.stringify(page),'images/a':new Uint8Array([137,80,78,71,13,10,26,10])});const design=await decodeSketch(data);assert.equal(design.nodes.length,4);assert.ok(design.nodes.some(n=>n.src?.startsWith('data:image/png;base64,')));assert.ok(design.nodes.find(n=>n.type==='path').path.includes('C'));assert.equal(richRuns(design.nodes.find(n=>n.type==='text'))[0].marks.bold,true);});
test('checkpoint restoration creates new character edits rather than unioning old text histories',()=>{const s=fixtureStore(),snap=s.snapshot();s.editText('text',0,11,'Changed');restoreAsEdits(s,snap);assert.equal(s.get('text').text,'Hello world');assert.equal(richRuns(s.get('text')).at(-1).marks.bold,true);s.undo();assert.equal(s.get('text').text,'Changed');s.redo();assert.equal(s.get('text').text,'Hello world');});
test('schema rejects CSS payloads, invalid colors and overdeep trees',()=>{for(const values of [{align:'left;background:url(https://bad.test)'},{gradientStops:[{offset:0,color:'#12345'},{offset:1,color:'#123456'}]},{strokeDash:'1px; x'},{fontSize:1e10},{richText:{}}])assert.throws(()=>validateValues(values));const s=new DocumentStore();let parent='';for(let i=0;i<131;i++){s.add(node('group',{parent}),'d'+i);parent='d'+i;}assert.throws(()=>validateSnapshot(s.snapshot()),/128/);});
