"""Native file-input conversions, editable SVG round-trip and CSP behavior in Chromium."""
import os,json,shlex
from pathlib import Path
from playwright.sync_api import sync_playwright
BASE=os.getenv('MIREVA_URL','http://127.0.0.1:4173/');OUT=Path(os.getenv('MIREVA_TEST_OUTPUT','test-artifacts/interchange'));OUT.mkdir(parents=True,exist_ok=True)
results=[]
def passed(n,d=None):results.append({'test':n,'passed':True,'details':d});print('PASS',n,d or '',flush=True)
svg='''<svg xmlns="http://www.w3.org/2000/svg" width="400" height="240" viewBox="0 0 400 240"><title>Interchange fixture</title><defs><style>.heading {font-size:24px;fill:#332244;font-family:Arial}</style><linearGradient id="g"><stop offset="0" stop-color="#9975d4"/><stop offset=".5" stop-color="#ccaadd"/><stop offset="1" stop-color="#eeddee"/></linearGradient><clipPath id="clip"><rect x="10" y="12" width="320" height="180" rx="12"/></clipPath></defs><g transform="translate(12 8)" clip-path="url(#clip)"><rect x="0" y="0" width="380" height="200" fill="url(#g)"/><text class="heading" x="24" y="54">Hello <tspan font-weight="bold" fill="#704090">design</tspan></text><path d="M20 100 Q100 20 180 100 T340 100 L340 180 L20 180Z" fill="#7655aa" fill-rule="evenodd" stroke="#ffffff" stroke-width="2" stroke-dasharray="4 3"/></g><script>window.SVG_EXECUTED=true</script><foreignObject width="10" height="10"><div xmlns="http://www.w3.org/1999/xhtml" onload="window.SVG_EXECUTED=true"/></foreignObject></svg>'''
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=shlex.split(os.getenv('MIREVA_BROWSER_ARGS','--no-sandbox')));page=b.new_page(viewport={'width':1600,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));response=page.goto(BASE+'?renderer=canvas');page.wait_for_function('()=>window.__MIREVA_READY__')
 try:
  csp=response.headers.get('content-security-policy','');assert "'nonce-" in csp and "script-src 'self' 'unsafe-inline'" not in csp
  page.evaluate('()=>{const s=document.createElement("script");s.textContent="window.UNTRUSTED_SCRIPT_EXECUTED=true";document.head.append(s)}');assert not page.evaluate('()=>!!window.UNTRUSTED_SCRIPT_EXECUTED');passed('Nonce CSP blocks injected inline script while application modules load')
  before=page.evaluate('()=>mireva.store.all().length');page.locator('#file-input').set_input_files({'name':'fixture.svg','mimeType':'image/svg+xml','buffer':svg.encode()});page.wait_for_function('(n)=>mireva.store.all().length>n',arg=before);assert not page.evaluate('()=>!!window.SVG_EXECUTED')
  info=page.evaluate('''()=>{const ns=mireva.store.all();return{rich:ns.find(n=>n.text==='Hello design')?.richText,masked:ns.some(n=>n.maskPath),gradient:ns.some(n=>n.gradientStops?.length===3),curves:ns.some(n=>n.path?.includes('C')&&n.strokeDash==='4 3')}}''');assert all(info.values());passed('SVG file input imports nested transforms, cubic paths, clips, gradient stops and mixed typography without executing scripts')
  report=page.evaluate('''async()=>{const {decodeSVG}=await import('./src/services/svg-import.js'),{svgExport,htmlExport}=await import('./src/services/export.js'),{richRuns}=await import('./src/core/richtext.js'),a=svgExport(mireva.store),doc=new DOMParser().parseFromString(a,'image/svg+xml');if(doc.querySelector('parsererror'))throw Error(doc.querySelector('parsererror').textContent);const b=decodeSVG(a),text=b.nodes.find(n=>n.text==='Hello design');return{xml:!doc.querySelector('parsererror'),editable:b.editable,count:b.nodes.length,bold:richRuns(text).some(r=>r.marks.bold),html:htmlExport(mireva.store).includes('font-weight:700'),path:doc.querySelectorAll('path').length}}''');assert report['xml'] and report['editable'] and report['bold'] and report['html'];passed('Editable SVG metadata round-trips mixed text and vector scene; exported XML is well-formed',report)
  # Fit import for evidence, without discarding source nodes.
  page.screenshot(path=str(OUT/'imported-svg-editor.png'))
  fig={'document':{'type':'DOCUMENT','children':[{'type':'CANVAS','children':[{'id':'0:1','type':'FRAME','name':'REST import','absoluteBoundingBox':{'x':0,'y':0,'width':300,'height':180},'children':[{'id':'0:2','type':'TEXT','name':'JSON heading','characters':'Documented JSON','absoluteBoundingBox':{'x':15,'y':20,'width':230,'height':40},'style':{'fontSize':20},'fills':[{'type':'SOLID','color':{'r':0.3,'g':0.2,'b':0.5}}]}]}]}]}}
  page.locator('#file-input').set_input_files({'name':'public-rest.json','mimeType':'application/json','buffer':json.dumps(fig).encode()});page.wait_for_function('()=>mireva.store.all().some(n=>n.text==="Documented JSON")');passed('Public design REST JSON imports through native file input')
  with page.expect_download() as dl:page.evaluate('()=>mireva.exec("export-package")')
  file=OUT/'roundtrip.mireva.zip';dl.value.save_as(file);count=page.evaluate('()=>mireva.store.all().length');page.locator('#file-input').set_input_files(str(file));page.wait_for_timeout(800);assert page.evaluate('()=>mireva.store.all().length')==count;passed('Portable ZIP exports and reopens the editable full project')
  assert not errors,errors;passed('No unhandled browser errors',errors)
 except Exception as e:
  results.append({'test':'Execution','passed':False,'error':str(e),'errors':errors});page.screenshot(path=str(OUT/'failure.png'));raise
 finally:(OUT/'results.json').write_text(json.dumps(results,indent=2));b.close()
