/** Reproducible bounded local load check, not a production capacity claim. */
import {createMirevaServer} from '../server/index.mjs';
import {DocumentStore} from '../src/core/store.js';import {node} from '../src/core/schema.js';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const dir=await mkdtemp(path.join(os.tmpdir(),'mireva-load-')),app=await createMirevaServer({dataDir:dir,port:0}),base='http://127.0.0.1:'+app.port;
try{
 const s=new DocumentStore('fixture');s.transact('Large fixture',()=>{s.add({entity:'project',name:'Load fixture'},'project');for(let i=0;i<1000;i++)s.add(node('rect',{x:(i%40)*170,y:Math.floor(i/40)*110}),'shape'+i);},{history:false});
 const create=await fetch(base+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({snapshot:s.snapshot()})}),room=await create.json();if(!create.ok)throw Error(room.error);const route=base+'/api/rooms/'+room.id,latencies=[],start=performance.now(),before=process.memoryUsage().rss;
 await Promise.all(Array.from({length:8},(_,writer)=>(async()=>{for(let i=1;i<=30;i++){const at=performance.now(),r=await fetch(route+'/ops',{method:'POST',headers:{Authorization:'Bearer '+room.token,'Content-Type':'application/json'},body:JSON.stringify({client:'writer'+writer,ops:[{id:'shape'+writer,values:{x:i},stamp:[s.clock+i,'writer'+writer]}]})});const b=await r.json();if(!r.ok)throw Error(b.error);latencies.push(performance.now()-at);}})()));
 const elapsed=performance.now()-start,r=await fetch(route,{headers:{Authorization:'Bearer '+room.token}}),final=await r.json();if(final.revision!==240)throw Error('Missing journal revisions');for(let i=0;i<8;i++)if(final.snapshot.records['shape'+i].x!==30)throw Error('Lost update');latencies.sort((a,b)=>a-b);const percentile=p=>latencies[Math.min(latencies.length-1,Math.floor(latencies.length*p))];
 const result={scope:'Synthetic loopback HTTP check, single local Node process, no external traffic, not a capacity guarantee',node:process.version,platform:process.platform,cpus:os.cpus().length,records:1001,concurrentWriters:8,acknowledgedBatches:240,failures:0,elapsedMs:+elapsed.toFixed(1),batchesPerSecond:+(240000/elapsed).toFixed(1),latencyMs:{p50:+percentile(.5).toFixed(2),p95:+percentile(.95).toFixed(2),max:+latencies.at(-1).toFixed(2)},rssDeltaMB:+((process.memoryUsage().rss-before)/1048576).toFixed(1),verifiedFinalRevision:final.revision};console.log(JSON.stringify(result,null,2));if(process.env.REPORT)await writeFile(process.env.REPORT,JSON.stringify(result,null,2));
}finally{await app.close();await rm(dir,{recursive:true,force:true});}
