import test from 'node:test';
import assert from 'node:assert/strict';
import {fork} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {once} from 'node:events';
import os from 'node:os';import path from 'node:path';
import {DocumentStore} from '../src/core/store.js';import {node} from '../src/core/schema.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function worker(dir){const child=fork(new URL('./fixtures/server-worker.mjs',import.meta.url),[],{env:{...process.env,TEST_DATA:dir},stdio:['ignore','ignore','pipe','ipc']});let errors='';child.stderr.on('data',c=>errors+=c);const data=await Promise.race([once(child,'message').then(([v])=>v),once(child,'exit').then(()=>{throw Error(errors)}),delay(10000).then(()=>{throw Error('Worker startup timeout')})]);return{child,base:'http://127.0.0.1:'+data.port};}
async function request(base,route,method='GET',body,token){const r=await fetch(base+route,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const b=await r.json();assert.ok(r.ok,JSON.stringify(b));return b;}
test('separate OS processes exchange live journal edits, deduplicate retries and recover acknowledged writes after SIGKILL',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'mireva-process-')),workers=[];t.after(async()=>{for(const w of workers)if(w.child.exitCode===null&&w.child.signalCode===null){w.child.kill('SIGKILL');await once(w.child,'exit').catch(()=>{});}await rm(dir,{recursive:true,force:true});});let a=await worker(dir),b=await worker(dir);workers.push(a,b);const s=new DocumentStore('writer');s.add({entity:'project',name:'Crash fixture'},'project');s.add(node('rect'),'shape');const room=await request(a.base,'/api/rooms','POST',{snapshot:s.snapshot()});const route='/api/rooms/'+room.id,abort=new AbortController(),response=await fetch(b.base+route+'/events?client=other',{headers:{Authorization:'Bearer '+room.token},signal:abort.signal});const packets=[],read=(async()=>{const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';try{for(;;){const r=await reader.read();if(r.done)break;buffer+=decoder.decode(r.value,{stream:true});let i;while((i=buffer.indexOf('\n\n'))>=0){packets.push(buffer.slice(0,i));buffer=buffer.slice(i+2);}}}catch{}})();const until=async fn=>{for(let i=0;i<150;i++){if(fn())return;await delay(20);}throw Error('Live packet did not arrive');};await until(()=>packets.some(p=>p.includes('event: hello')));let ops; s.on(e=>{if(e.local)ops=e.ops;});s.set('shape',{x:321});const first=await request(a.base,route+'/ops','POST',{ops,client:'writer'},room.token);await until(()=>packets.some(p=>p.includes('event: ops')&&p.includes('321')));const duplicate=await request(b.base,route+'/ops','POST',{ops,client:'writer'},room.token);assert.equal(duplicate.revision,first.revision);assert.equal(duplicate.duplicate,true);for(let i=1;i<=17;i++){s.set('shape',{y:i});await request(i%2?a.base:b.base,route+'/ops','POST',{ops,client:'writer'},room.token);}assert.equal((await request(b.base,route,'GET',null,room.token)).snapshot.records.shape.y,17);abort.abort();await read;a.child.kill('SIGKILL');b.child.kill('SIGKILL');await Promise.all([once(a.child,'exit'),once(b.child,'exit')]);const c=await worker(dir);workers.push(c);const restored=await request(c.base,route,'GET',null,room.token);assert.equal(restored.snapshot.records.shape.x,321);assert.equal(restored.snapshot.records.shape.y,17);assert.equal(restored.revision,18);t.diagnostic('Two independently spawned Node processes; 18 acknowledged transactions; abrupt SIGKILL of both and WAL restart.');});
