import test from 'node:test';
import assert from 'node:assert/strict';
import {DocumentStore} from '../src/core/store.js';
import {node, validateSnapshot} from '../src/core/schema.js';
import {richAtoms, richRuns} from '../src/core/richtext.js';
const make = actor => { const s = new DocumentStore(actor); s.add(node('text',{text:'Hello world'}),'text1'); s.undoStack=[]; return s; };
function peers() { const a=make('alice'), b=new DocumentStore('bob');b.load(a.snapshot());const ao=[],bo=[];a.on(e=>{if(e.local)ao.push(...e.ops)});b.on(e=>{if(e.local)bo.push(...e.ops)});return{a,b,ao,bo}; }
test('concurrent character insertions preserve both runs and converge',()=>{const{a,b,ao,bo}=peers();a.editText('text1',5,0,' dear');b.editText('text1',5,0,' lovely');a.receive(bo);b.receive(ao);assert.equal(a.get('text1').text,b.get('text1').text);assert.match(a.get('text1').text,/dear/);assert.match(a.get('text1').text,/lovely/);validateSnapshot(a.snapshot());});
test('out-of-order character deletion and formatting converge',()=>{const{a,b,ao}=peers();a.editText('text1',5,0,'✨');a.formatText('text1',5,1,{bold:true,color:'#123456'});a.editText('text1',5,1,'');b.receive([...ao].reverse());assert.equal(b.get('text1').text,a.get('text1').text);assert.deepEqual(richAtoms(b.get('text1').richText),richAtoms(a.get('text1').richText));});
test('concurrent range emphasis merges independent marks',()=>{const{a,b,ao,bo}=peers();a.formatText('text1',0,5,{bold:true});b.formatText('text1',0,5,{italic:true});a.receive(bo);b.receive(ao);const run=richRuns(a.get('text1'))[0];assert.equal(run.text,'Hello');assert.equal(run.marks.bold,true);assert.equal(run.marks.italic,true);assert.deepEqual(richRuns(a.get('text1')),richRuns(b.get('text1')));});
test('selective text undo never deletes a concurrent insertion and supports redo',()=>{const{a,b,ao,bo}=peers();a.editText('text1',5,0,' Alice');b.editText('text1',5,0,' Bob');a.receive(bo);b.receive(ao);a.undo();assert.ok(!a.get('text1').text.includes('Alice'));assert.ok(a.get('text1').text.includes('Bob'));a.redo();assert.ok(a.get('text1').text.includes('Alice'));assert.ok(a.get('text1').text.includes('Bob'));});
test('text deletion, Unicode, mark undo, snapshot merge and ordinary set use character ops',()=>{const s=make('s');s.set('text1',{text:'Hi 👩🏽‍💻世界'});assert.equal(s.get('text1').text,'Hi 👩🏽‍💻世界');s.undo();assert.equal(s.get('text1').text,'Hello world');s.redo();assert.equal(s.get('text1').text,'Hi 👩🏽‍💻世界');s.formatText('text1',0,2,{bold:true});s.undo();assert.ok(!richRuns(s.get('text1'))[0].marks.bold);s.redo();assert.equal(richRuns(s.get('text1'))[0].marks.bold,true);const b=new DocumentStore('b');b.merge(s.snapshot());assert.equal(b.get('text1').text,s.get('text1').text);});
test('failed multi-operation receive and transactions are atomic',()=>{const s=make('s'),snapshot=JSON.stringify(s.snapshot());assert.throws(()=>s.transact('bad',()=>{s.editText('text1',0,0,'bad');s.set('text1',{fill:'javascript:bad'})}));assert.equal(JSON.stringify(s.snapshot()),snapshot);});
test('concurrent reparenting projects to the same visible, cycle-free tree',()=>{const a=new DocumentStore('a');a.add(node('group'),'one');a.add(node('group'),'two');const b=new DocumentStore('b');b.load(a.snapshot());const ao=[],bo=[];a.on(e=>{if(e.local)ao.push(...e.ops)});b.on(e=>{if(e.local)bo.push(...e.ops)});a.set('one',{parent:'two'});b.set('two',{parent:'one'});a.receive(bo);b.receive(ao);assert.deepEqual([...a.effectiveParents()],[...b.effectiveParents()]);assert.equal(a.children('').length,1);assert.equal(a.descendants(a.children('')[0].id).length,1);});
