import {createRichText,richAtoms,richRuns,relativeTextPosition,resolveTextPosition,minimalTextDiff} from '../core/richtext.js';
import {textStyle,richFontFamily} from '../render/richlayout.js';

/** A native contenteditable surface backed by character operations, not innerHTML. */
export class RichTextEditor {
  constructor(store,renderer,id,{onClose=()=>{},onPresence=()=>{},onError=()=>{}}={}) {
    Object.assign(this,{store,renderer,id,onClose,onPresence,onError});this.node=store.get(id);this.typingMarks=null;this.composing=false;this.disposed=false;
    this.area=document.createElement('div');this.area.className='text-editor rich-text-editor';this.area.contentEditable='true';this.area.setAttribute('role','textbox');this.area.setAttribute('aria-label','Edit rich text');this.area.setAttribute('aria-multiline','true');this.area.spellcheck=true;
    this.toolbar=document.createElement('div');this.toolbar.className='rich-toolbar';this.toolbar.setAttribute('role','toolbar');this.toolbar.setAttribute('aria-label','Rich text formatting');
    this.toolbar.innerHTML='<button data-mark="bold" aria-label="Bold" title="Bold · Ctrl B"><b>B</b></button><button data-mark="italic" aria-label="Italic" title="Italic · Ctrl I"><i>I</i></button><button data-mark="underline" aria-label="Underline" title="Underline · Ctrl U"><u>U</u></button><button data-mark="strike" aria-label="Strikethrough"><s>S</s></button><i></i><label title="Text color">A<input data-mark="color" type="color" aria-label="Selected text color" value="#302641"></label><label title="Highlight">▰<input data-mark="highlight" type="color" aria-label="Selected text highlight" value="#fff1a8"></label><select data-mark="fontFamily" aria-label="Selected text font"><option>Inter</option><option>Arial</option><option>Georgia</option><option>monospace</option><option>Verdana</option></select><input data-mark="fontSize" aria-label="Selected text font size" type="number" min="4" max="512" value="16"><button data-link aria-label="Link selected text" title="Add or remove a link">↗</button><button data-clear aria-label="Clear selected text formatting" title="Clear formatting">Tx</button><i></i><button data-done aria-label="Finish editing text" title="Done · Ctrl Enter">✓</button>';
    renderer.host.append(this.area,this.toolbar);
    for(const event of ['pointerdown','pointermove','pointerup','dblclick','click','contextmenu'])this.area.addEventListener(event,e=>e.stopPropagation());
    this.toolbar.addEventListener('pointerdown',e=>{e.stopPropagation();this.bookmark=this.capture();if(e.target.closest('button'))e.preventDefault();});
    this.toolbar.addEventListener('click',e=>{e.stopPropagation();const button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-done')){this.close();return;}if(button.hasAttribute('data-link')){this.linkDialog();return;}if(button.hasAttribute('data-clear')){this.format({bold:null,italic:null,underline:null,strike:null,color:null,highlight:null,fontSize:null,fontFamily:null,link:null});return;}if(button.dataset.mark){const current=this.selectionMarks();this.format({[button.dataset.mark]:!current[button.dataset.mark]});}});
    this.toolbar.addEventListener('change',e=>{if(!e.target.dataset.mark)return;const key=e.target.dataset.mark;this.format({[key]:key==='fontSize'?Math.max(4,Math.min(512,+e.target.value||16)):e.target.value});});
    this.area.addEventListener('beforeinput',e=>this.beforeInput(e));this.area.addEventListener('input',()=>{if(!this.composing)this.reconcileDOM();});
    this.area.addEventListener('compositionstart',()=>{this.composing=true;this.compositionBefore=this.store.get(id)?.text||'';this.compositionAtoms=this.atoms;this.compositionRange=this.range();});
    this.area.addEventListener('compositionend',()=>{this.composing=false;this.reconcileDOM(true);});
    this.area.addEventListener('paste',e=>this.paste(e));this.area.addEventListener('cut',e=>{const range=this.range();if(range.start===range.end)return;e.preventDefault();e.clipboardData.setData('text/plain',[...this.store.get(id).text].slice(range.start,range.end).join(''));this.replace(range,'');});
    this.area.addEventListener('keydown',e=>{e.stopPropagation();const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(e.key==='Escape'||mod&&e.key==='Enter'){e.preventDefault();this.close();return;}if(mod&&['b','i','u'].includes(k)){e.preventDefault();const key={b:'bold',i:'italic',u:'underline'}[k];this.format({[key]:!this.selectionMarks()[key]});}if(mod&&['z','y'].includes(k)){e.preventDefault();k==='y'||e.shiftKey?store.redo():store.undo();}});
    this.outside=e=>{if(!this.disposed&&!this.area.contains(e.target)&&!this.toolbar.contains(e.target)&&!this.linkPanel?.contains(e.target))this.close();};
    document.addEventListener('pointerdown',this.outside,true);
    this.selectionChange=()=>{if(this.disposed||!this.area.contains(document.getSelection()?.anchorNode))return;this.bookmark=this.capture();this.refreshToolbar();const range=this.range();this.onPresence({node:this.id,anchor:relativeTextPosition(this.atoms,range.anchor),focus:relativeTextPosition(this.atoms,range.focus)});};document.addEventListener('selectionchange',this.selectionChange);
    this.unsub=store.on(()=>{if(!store.get(id)){this.close();return;}if(!this.composing)this.render(true);});
    this.render(false);this.area.focus();this.setSelection(0,this.atoms.length);this.position();
  }
  state(){return this.store.get(this.id)?.richText||createRichText(this.store.get(this.id)?.text||'');}
  offset(node,offset){try{const range=document.createRange();range.selectNodeContents(this.area);range.setEnd(node,offset);return [...range.toString()].length;}catch{return 0;}}
  range(){const selection=document.getSelection();if(selection&&this.area.contains(selection.anchorNode)&&this.area.contains(selection.focusNode)){const anchor=this.offset(selection.anchorNode,selection.anchorOffset),focus=this.offset(selection.focusNode,selection.focusOffset);return{anchor,focus,start:Math.min(anchor,focus),end:Math.max(anchor,focus)};}if(this.bookmark){const state=this.state(),anchor=resolveTextPosition(state,this.bookmark.anchor),focus=resolveTextPosition(state,this.bookmark.focus);return{anchor,focus,start:Math.min(anchor,focus),end:Math.max(anchor,focus)};}return{anchor:0,focus:0,start:0,end:0};}
  capture(){const r=this.range();return{anchor:relativeTextPosition(this.atoms||[],r.anchor),focus:relativeTextPosition(this.atoms||[],r.focus)};}
  setSelection(anchor,focus=anchor){
    const locate=index=>{const walker=document.createTreeWalker(this.area,NodeFilter.SHOW_TEXT);let text,last;while((text=walker.nextNode())){last=text;const count=[...text.data].length;if(index<=count)return[text,[...text.data].slice(0,index).join('').length];index-=count;}return last?[last,last.data.length]:[this.area,0];};
    const [a,ao]=locate(Math.max(0,anchor)),[f,fo]=locate(Math.max(0,focus));const selection=document.getSelection();selection.setBaseAndExtent(a,ao,f,fo);this.bookmark=this.capture();
  }
  render(preserve=true){
    const bookmark=preserve?this.capture():null,n=this.store.get(this.id);if(!n)return;this.atoms=richAtoms(this.state());this.node=n;const fragment=document.createDocumentFragment();
    for(const run of richRuns(n)){const span=document.createElement('span'),s=textStyle(n,run.marks);span.textContent=run.text;Object.assign(span.style,{fontFamily:richFontFamily(s.fontFamily),fontSize:s.fontSize+'px',fontWeight:String(s.fontWeight),fontStyle:s.italic?'italic':'normal',color:s.color,backgroundColor:s.highlight||'transparent',textDecoration:[s.underline||s.link?'underline':'',s.strike?'line-through':''].filter(Boolean).join(' ')||'none'});if(s.link)span.title=s.link;fragment.append(span);}
    if(!fragment.childNodes.length)fragment.append(document.createTextNode(''));this.area.replaceChildren(fragment);this.position();
    if(bookmark){const state=this.state();this.setSelection(resolveTextPosition(state,bookmark.anchor),resolveTextPosition(state,bookmark.focus));}this.refreshToolbar();
  }
  position(){if(this.disposed)return;const item=this.renderer.scene().find(i=>i.n.id===this.id);if(!item)return;const n=this.store.get(this.id),m=item.matrix,z=this.renderer.camera.z,p=this.renderer.screen({x:m[4],y:m[5]});
    Object.assign(this.area.style,{left:p.x+'px',top:p.y+'px',width:n.w+'px',height:Math.max(n.h,n.fontSize*1.5)+'px',transform:`matrix(${m[0]*z},${m[1]*z},${m[2]*z},${m[3]*z},0,0)`,transformOrigin:'0 0',fontFamily:richFontFamily(n.fontFamily),fontSize:n.fontSize+'px',fontWeight:String(n.fontWeight||400),lineHeight:String(n.lineHeight||1.35),letterSpacing:(n.letterSpacing||0)+'px',textAlign:n.align||'left',padding:n.type==='text'?'0':'0 15px'});
    Object.assign(this.toolbar.style,{left:Math.max(8,Math.min(this.renderer.width-510,p.x))+'px',top:Math.max(8,p.y-48)+'px'});
  }
  selectionMarks(){const r=this.range(),atoms=this.atoms.slice(r.start,r.end),sample=atoms[0]||this.atoms[Math.max(0,r.start-1)];return this.typingMarks||sample?.marks||{};}
  refreshToolbar(){const marks=this.selectionMarks();for(const button of this.toolbar.querySelectorAll('button[data-mark]'))button.classList.toggle('active',!!marks[button.dataset.mark]);const size=this.toolbar.querySelector('[data-mark="fontSize"]');if(document.activeElement!==size)size.value=marks.fontSize||this.node.fontSize||16;}
  format(marks){try{const r=this.range();this.area.focus({preventScroll:true});if(r.start!==r.end){this.store.formatText(this.id,r.start,r.end-r.start,marks);this.setSelection(r.anchor,r.focus);}else this.typingMarks={...this.selectionMarks(),...marks};this.refreshToolbar();}catch(e){this.onError(e.message);}}
  replace(range,text,marks=this.typingMarks){try{this.store.editText(this.id,range.start,range.end-range.start,text,marks);const caret=range.start+[...text].length;this.setSelection(caret);this.bookmark=this.capture();}catch(e){this.onError(e.message);this.render();}}
  beforeInput(e){if(this.composing||e.isComposing||e.inputType==='insertCompositionText')return;const r=this.range(),type=e.inputType;
    if(['insertText','insertReplacementText','insertParagraph','insertLineBreak'].includes(type)){e.preventDefault();this.replace(r,type==='insertParagraph'||type==='insertLineBreak'?'\n':e.data||'');}
    else if(type.startsWith('delete')){e.preventDefault();if(r.start===r.end){const text=[...this.node.text];if(type.includes('Backward')){let count=1;if(type.includes('Word')){const left=text.slice(0,r.start).join(''),word=left.match(/\s*\S+\s*$/u)?.[0];count=[...(word||'')].length||1;}r.start=Math.max(0,r.start-count);}else{let count=1;if(type.includes('Word')){const word=text.slice(r.end).join('').match(/^\s*\S+\s*/u)?.[0];count=[...(word||'')].length||1;}r.end=Math.min(text.length,r.end+count);}}this.replace(r,'');}
    else if(type==='historyUndo'||type==='historyRedo'){e.preventDefault();type==='historyUndo'?this.store.undo():this.store.redo();}
    else if(type.startsWith('format')){const key={formatBold:'bold',formatItalic:'italic',formatUnderline:'underline',formatStrikeThrough:'strike'}[type];if(key){e.preventDefault();this.format({[key]:!this.selectionMarks()[key]});}}
  }
  reconcileDOM(composition=false){
    const after=this.area.innerText.replace(/\r/g,''),before=composition?this.compositionBefore:this.store.get(this.id).text;if(after===before)return;
    const diff=minimalTextDiff(before,after);
    if(composition){const state=this.state(),start=resolveTextPosition(state,relativeTextPosition(this.compositionAtoms,diff.start)),end=resolveTextPosition(state,relativeTextPosition(this.compositionAtoms,diff.start+diff.count));this.replace({start,end},diff.text);}else this.replace({start:diff.start,end:diff.start+diff.count},diff.text);
  }
  paste(e){e.preventDefault();e.stopPropagation();const text=e.clipboardData?.getData('text/plain')||'';this.replace(this.range(),text.slice(0,20000));}
  linkDialog(){
    this.bookmark=this.capture();this.linkPanel?.remove();const panel=document.createElement('form');panel.className='rich-link-panel';panel.innerHTML='<label>Selected text link<input name="url" type="url" placeholder="https://example.com" aria-label="Rich text link URL"></label><button class="button primary" type="submit">Apply</button><button class="button" type="button" data-remove>Remove link</button>';this.renderer.host.append(panel);this.linkPanel=panel;panel.style.left=this.toolbar.style.left;panel.style.top=(parseFloat(this.toolbar.style.top)+48)+'px';panel.elements.url.value=this.selectionMarks().link||'';
    panel.addEventListener('pointerdown',e=>e.stopPropagation());panel.addEventListener('submit',e=>{e.preventDefault();const value=panel.elements.url.value;if(value&&!/^(https?:\/\/|mailto:)/i.test(value)){this.onError('Use an HTTPS, HTTP, or mailto link');return;}this.format({link:value||null});panel.remove();this.linkPanel=null;});panel.querySelector('[data-remove]').onclick=()=>{this.format({link:null});panel.remove();this.linkPanel=null;};panel.elements.url.focus();
  }
  close(){if(this.disposed)return;if(this.composing){this.composing=false;this.reconcileDOM(true);}this.disposed=true;this.unsub?.();document.removeEventListener('selectionchange',this.selectionChange);document.removeEventListener('pointerdown',this.outside,true);this.area.remove();this.toolbar.remove();this.linkPanel?.remove();this.onClose();}
}
