import {Vector,VectorWorker} from '../core/vector.js';
import {node,clone,uid} from '../core/schema.js';
import {point,inverse,mul,localMatrix} from '../core/geometry.js';
/** Native anchor editor; calculations run in the independent vector worker. */
export class VectorEditor {
 constructor(store,renderer,editor,{canEdit=()=>true,onError=()=>{},onChange=()=>{}}={}){
  Object.assign(this,{store,renderer,editor,canEdit,onError,onChange});this.worker=new VectorWorker();this.active=false;this.selected=new Set();this.host=renderer.host;
  this.svg=document.createElementNS('http://www.w3.org/2000/svg','svg');this.svg.classList.add('vector-overlay');this.svg.hidden=true;this.host.append(this.svg);
  this.toolbar=document.createElement('div');this.toolbar.className='vector-toolbar';this.toolbar.hidden=true;this.host.append(this.toolbar);
  this.toolbar.innerHTML='<strong>Vector path</strong>'+[['corner','Corner'],['smooth','Smooth'],['symmetric','Symmetric'],['split','Split segment'],['remove','Delete point'],['closed','Open / close'],['reverse','Reverse'],['cancel','Cancel'],['done','Done']].map(([a,b])=>`<button data-vector-action="${a}" title="${b}">${b}</button>`).join('');
  for(const name of ['pointerdown','pointermove','pointerup','dblclick'])this.toolbar.addEventListener(name,e=>e.stopPropagation());
  this.toolbar.addEventListener('click',e=>{const b=e.target.closest('[data-vector-action]');if(b){e.stopPropagation();this.action(b.dataset.vectorAction);}});
  for(const [name,fn] of [['pointerdown','down'],['pointermove','move'],['pointerup','up'],['pointercancel','up']])this.host.addEventListener(name,e=>{if(!this.active||e.target.closest('.vector-toolbar'))return;try{this[fn](e);}catch(err){this.onError(err.message);this.stop(false);}},true);
  this.host.addEventListener('dblclick',e=>{if(this.active){e.preventDefault();e.stopImmediatePropagation();if(this.pen)this.stop(true);}},true);
  document.addEventListener('keydown',e=>{if(!this.active||e.target.matches('input,textarea,select,[contenteditable="true"]'))return;const k=e.key.toLowerCase();if(['escape','enter','delete','backspace','a'].includes(k)){e.preventDefault();e.stopImmediatePropagation();if(k==='escape')this.stop(false);else if(k==='enter')this.stop(true);else if(k==='a'&&(e.ctrlKey||e.metaKey)){this.parts.forEach((p,i)=>p.points.forEach((_,j)=>this.selected.add(i+':'+j)));this.render();}else if(['delete','backspace'].includes(k))this.action('remove');}},true);
  this.unsubscribe=store.on(e=>{if(this.active&&this.id&&!store.get(this.id)){this.stop(false);return;}if(this.active&&!e.local&&e.ops.some(o=>o.id===this.id)){this.onError('Path changed remotely. Reopen it to edit the updated geometry.');this.stop(false);}});
 }
 start(id){if(!this.canEdit())throw Error('An editor role is required');this.stop(true);const n=this.store.get(id);if(!n||n.locked||!['path','line','rect','ellipse'].includes(n.type))throw Error('Select an unlocked vector, line, rectangle, or ellipse');this.id=id;this.original=clone(n);this.parts=Vector.nodeParts(n);this.pen=false;this.begin();}
 startPen(){if(!this.canEdit())throw Error('An editor role is required');this.stop(true);this.id=null;this.original=node('path',{x:0,y:0,w:1,h:1,fill:'none',stroke:'#8265c9',strokeWidth:2,name:'Bézier path'});this.parts=[{closed:false,points:[]}];this.pen=true;this.begin();}
 begin(){this.active=true;this.selected.clear();this.editor.cancel();this.editor.vectorActive=true;this.svg.hidden=false;this.toolbar.hidden=false;this.toolbar.querySelector('strong').textContent=this.pen?'Pen · click or drag':'Vector path';this.host.style.cursor=this.pen?'crosshair':'';this.render();this.renderer.invalidate();}
 matrix(){if(!this.id)return[1,0,0,1,0,0];const parent=this.original.parent?this.renderer.scene().find(i=>i.n.id===this.original.parent)?.matrix:null;return mul(parent||[1,0,0,1,0,0],localMatrix(this.original));}
 local(e){const r=this.host.getBoundingClientRect(),w=this.renderer.world({x:e.clientX-r.left,y:e.clientY-r.top});return point(inverse(this.matrix()),w.x,w.y);}
 key(part,index){return part+':'+index;}
 down(e){if(e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();const handle=e.target.closest('[data-anchor]'),p=this.local(e);let part,index,kind='point';
  if(handle){[part,index,kind]=handle.dataset.anchor.split(':');part=+part;index=+index;const key=this.key(part,index);if(this.pen&&part===0&&index===0&&this.parts[0].points.length>2){this.parts[0].closed=true;this.stop(true);return;}if(e.shiftKey&&kind==='point'){this.selected.has(key)?this.selected.delete(key):this.selected.add(key);}else if(!this.selected.has(key)){this.selected.clear();this.selected.add(key);}}
  else if(this.pen){part=0;index=this.parts[0].points.length;this.parts[0].points.push(Vector.anchor(p.x,p.y,'symmetric'));this.selected.clear();this.selected.add(this.key(part,index));kind='pen';}
  else{this.selected.clear();this.render();return;}
  this.drag={part,index,kind,start:p,parts:clone(this.parts)};this.host.setPointerCapture(e.pointerId);this.render();
 }
 move(e){if(!this.drag)return;e.preventDefault();e.stopImmediatePropagation();const d=this.drag,p=this.local(e),dx=p.x-d.start.x,dy=p.y-d.start.y;this.parts=clone(d.parts);const a=this.parts[d.part].points[d.index];if(!a)return;
  if(d.kind==='point'){for(const key of this.selected){const [pi,ai]=key.split(':').map(Number),b=this.parts[pi]?.points[ai];if(b){for(const f of ['x','inX','outX'])b[f]+=dx;for(const f of ['y','inY','outY'])b[f]+=dy;}}}
  else{let x=p.x,y=p.y;if(e.shiftKey){const angle=Math.round(Math.atan2(y-a.y,x-a.x)/(Math.PI/4))*Math.PI/4,r=Math.hypot(x-a.x,y-a.y);x=a.x+Math.cos(angle)*r;y=a.y+Math.sin(angle)*r;}const side=d.kind==='in'?'in':'out',other=side==='in'?'out':'in',length=Math.hypot(a[other+'X']-a.x,a[other+'Y']-a.y);a[side+'X']=x;a[side+'Y']=y;if(e.altKey)a.mode='corner';if(d.kind==='pen'||!e.altKey&&a.mode!=='corner'){const vx=x-a.x,vy=y-a.y,r=Math.hypot(vx,vy)||1,f=(a.mode==='symmetric'||d.kind==='pen')?1:length/r;a[other+'X']=a.x-vx*f;a[other+'Y']=a.y-vy*f;}}
  this.preview();this.render();
 }
 up(e){if(!this.drag)return;e.preventDefault();e.stopImmediatePropagation();this.drag=null;if(this.host.hasPointerCapture(e.pointerId))this.host.releasePointerCapture(e.pointerId);this.preview();this.render();}
 preview(){if(this.id)this.renderer.setPreview(new Map([[this.id,{type:'path',path:Vector.serialize(this.parts),pathW:this.original.w,pathH:this.original.h}]]));}
 action(action){try{if(action==='done'||action==='cancel'){this.stop(action==='done');return;}const grouped=new Map();for(const key of this.selected){const [p,i]=key.split(':').map(Number);if(!grouped.has(p))grouped.set(p,[]);grouped.get(p).push(i);}if(!grouped.size&&this.parts.length)grouped.set(0,[0]);
  for(const [p,indices] of grouped){const part=this.parts[p];if(!part)continue;if(action==='closed')part.closed=!part.closed;else if(action==='reverse')Vector.reverse(part);else if(action==='remove'){for(const i of indices.sort((a,b)=>b-a))part.points.splice(i,1);if(part.points.length<3)part.closed=false;}else if(action==='split'){for(const i of indices.sort((a,b)=>b-a)){if(i<part.points.length-1||part.closed)Vector.splitSegment(part,i,.5);}}else for(const i of indices)Vector.smooth(part,i,action);}
  this.selected.clear();this.preview();this.render();
 }catch(e){this.onError(e.message);}}
 stop(commit=true){if(!this.active)return;const id=this.id,parts=this.parts,original=this.original;this.active=false;this.drag=null;this.editor.vectorActive=false;this.renderer.setPreview(new Map());this.svg.hidden=true;this.svg.innerHTML='';this.toolbar.hidden=true;this.host.style.cursor='';
  if(commit&&parts.some(p=>p.points.length>=2)){let target=id;const values=Vector.normalizeNode(original,parts);this.store.transact(id?'Edit vector anchors':'Draw Bézier path',()=>{if(id)this.store.set(id,values);else target=this.store.add(node('path',{...original,...values}),uid('path'));});this.editor.select([target]);this.onChange();}this.renderer.invalidate();
 }
 render(){if(!this.active)return;const r=this.renderer,m=this.matrix();this.svg.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);const screen=(x,y)=>r.screen(point(m,x,y));const transformed=Vector.transform(this.parts,[r.camera.z*m[0],r.camera.z*m[1],r.camera.z*m[2],r.camera.z*m[3],r.camera.x+r.camera.z*m[4],r.camera.y+r.camera.z*m[5]]);let html=`<path d="${Vector.serialize(transformed)}" fill="none" stroke="#926cde" stroke-width="1.5"/>`;
  for(let pi=0;pi<this.parts.length;pi++)for(let ai=0;ai<this.parts[pi].points.length;ai++){const a=this.parts[pi].points[ai],p=screen(a.x,a.y),selected=this.selected.has(this.key(pi,ai));if(selected)for(const side of ['in','out']){const h=screen(a[side+'X'],a[side+'Y']);html+=`<line x1="${p.x}" y1="${p.y}" x2="${h.x}" y2="${h.y}" stroke="#a484d8"/><circle data-anchor="${pi}:${ai}:${side}" cx="${h.x}" cy="${h.y}" r="4" fill="white" stroke="#926cde"/>`;}html+=`<rect data-anchor="${pi}:${ai}:point" x="${p.x-4}" y="${p.y-4}" width="8" height="8" fill="${selected?'#926cde':'white'}" stroke="#926cde"/>`;}
  this.svg.innerHTML=html;
 }
 async combine(operation,tolerance=.25){if(!this.canEdit())throw Error('An editor role is required');this.stop(true);const ids=[...this.editor.selection],nodes=ids.map(id=>this.store.get(id));if(nodes.length<2||nodes.some(n=>!n||n.locked))throw Error('Select at least two unlocked filled shapes');if(nodes.some(n=>n.parent!==nodes[0].parent))throw Error('Boolean operands must have the same parent');const before=JSON.stringify(nodes),operands=nodes.map(n=>{const p=Vector.nodeParts(n);if(p.some(s=>!s.closed))throw Error('Close open paths before combining fills');return{path:Vector.transform(p,localMatrix(n)),fillRule:n.fillRule};});const result=await this.worker.run(operands,operation,tolerance);if(JSON.stringify(ids.map(id=>this.store.get(id)))!==before)throw Error('Operands changed while calculating. Retry with the latest geometry.');if(!result.path)throw Error('The result is empty; source shapes were kept');const first=nodes[0],parts=Vector.parse(result.path);let id;this.store.transact('Boolean '+operation,()=>{id=this.store.add(node('path',{...Vector.normalizeNode({x:0,y:0,w:1,h:1,rotation:0},parts),parent:first.parent,order:Math.max(...nodes.map(n=>n.order||0))+1,name:operation[0].toUpperCase()+operation.slice(1),fill:first.fill||'#ece8ff',stroke:first.stroke||'none',strokeWidth:first.strokeWidth||0,opacity:first.opacity??1,fillRule:'evenodd'}));for(const source of ids)this.store.set(source,{hidden:true});});this.editor.select([id]);this.onChange();return{id,tolerance:result.tolerance,sourceIds:ids};}
 destroy(){this.stop(false);this.unsubscribe();this.worker.cancel();this.svg.remove();this.toolbar.remove();}
}
