import {escapeHTML as esc,download} from '../services/export.js';
import {clone,uid} from '../core/schema.js';
import {applyGenerated,readImage} from '../services/import.js';
const date=n=>n?new Date(n).toLocaleString():'—';
const button=(label,action,id='',kind='')=>`<button type="button" class="button ${kind}" data-ws-action="${action}" data-ws-id="${esc(id)}">${label}</button>`;
const field=(label,name,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,options,value='')=>`<label>${label}<select name="${name}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
const form=(name,body,label='Save')=>`<form data-ws-form="${name}" class="modal-form ws-form">${body}<div class="modal-actions"><button class="button primary" type="submit">${label}</button></div><p class="ws-form-error" role="alert"></p></form>`;
/** Account, team, policy and cloud-project UI. Every action calls a permission-checked API. */
export class WorkspaceUI {
 constructor(api,{store,sync,editor,dialog,toast,onOpen=async()=>{},onImport=()=>{},close=()=>{}}){Object.assign(this,{api,store,sync,editor,dialog,toast,onOpen,onImport,close});this.orgId='';this.tab='projects';this.organizations=[];this.sequence=0;this.jobTimer=null;this.image=null;
  document.addEventListener('click',e=>{const b=e.target.closest('[data-ws-action]');if(!b)return;e.preventDefault();e.stopPropagation();this.run(()=>this.action(b.dataset.wsAction,b.dataset.wsId,b));});
  document.addEventListener('submit',e=>{const f=e.target.closest('[data-ws-form]');if(!f)return;e.preventDefault();e.stopPropagation();const body=Object.fromEntries(new FormData(f));for(const i of f.querySelectorAll('input[type="checkbox"]'))body[i.name]=i.checked;const b=f.querySelector('button[type="submit"]');b.disabled=true;this.run(()=>this.submit(f.dataset.wsForm,body),f).finally(()=>b.disabled=false);});
  document.addEventListener('change',e=>{if(e.target.id==='ws-org')this.run(()=>{this.orgId=e.target.value;return this.show(this.tab);});if(e.target.id==='ws-ai-image')this.run(async()=>{this.image=e.target.files[0]?await readImage(e.target.files[0]):null;document.querySelector('#ws-image-state').textContent=this.image?'Attached · '+e.target.files[0].name:'No image attached';});});
  this.api.onChange=state=>{const label=document.querySelector('#account-label');if(label)label.textContent=state.user?.name||'Workspace';};
 }
 async run(fn,form){try{return await fn();}catch(e){if(form?.isConnected){form.querySelector('.ws-form-error').textContent=e.message;}else this.toast(e.message,true);}}
 orgPath(suffix=''){if(!this.orgId)throw Error('Select an organization first');return'/api/orgs/'+this.orgId+suffix;}
 async request(path,method='GET',body){return this.api.request(path,{method,body});}
 async initialize(){if(!this.api.server)return;try{await this.api.refresh();}catch{return;}const hash=new URLSearchParams(location.hash.slice(1));this.invite=hash.get('org-invite')||sessionStorage.getItem('mireva-org-invite')||'';if(this.invite)sessionStorage.setItem('mireva-org-invite',this.invite);this.reset=hash.get('reset');if(this.reset||hash.has('account')||this.invite){history.replaceState(null,'',location.pathname+location.search);await this.show(this.reset?'reset':'projects');}}
 authView(kind='login',message=''){const state=this.api.state;let body='';
  if(this.reset||kind==='reset')body=form('reset',field('New password','password','password','','minlength="12" required autocomplete="new-password"'),'Reset password');
  else if(state.needsMfa)body=form('mfa-verify',field('Authenticator or recovery code','code','text','','required autocomplete="one-time-code"'),'Verify and sign in');
  else if(kind==='register')body=form('register',field('Your name','name','text','','required maxlength="80" autocomplete="name"')+field('Email address','email','email','','required autocomplete="email"')+field('Password · at least 12 characters','password','password','','required minlength="12" autocomplete="new-password"'),'Create account')+button('Already registered? Sign in','login');
  else if(kind==='forgot')body=form('forgot',field('Account email','email','email','','required autocomplete="email"'),'Send reset link')+button('Back to sign in','login');
  else body=form('login',field('Email address','email','email','','required autocomplete="username"')+field('Password','password','password','','required autocomplete="current-password"'),'Sign in')+`<div class="ws-inline">${state.registration?button('Create an account','register'):''}${button('Forgot password?','forgot')}${button('Resend verification','resend')}</div>`;
  this.dialog(this.reset?'Reset your password':'Your Mireva workspace',`<div class="ws-auth"><div class="ws-auth-art"><span class="ws-monogram">m</span><h2>A shared home<br>for better ideas.</h2><p>Verified identities. Live collaboration.<br>One place for your team’s work.</p></div><div><h3>${state.needsMfa?'Verify your identity':kind==='register'?'Create your account':kind==='forgot'?'Recover access':this.reset?'Choose a new password':'Welcome back'}</h3>${message?`<div class="notice">${esc(message)}</div>`:''}${this.invite?'<p class="notice">An organization invitation is ready. Sign in using the invited email address.</p>':''}${body}${!this.reset&&!state.needsMfa?(state.providers||[]).map(p=>button('Continue with '+esc(p.name),'sso',p.id)).join(''):''}${state.developmentMail?'<p class="muted">Development mail is written to the server’s private mail directory. Production uses configured SMTP or an email webhook.</p>':''}</div></div>`,{wide:true});
 }
 async show(tab='projects'){if(!this.api.server){this.dialog('Local editor · server services',`<div class="notice"><strong>This editor is running without the Mireva server.</strong><p>Canvas editing, local projects, imports, exports, components and interactive prototypes work in your browser. Accounts, organization workspaces, durable live collaboration and connected AI require the included Node.js server.</p><p>Download the source, use Node.js 22.16 or later, run <code>npm start</code>, then open <code>http://localhost:4173</code>. Export a .mireva project to move your local design to that server.</p><p>Your local projects have not been uploaded.</p></div>`);return;}clearTimeout(this.jobTimer);this.tab=tab;await this.api.refresh();if(!this.api.state.user||tab==='reset'){this.authView(tab);return;}if(this.invite){await this.request('/api/orgs/accept','POST',{token:this.invite});this.invite='';sessionStorage.removeItem('mireva-org-invite');this.toast('Organization invitation accepted');}
  const seq=++this.sequence;this.organizations=(await this.request('/api/orgs')).organizations;if(this.orgId&&!this.organizations.some(o=>o.id===this.orgId))this.orgId='';this.org=this.organizations.find(o=>o.id===this.orgId);const tabs=[['projects','Projects'],...(this.orgId?[['members','People'],['library','Team library'],['policy','Policies'],['audit','Audit log']]:[]),['security','Account & security'],['ai','AI generation'],['publish','Publishing']];if(!tabs.some(([k])=>k===tab))this.tab=tab='projects';
  this.dialog('Workspace',`<div class="ws-shell"><aside class="ws-sidebar"><div class="ws-person"><span class="avatar">${esc(this.api.state.user.name[0])}</span><strong>${esc(this.api.state.user.name)}</strong><small>${esc(this.api.state.user.email)}</small></div><label class="ws-org-label">Organization<select id="ws-org"><option value="">Personal workspace</option>${this.organizations.map(o=>`<option value="${o.id}" ${o.id===this.orgId?'selected':''}>${esc(o.name)} · ${o.role}</option>`).join('')}</select></label>${button('+ New organization','new-org') }<nav>${tabs.map(([k,v])=>button(v,'tab',k,k===tab?'active':'')).join('')}</nav>${button('Sign out','logout')}</aside><section class="ws-content" id="ws-content"><p class="muted">Loading workspace…</p></section></div>`,{wide:true});
  let content='';try{content=await this.content(tab);}catch(e){content='<div class="notice warning">'+esc(e.message)+'</div>'+(e.code==='sso_required'&&this.org?.settings.ssoProvider?button('Sign in with required SSO','sso',this.org.settings.ssoProvider):'');}if(seq===this.sequence&&document.querySelector('#ws-content'))document.querySelector('#ws-content').innerHTML=content;
 }
 async content(tab){const admin=!this.org||['owner','admin'].includes(this.org.role),head=(title,desc='')=>`<div class="ws-page-head"><h2>${title}</h2><p>${desc}</p></div>`;
  if(tab==='projects'){const data=await this.request(this.orgId?this.orgPath('/projects'+(this.archived?'?archived=true':'')):'/api/rooms');return head(esc(this.org?.name||'Personal projects'),'Account-owned projects sync through the collaboration server.')+`<div class="ws-inline">${button('Save current design here','save-cloud','','primary')}${button(this.archived?'Show active':'Show archived','archived')}</div><div class="ws-projects">${data.projects.filter(p=>this.orgId||!!p.archivedAt===!!this.archived).map(p=>`<article class="ws-project"><div class="ws-project-art">▱<span>${p.records||''} layers</span></div><h3>${esc(p.name)}</h3><p>Revision ${p.revision} · ${date(p.updatedAt)}</p><div class="ws-inline">${p.archivedAt?button('Restore','restore-project',p.id):button('Open design','open-project',p.id,'primary')}${!p.archivedAt?button('Archive','archive-project',p.id):''}</div></article>`).join('')||'<div class="ws-empty"><strong>Your next idea starts here.</strong><p>Save the current canvas to create the first shared project.</p></div>'}</div>`;}
  if(tab==='members'){const {members}=await this.request(this.orgPath('/members')),invites=admin?(await this.request(this.orgPath('/invites'))).invites:[];return head('People & permissions','Only verified accounts can accept email-bound invitations.')+(admin?form('invite',`<div class="ws-form-row">${field('Email address','email','email','','required')}${select('Role','role',['admin','member','viewer'],'member')}</div>`,'Send invitation'):'')+`<div class="ws-table">${members.map(m=>`<div class="ws-table-row"><span class="avatar">${esc(m.name[0])}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.email)}</small></div>${admin?`<select aria-label="Role for ${esc(m.name)}" data-member-role="${m.id}">${['owner','admin','member','viewer'].map(r=>`<option ${m.role===r?'selected':''}>${r}</option>`).join('')}</select>${button('Update','member-role',m.id)}${button('Remove','member-remove',m.id)}`:`<span class="role-pill">${m.role}</span>`}</div>`).join('')}</div><h3>Invitations</h3>${invites.map(i=>`<div class="ws-table-row"><div>${esc(i.email)}<small>${i.role} · ${i.accepted?'Accepted':i.expires<Date.now()?'Expired':'Pending until '+date(i.expires)}</small></div>${!i.accepted?button('Revoke','invite-revoke',i.id):''}</div>`).join('')||'<p class="muted">No pending invitations.</p>'}`;}
  if(tab==='library'){const {items}=await this.request(this.orgPath('/library'));return head('Team library','Versioned components, templates and shared palettes.')+button('Publish current design as a library item','library-new','','primary')+`<div class="ws-table">${items.map(i=>`<div class="ws-table-row"><span class="ws-library-icon">◇</span><div><strong>${esc(i.name)}</strong><small>${i.kind} · revision ${i.revision} · ${date(i.updatedAt)}</small></div>${button('Insert','library-insert',i.id)}${button('Update','library-update',i.id)}${admin?button('Delete','library-delete',i.id):''}</div>`).join('')||'<p class="muted">Publish a library item to share it across projects.</p>'}</div>`;}
  if(tab==='policy'){const {organization:o,usage,providers}=await this.request(this.orgPath()),s=o.settings;return head('Organization policies','Access rules are checked on project reads, writes and live connections.')+`<div class="ws-metrics"><div><strong>${usage.members}</strong><span>Members</span></div><div><strong>${usage.projects||usage.count||0}</strong><span>Projects</span></div><div><strong>${((usage.bytes||0)/1048576).toFixed(1)} MB</strong><span>Stored project payloads</span></div></div>`+form('policy',field('Organization name','name','text',o.name,'required maxlength="100"')+select('Required sign-in provider','ssoProvider',[['','Any configured sign-in method'],...providers.map(p=>[p.id,p.name])],s.ssoProvider||'')+select('Default member project access','defaultProjectRole',['editor','commenter','viewer'],s.defaultProjectRole)+['allowGuestInvites','allowPublicPrototypes','membersCanCreate'].map((k,i)=>`<label class="ws-check"><input type="checkbox" name="${k}" ${s[k]?'checked':''}>${['Allow guest invitation links','Allow public prototype publishing','Members may create projects'][i]}</label>`).join('')+`<div class="ws-form-row">${field('Member limit','memberLimit','number',s.memberLimit,'min="1" max="10000"')}${field('Project limit','projectLimit','number',s.projectLimit,'min="1" max="10000"')}${field('Storage MB','storageMB','number',s.storageMB,'min="10" max="100000"')}${field('Daily AI requests','aiDailyRequests','number',s.aiDailyRequests,'min="0" max="10000"')}${field('Audit retention days','auditRetentionDays','number',s.auditRetentionDays,'min="30" max="3650"')}</div>`,'Apply policies')+(!admin?'<p class="muted">Changes require an administrator role.</p>':'')+(o.role==='owner'?button('Delete organization','delete-org','','danger'):'');}
  if(tab==='audit'){const data=await this.request(this.orgPath('/audit?after='+(this.auditAfter||0)+'&limit=100'));this.auditData=data;return head('Audit trail','Security and workspace events with a per-organization hash chain.')+`<div class="notice">Chain verification: ${data.integrity.valid?'passed':'FAILED'} · ${data.entries.length} events shown</div><div class="ws-inline">${button('Download this page','audit-download')}${button('Next page','audit-next')}${button('Apply retention policy','audit-retention')}</div><div class="ws-audit">${data.entries.map(a=>`<article><time>${date(a.at)}</time><strong>${esc(a.action)}</strong><small>Actor ${esc(a.actor||'system')} · ${esc(a.target||'')}</small><code>${esc(a.payload)}</code></article>`).join('')||'<p>No events in this page.</p>'}</div>`;}
  if(tab==='security'){const u=this.api.state.user,{sessions}=await this.api.auth('sessions',undefined,'GET'),{identities}=await this.api.auth('identities',undefined,'GET');return head('Account & security',esc(u.email)+' · verified')+form('profile',field('Display name','name','text',u.name,'required maxlength="80"'))+`<details class="ws-details"><summary>Change password</summary>${form('password-change',field('Current password','currentPassword','password','','autocomplete="current-password"')+field('New password','password','password','','required minlength="12" autocomplete="new-password"'),'Change password')}</details><details class="ws-details"><summary>Authenticator · ${u.mfaEnabled?'enabled':'not enabled'}</summary><p>Time-based codes and eight single-use recovery codes. Security changes require your password or a recent SSO sign-in.</p>${form(u.mfaEnabled?'mfa-disable':'mfa-enroll',field('Current password','password','password','','autocomplete="current-password"')+(u.mfaEnabled?field('Authenticator or recovery code','code','text','','required'):''),u.mfaEnabled?'Disable authenticator':'Set up authenticator')}</details><h3>Identity providers</h3>${(this.api.state.providers||[]).map(p=>`<div class="ws-table-row"><div>${esc(p.name)}<small>${identities.some(i=>i.provider===p.id)?'Linked identity':'Not linked'}</small></div>${button(identities.some(i=>i.provider===p.id)?'Unlink':'Link identity',identities.some(i=>i.provider===p.id)?'sso-unlink':'sso-link',p.id)}</div>`).join('')||'<p class="muted">Configure OIDC_PROVIDERS on the server to enable SSO.</p>'}<h3>Active sessions</h3>${sessions.map(s=>`<div class="ws-table-row"><div><strong>${esc(s.method)} ${s.current?'· this device':''}</strong><small>${esc(s.agent)}<br>Last active ${date(s.last_seen)}</small></div>${button('Revoke','session-revoke',s.id)}</div>`).join('')}${button('Sign out every device','logout-all','','danger')}`;}
  if(tab==='ai'){if(!this.sync.config)return head('Connected AI')+'<p class="notice">Open or save an account-owned project first. The local Compose template engine remains available without a model.</p>';const {providers}=await (await this.sync.request('/ai/providers')).json(),{jobs}=await(await this.sync.request('/ai/jobs')).json();this.providers=providers;return head('Connected AI','Generation sends your prompt and optional image/context to the selected provider. Keys stay server-side.')+(providers.length?form('ai-generate',select('Model provider','provider',providers.map(p=>[p.id,p.name+' · '+p.model+(p.vision?' · vision':'')]))+'<label>Instructions<textarea name="prompt" rows="4" required maxlength="12000" placeholder="Create an accessible three-screen travel planner…"></textarea></label>'+select('Device','device',['mobile','tablet','desktop'],'mobile')+'<label>Optional reference image<input id="ws-ai-image" type="file" accept="image/png,image/jpeg,image/webp"></label><small id="ws-image-state">'+(this.image?'Image attached':'No image attached')+'</small><label class="ws-check"><input type="checkbox" name="includeContext"> Include current design structure as context</label>','Generate editable screens'):'<div class="notice warning">No provider is configured. Set AI_PROVIDERS, or AI_URL + AI_MODEL + AI_KEY, in the server environment. The app does not pretend to generate with an unavailable model.</div>')+`<h3>Generation history</h3>${jobs.map(j=>`<div class="ws-table-row"><div><strong>${esc(j.provider)} · ${esc(j.status)}</strong><small>${date(j.createdAt)} ${esc(j.error||'')}</small></div>${j.status==='running'?button('Cancel','ai-cancel',j.id):j.status==='completed'?button('Insert result','ai-insert',j.id):''}</div>`).join('')||'<p class="muted">No generation jobs yet.</p>'}`+(this.orgId&&admin?'<h3>Organization credentials</h3>'+form('ai-provider',select('Configured provider','id',providers.map(p=>[p.id,p.name]))+field('Model identifier','model','text','','required')+field('API key · leave empty to keep existing','key','password','','autocomplete="off"'),'Save encrypted credentials'):'');}
  if(tab==='publish'){if(!this.sync.config)return head('Publishing')+'<p class="notice">Open a shared project to publish an interactive prototype.</p>';const {publications}=await(await this.sync.request('/publish')).json();return head('Public prototypes','Publishing creates a snapshot. Later edits are private until you publish another snapshot.')+form('publish',field('Title','title','text',this.store.get('project')?.name||'Prototype','required maxlength="100"')+field('Expires after days','days','number',30,'min="1" max="365"'),'Publish snapshot')+publications.map(p=>`<div class="ws-table-row"><div><strong>${esc(p.title)}</strong><small>${p.enabled?'Expires '+date(p.expires):'Disabled'}</small><a href="${esc(this.api.server+'/p/'+p.id)}" target="_blank" rel="noopener noreferrer">Open prototype</a></div>${p.enabled?button('Unpublish','unpublish',p.id):''}</div>`).join('')+ (this.sync.config.account&&this.sync.role==='owner'?`<h3>Project-level access</h3><p class="muted">Overrides apply to existing organization members. Organization owners and administrators retain management access.</p>${form('project-member',field('Verified account email','email','email','','required')+select('Project role','role',['editor','commenter','viewer']),'Assign project role')}${button('Show project overrides','project-members')}`:'');}
  return '';
 }
 async action(action,id,el){if(action==='tab')return this.show(id);if(['login','register','forgot'].includes(action))return this.authView(action);
  if(action==='sso'){location.assign(this.api.server+'/api/auth/oidc/'+encodeURIComponent(id)+'/start');return;}
  if(action==='resend'){this.dialog('Resend verification',form('resend',field('Email','email','email','','required'),'Send verification'));return;}
  if(action==='logout'||action==='logout-all'){if(this.sync.config?.account){this.sync.disconnect();await this.onOpen(null);}await this.api.auth(action,{});return this.show();}
  if(action==='new-org'){this.dialog('Create an organization',form('org-create',field('Organization name','name','text','','required maxlength="100"'),'Create workspace'));return;}
  if(action==='save-cloud'){this.dialog('Save to '+esc(this.org?.name||'personal workspace'),form('cloud-save',field('Project name','name','text',this.store.get('project')?.name||'Untitled','required maxlength="100"'),'Save and collaborate'));return;}
  if(action==='open-project'){await this.onOpen(null);await this.api.connect(this.sync,id,this.orgId);await this.onOpen(id);this.close();return;}
  if(action==='archived'){this.archived=!this.archived;return this.show('projects');}
  if(action==='archive-project'||action==='restore-project'){await this.request('/api/rooms/'+id+'/archive','POST',{archived:action==='archive-project'});if(action==='archive-project'&&id===this.sync.config?.id){this.sync.disconnect();await this.onOpen(null);}return this.show('projects');}
  if(action==='member-role'){const role=document.querySelector(`[data-member-role="${id}"]`).value;await this.request(this.orgPath('/members/'+id),'PATCH',{role});return this.show('members');}
  if(action==='member-remove'){this.confirm('Remove organization member?','Existing shared-project access will be revoked.',()=>this.request(this.orgPath('/members/'+id),'DELETE').then(()=>this.show('members')));return;}
  if(action==='invite-revoke'){await this.request(this.orgPath('/invites/'+id),'DELETE');return this.show('members');}
  if(action==='library-new'){this.dialog('Publish team library item',form('library-new',field('Name','name','text',this.store.get('project')?.name||'Library','required')+select('Kind','kind',['components','template','palette'])+field('Palette colors (comma separated; only used for palette items)','colors','text',[...new Set(this.store.all().flatMap(n=>[n.fill,n.color]).filter(c=>/^#[0-9a-f]{6}$/i.test(c)))].slice(0,12).join(', '))+'<p class="muted">Publishes the current editable document, including its frames and components.</p>','Publish'));return;}
  if(action==='library-insert'){const item=await this.request(this.orgPath('/library/'+id));if(item.kind==='palette'){this.dialog(esc(item.name),'<div class="ws-palette">'+item.payload.map(c=>`<button data-ws-action="palette" data-ws-id="${c}" style="background:${c}">${c}</button>`).join('')+'</div>');return;}const nodes=Object.values(item.payload.records).filter(n=>n.entity==='node'&&!n.deleted).map(({_stamps,...n})=>n);applyGenerated(this.store,{nodes},Math.max(0,...this.store.children('').map(n=>n.x+n.w))+80);this.onImport();this.close();return;}
  if(action==='palette'){this.store.transact('Apply shared palette',()=>{for(const node of this.editor.selection)this.store.set(node,{fill:id});});return;}
  if(action==='library-update'){const item=await this.request(this.orgPath('/library/'+id));if(item.kind==='palette'){this.editingLibrary=item;this.dialog('Update shared palette',form('library-palette',field('Name','name','text',item.name,'required')+field('Colors (comma separated)','colors','text',item.payload.join(', '),'required'),'Publish revision'));return;}this.confirm('Publish a new library revision?','The current design will replace the shared payload. A revision check prevents overwriting concurrent updates.',async()=>{await this.request(this.orgPath('/library/'+id),'PUT',{name:item.name,kind:item.kind,revision:item.revision,payload:this.store.snapshot()});await this.show('library');});return;}
  if(action==='library-delete'){this.confirm('Delete library item?','This does not remove already inserted components.',()=>this.request(this.orgPath('/library/'+id),'DELETE').then(()=>this.show('library')));return;}
  if(action==='audit-download'){download('mireva-audit.json',JSON.stringify(this.auditData,null,2),'application/json');return;}if(action==='audit-next'){this.auditAfter=this.auditData.next;return this.show('audit');}if(action==='audit-retention'){const result=await this.request(this.orgPath('/audit'),'DELETE');this.toast(result.removed+' old audit entries removed');this.auditAfter=0;return this.show('audit');}
  if(action==='delete-org'){this.dialog('Delete organization',form('org-delete',field('Type the organization name to confirm','name','text','','required')+field('Current password · recent SSO for SSO-only accounts','password','password')+'<p class="notice warning">Projects will be archived and organization access disabled.</p>','Delete organization'));return;}
  if(action==='session-revoke'){await this.api.auth('sessions/'+id,undefined,'DELETE');return this.show('security');}
  if(action==='sso-link'||action==='sso-unlink'){this.identityAction={id,action};this.dialog(action==='sso-link'?'Link identity provider':'Unlink identity provider',form('identity',field('Current password · leave blank for recent SSO','password','password'),'Continue'));return;}
  if(action==='ai-cancel'){await this.sync.request('/ai/jobs/'+id,{method:'DELETE'});return this.show('ai');}
  if(action==='ai-insert'){const job=await(await this.sync.request('/ai/jobs/'+id)).json();if(job.status!=='completed'||!job.response)throw Error('This job has no completed result');applyGenerated(this.store,job.response,Math.max(0,...this.store.children('').map(n=>n.x+n.w))+80);this.onImport();this.close();return;}
  if(action==='unpublish'){await this.sync.request('/publish/'+id,{method:'DELETE'});return this.show('publish');}
  if(action==='project-members'){const {members}=await(await this.sync.request('/members')).json();this.dialog('Project role overrides',members.map(m=>`<div class="ws-table-row"><div>${esc(m.name)}<small>${esc(m.email)} · ${m.role}</small></div>${button('Remove override','project-member-remove',m.id)}</div>`).join('')||'<p>No overrides. Organization defaults apply.</p>');return;}
  if(action==='project-member-remove'){await this.sync.request('/members/'+id,{method:'DELETE'});return this.action('project-members');}
  if(action==='confirm'){const fn=this.confirmAction;this.confirmAction=null;if(fn)await fn();}
 }
 confirm(title,text,fn){this.confirmAction=fn;this.dialog(title,`<p>${esc(text)}</p><div class="modal-actions">${button('Confirm','confirm','','danger')}</div>`);}
 async submit(name,b){
  if(name==='login'){await this.api.auth('login',b);return this.show();}
  if(name==='register'){const r=await this.api.auth('register',b);return this.authView('login',r.message);}
  if(name==='forgot'){const r=await this.api.auth('password/reset/request',b);return this.authView('login',r.message);}
  if(name==='resend'){const r=await this.api.auth('verification/resend',b);return this.authView('login',r.message);}
  if(name==='reset'){await this.api.auth('password/reset',{token:this.reset,password:b.password});this.reset=null;return this.authView('login','Password changed. Sign in with the new password.');}
  if(name==='mfa-verify'){await this.api.auth('mfa/verify',b);return this.show();}
  if(name==='profile'){await this.api.auth('profile',b,'PATCH');return this.show('security');}
  if(name==='password-change'){await this.api.auth('password/change',b);this.toast('Password changed; other sessions revoked');return this.show('security');}
  if(name==='mfa-enroll'){const r=await this.api.auth('mfa/enroll',b);this.dialog('Connect your authenticator','<p>Add this secret in your authenticator app. Confirm its six-digit code to finish.</p><pre class="ws-secret">'+esc(r.secret)+'</pre>'+form('mfa-confirm',field('Authenticator code','code','text','','required inputmode="numeric" autocomplete="one-time-code"'),'Enable authenticator'));return;}
  if(name==='mfa-confirm'){const r=await this.api.auth('mfa/confirm',b);this.dialog('Save your recovery codes','<p>Each code works once. These codes are shown only now. Store them somewhere private.</p><pre class="ws-secret">'+r.recoveryCodes.map(esc).join('\n')+'</pre>'+button('Done','tab','security'));return;}
  if(name==='mfa-disable'){await this.api.auth('mfa/disable',b);return this.show('security');}
  if(name==='identity'){const {id,action}=this.identityAction;if(action==='sso-link'){const r=await this.api.auth('oidc/'+id+'/start',{...b,link:true});location.assign(r.url);}else{await this.api.auth('oidc/'+id+'/unlink',b);return this.show('security');}return;}
  if(name==='org-create'){const r=await this.request('/api/orgs','POST',b);this.orgId=r.id;return this.show('projects');}
  if(name==='cloud-save'){await this.onOpen(null);const snapshot=clone(this.store.snapshot());snapshot.records.project.name=b.name;const r=await this.api.create(this.sync,snapshot,this.orgId);this.store.set('project',{name:b.name});await this.onOpen(r.id);this.close();this.toast('Account project created');return;}
  if(name==='invite'){const r=await this.request(this.orgPath('/invites'),'POST',b);this.dialog('Invitation sent',`<p>The invitation is bound to <strong>${esc(r.email)}</strong> and was queued for email delivery.</p><label class="modal-form">Invitation link<input readonly value="${esc(this.api.server+'/#org-invite='+r.token)}"></label>`+button('Back to people','tab','members'));return;}
  if(name==='policy'){const settings={...b};delete settings.name;for(const k of ['memberLimit','projectLimit','storageMB','aiDailyRequests','auditRetentionDays'])settings[k]=Number(settings[k]);await this.request(this.orgPath(),'PATCH',{name:b.name,settings});this.toast('Policies updated');return this.show('policy');}
  if(name==='org-delete'){await this.request(this.orgPath(),'DELETE',{confirm:b.name,password:b.password});this.orgId='';if(this.sync.config?.orgId){this.sync.disconnect();await this.onOpen(null);}return this.show('projects');}
  if(name==='library-new'||name==='library-palette'){const item=name==='library-palette'?this.editingLibrary:null,kind=item?.kind||b.kind,payload=kind==='palette'?b.colors.split(/[,\s]+/).filter(Boolean):this.store.snapshot();await this.request(this.orgPath('/library'+(item?'/'+item.id:'')),item?'PUT':'POST',{name:b.name,kind,revision:item?.revision,payload});return this.show('library');}
  if(name==='ai-generate'){const body={prompt:b.prompt,provider:b.provider,device:b.device,...(this.image?{image:this.image.src}:{}),...(b.includeContext?{context:{nodes:this.store.all().slice(0,600).map(({richText,_stamps,...n})=>n)}}:{})};const result=await(await this.sync.request('/ai/jobs',{method:'POST',body})).json();await this.show('ai');this.pollJob(result.id);return;}
  if(name==='ai-provider'){await this.sync.request('/ai/providers',{method:'PUT',body:b});this.toast('Provider credentials stored encrypted');return this.show('ai');}
  if(name==='publish'){const r=await(await this.sync.request('/publish',{method:'POST',body:{...b,days:Number(b.days)}})).json();this.dialog('Prototype published',`<p>This link opens the published snapshot without an account. It expires automatically.</p><label class="modal-form">Public URL<input readonly value="${esc(r.url)}"></label><a class="button primary" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Open prototype</a>`);return;}
  if(name==='project-member'){await this.sync.request('/members',{method:'PUT',body:b});this.toast('Project role assigned');return this.show('publish');}
 }
 pollJob(id){clearTimeout(this.jobTimer);this.jobTimer=setTimeout(async()=>{if(this.tab!=='ai'||!document.querySelector('#ws-content'))return;try{const job=await(await this.sync.request('/ai/jobs/'+id)).json();await this.show('ai');if(job.status==='running')this.pollJob(id);else this.toast(job.status==='completed'?'Generation ready. Review and insert it from history.':job.error||'Generation '+job.status,job.status!=='completed');}catch(e){this.toast(e.message,true);}},2000);}
}
