import {node,clone,uid} from './schema.js';
import {flatten,union,inverse,point} from './geometry.js';
export function topSelection(store,ids){const s=new Set(ids);return [...s].filter(id=>store.get(id)&&![...s].some(other=>other!==id&&store.isAncestor(other,id)));}
export function duplicate(store,ids,offset=24){const map=new Map(),roots=topSelection(store,ids),all=roots.flatMap(id=>[store.get(id),...store.descendants(id)]);for(const n of all)map.set(n.id,uid());store.transact('Duplicate',()=>{for(const n of all){const{id,_stamps,...v}=clone(n);v.parent=map.get(v.parent)||v.parent;v.target=map.get(v.target)||v.target||'';if(roots.includes(id)){v.x+=offset;v.y+=offset;v.name+=' copy';v.order+=.1;}store.add(v,map.get(id));}});return roots.map(id=>map.get(id));}
export function group(store,ids){const roots=topSelection(store,ids);if(roots.length<2)throw Error('Select at least two elements');const ns=roots.map(id=>store.get(id)),parent=ns[0].parent;if(ns.some(n=>n.parent!==parent||n.type==='frame'))throw Error('Group elements within the same screen');const b=union(ns.map(n=>({x:n.x,y:n.y,w:n.w,h:n.h})));let id;store.transact('Group',()=>{id=store.add(node('group',{...b,parent,fill:'transparent',name:'Group',order:Math.min(...ns.map(n=>n.order))}));for(const n of ns)store.set(n.id,{parent:id,x:n.x-b.x,y:n.y-b.y});});return id;}
export function ungroup(store,id){const g=store.get(id);if(!g||g.type!=='group')return[];const flat=flatten(store),gm=flat.find(i=>i.n.id===id).matrix,pm=g.parent?flat.find(i=>i.n.id===g.parent).matrix:[1,0,0,1,0,0],pi=inverse(pm),children=store.children(id);store.transact('Ungroup',()=>{for(const n of children){const item=flat.find(i=>i.n.id===n.id),center=point(pi,...Object.values(point(item.matrix,n.w/2,n.h/2)));store.set(n.id,{parent:g.parent,x:center.x-n.w/2,y:center.y-n.h/2,rotation:(g.rotation||0)+(n.rotation||0)});}store.set(id,{deleted:true});});return children.map(n=>n.id);}
export function alignNodes(store,ids,kind){const ns=topSelection(store,ids).map(id=>store.get(id));if(!ns.length)return;if(ns.some(n=>n.parent!==ns[0].parent))throw Error('Align elements with the same parent');const b=union(ns);store.transact('Align '+kind,()=>{for(const n of ns){const v=kind==='left'?{x:b.x}:kind==='center'?{x:b.x+(b.w-n.w)/2}:kind==='right'?{x:b.x+b.w-n.w}:kind==='top'?{y:b.y}:kind==='middle'?{y:b.y+(b.h-n.h)/2}:{y:b.y+b.h-n.h};store.set(n.id,v);}});}
export function distribute(store,ids,axis='x'){const ns=topSelection(store,ids).map(id=>store.get(id)).sort((a,b)=>a[axis]-b[axis]);if(ns.length<3)throw Error('Select three or more elements');if(ns.some(n=>n.parent!==ns[0].parent))throw Error('Use elements with the same parent');const dim=axis==='x'?'w':'h',first=ns[0][axis],last=ns.at(-1),gap=(last[axis]+last[dim]-first-ns.reduce((s,n)=>s+n[dim],0))/(ns.length-1);store.transact('Distribute',()=>{let p=first;for(const n of ns){store.set(n.id,{[axis]:p});p+=n[dim]+gap;}});}
export function resizeChildren(store,id,oldW,oldH,newW,newH,scale=false){for(const n of store.children(id)){const childW=n.w,childH=n.h,v={};for(const[axis,dim,oldSize,newSize,c]of[['x','w',oldW,newW,n.constraintX],['y','h',oldH,newH,n.constraintY]]){if(scale||c==='scale'){v[axis]=n[axis]*newSize/oldSize;v[dim]=Math.max(1,n[dim]*newSize/oldSize);}else if(c==='right'||c==='bottom')v[axis]=n[axis]+newSize-oldSize;else if(c==='center')v[axis]=n[axis]+(newSize-oldSize)/2;else if(c==='stretch')v[dim]=Math.max(1,n[dim]+newSize-oldSize);}store.set(n.id,v);if(scale)resizeChildren(store,n.id,childW,childH,v.w??childW,v.h??childH,true);}}
export function reflow(store,id){const p=store.get(id);if(!p||!['row','column'].includes(p.layout))return;const row=p.layout==='row',pad=p.padding??16,gap=p.gap??16;let cursor=pad;store.transact('Auto layout',()=>{for(const n of store.children(id)){let v=row?{x:cursor,y:pad}:{y:cursor,x:pad};if(p.layoutAlign==='center')v[row?'y':'x']=((row?p.h:p.w)-(row?n.h:n.w))/2;if(p.layoutAlign==='stretch')v[row?'h':'w']=Math.max(1,(row?p.h:p.w)-2*pad);store.set(n.id,v);cursor+=(row?n.w:n.h)+gap;}});}
export function makeComponent(store,id){store.transact('Create component',()=>store.set(id,{component:true,componentId:'',name:store.get(id).name.replace(/^Component: /,'').replace(/^/,'Component: ')}));}
export function instantiate(store,id){const roots=duplicate(store,[id]);store.transact('Create instance',()=>{const source=[store.get(id),...store.descendants(id)],copies=[store.get(roots[0]),...store.descendants(roots[0])];for(let i=0;i<copies.length;i++)store.set(copies[i].id,{component:false,componentId:source[i].id,name:source[i].name.replace('Component: ','Instance: ')});});return roots;}
export function syncInstances(store,id){const master=store.get(id);if(!master)return;const ids=[id,...store.descendants(id).map(n=>n.id)];store.transact('Update linked instances',()=>{for(const src of ids){const n=store.get(src);for(const instance of store.all().filter(i=>i.componentId===src)){const{id,_stamps,parent,x,y,order,name,component,componentId,...style}=n;store.set(instance.id,style);}}});}
