import {decodeFigma,decodeSketch,decodePackage,portableArchive} from './services/interchange.js';
import {WorkspaceClient} from './services/workspace.js';
import {WorkspaceUI} from './ui/workspace.js';
import {VectorEditor} from './ui/vector-editor.js';
import {RichTextEditor} from './ui/rich-editor.js';
import {DocumentStore} from './core/store.js';
import {node,uid,clone,validateSnapshot} from './core/schema.js';
import {union,point,inverse,contains,flatten,clamp} from './core/geometry.js';
import {topSelection,duplicate,group,ungroup,alignNodes,distribute,resizeChildren,reflow,makeComponent,instantiate,syncInstances} from './core/commands.js';
import {seedProject,THEMES,insertComponent,blankFrame,composeScreens} from './core/templates.js';
import {Renderer} from './render/renderer.js';
import {fontName} from './render/paint.js';
import {EditorController} from './ui/editor.js';
import {icon,ICONS} from './ui/icons.js';
import {LocalVault,restoreAsEdits} from './services/persistence.js';
import {CollaborationClient} from './services/collaboration.js';
import {escapeHTML as esc,download,svgExport,pngExport,htmlExport,nodeCSS,sceneSubset} from './services/export.js';
import {readImage,importSVG,applyGenerated,extractPalette} from './services/import.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store=new DocumentStore(),vault=new LocalVault(),account=new WorkspaceClient();
let renderer,editor,sync,vector,workspace,documentId=uid('doc'),panel='components',mode='design',search='',category='all',componentTab='all',composeDevice='mobile',composeTheme=0,composePrompt='',composeCount=3,composeMethod='local',clipboard=null,exportScope='selection',exportScale=2,showResolved=false,identity={name:'Designer',color:'#9270c6'},preferences={theme:'light',server:'',snap:true,grid:false},lastInvite='',importPurpose='normal',scanImage=null,localVersions=[],sharedVersions=[],projectList=[],saveTimer,renderTimer,saveChain=Promise.resolve(),editingText=null,collapsed=new Set(),layerRows=[],layerScroll=0,initializing=true,askResolve=null;
let saveError=false;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));}
function toast(message,error=false){const div=document.createElement('div');div.className='toast'+(error?' error':'');div.textContent=message;$('#toasts').append(div);setTimeout(()=>div.remove(),error?7000:3600);}
function busy(button,yes){if(!button)return;button.classList.toggle('busy',yes);button.disabled=yes;}
function canEdit(){return !sync||['local','owner','editor'].includes(sync.role);}
function canComment(){return !sync||['local','owner','editor','commenter'].includes(sync.role);}
function frames(){return store.children('').filter(n=>n.type==='frame');}
function selected(){return [...editor.selection].map(id=>store.get(id)).filter(Boolean);}
function firstSelected(){return selected()[0];}
function activeTheme(){return THEMES.find(t=>t.name===store.get('project')?.theme)||THEMES[0];}
function activeFrame(){const n=firstSelected();if(n?.type==='frame')return n;let p=n;const seen=new Set();while(p?.parent&&!seen.has(p.id)){seen.add(p.id);p=store.get(p.parent);if(p?.type==='frame')return p;}const center=renderer.world({x:renderer.width/2,y:renderer.height/2});return editor.frameAt(center)?.n||frames()[0];}
function rightEdge(){return Math.max(0,...frames().map(n=>n.x+n.w))+80;}
function nextOrder(parent){return Math.max(0,...store.children(parent).map(n=>n.order||0))+1;}
function insertion(){const frame=activeFrame(),center=renderer.world({x:renderer.width/2,y:renderer.height/2});if(frame){const item=renderer.scene().find(i=>i.n.id===frame.id),p=point(inverse(item?.matrix||[1,0,0,1,0,0]),center.x,center.y);return{parent:frame.id,x:clamp(p.x-100,24,Math.max(24,frame.w-250)),y:clamp(p.y-30,24,Math.max(24,frame.h-180))};}return{parent:'',x:center.x-100,y:center.y-50};}
function focusCanvas(){setTimeout(()=>$('#canvas-host').focus({preventScroll:true}),0);}
function fitAll(){const items=renderer.scene();renderer.fit(union((frames().length?items.filter(i=>i.n.type==='frame'):items).map(i=>i.bounds)),Math.min(70,renderer.width*.07));}
function renderTools(){const tools=[['select','select','Select','V'],['hand','hand','Pan','H'],['divider'],['frame','frame','Screen','F'],['rect','rectangle','Rectangle','R'],['ellipse','ellipse','Ellipse','O'],['line','line','Line','L'],['pen','pen','Freehand','P'],['text','text','Text','T'],['divider'],['comment','comment','Comment','C']];$('#floating-tools').innerHTML=tools.map(([tool,ic,label,key])=>tool==='divider'?'<i></i>':`<button data-tool="${tool}" title="${label} · ${key}" aria-label="${label}" class="${editor.tool===tool?'active':''}">${icon(ic)}</button>`).join('')+'<i></i><button data-cmd="vector-pen" title="Bézier pen · Shift+P" aria-label="Bézier pen">⌁</button><button data-cmd="vector-edit" title="Edit vector points" aria-label="Edit vector points">◇</button>';}
function updateHeader(){const p=store.get('project');$('#project-name').textContent=p?.name||'Untitled project';document.title=(p?.name||'Untitled project')+' · Mireva Studio';$('#screen-count').textContent=frames().length+' screen'+(frames().length===1?'':'s');$('#canvas-description').textContent=(p?.device||'mobile')[0].toUpperCase()+(p?.device||'mobile').slice(1)+' app';$('#empty-canvas').hidden=store.all().length>0;$$('[data-cmd="undo"]').forEach(e=>e.disabled=!store.undoStack.length||!canComment());$$('[data-cmd="redo"]').forEach(e=>e.disabled=!store.redoStack.length||!canComment());}
function setPanel(name){if(panel===name&&matchMedia('(max-width:820px)').matches&&document.body.classList.contains('show-library'))document.body.classList.remove('show-library');else{panel=name;search='';renderPanel();document.body.classList.add('show-library');}$$('[data-panel]').forEach(el=>el.classList.toggle('active',el.dataset.panel===panel));}
function panelHeader(title,subtitle=''){return `<div class="panel-head"><h2>${title}</h2><button class="icon-button panel-close-mobile" data-cmd="close-library" aria-label="Close library">${icon('close',15)}</button>${subtitle}</div>`;}
function searchBox(placeholder){return `<div class="library-search">${icon('search')}<input id="library-search" type="search" placeholder="${placeholder}" value="${esc(search)}" aria-label="${placeholder}"></div>`;}
function mini(kind){const m={button:'<b class="mini-button">Get started</b>',input:'<div class="mini-input">Your email address</div>',badge:'<span class="mini-badge">New release</span>',card:'<div class="mini-card"></div>',text:'<b style="font-size:20px;font-weight:500;color:#b4a2c7">Aa</b>',toggle:'<span class="mini-toggle"></span>',avatar:`<div class="avatar" style="width:31px;height:31px;background:#e5daf2">${icon('user',16)}</div>`,navigation:`<div class="mini-nav">${icon('home')}${icon('grid')}${icon('user')}</div>`,chart:'<div class="mini-chart"><i style="height:17px"></i><i style="height:26px"></i><i style="height:36px"></i><i style="height:21px"></i><i style="height:29px"></i></div>',checkbox:`<span style="display:flex;align-items:center;gap:5px;color:#a991c5">${icon('checkSquare',13)}<i style="width:28px;height:3px;background:#ddcfe9"></i></span>`,modal:'<div class="mini-card" style="background:white;height:51px;width:65px"></div>'};return m[kind]||m.card;}
const COMPONENTS=[['button','Primary button','basic'],['input','Text field','basic'],['card','Feature card','cards'],['badge','Badge / label','basic'],['toggle','Toggle switch','forms'],['checkbox','Checkbox','forms'],['navigation','Navigation bar','navigation'],['avatar','Avatar','basic'],['chart','Activity chart','cards'],['modal','Confirmation','cards']];
function renderPanel(){const library=$('#library'),active=document.activeElement,retain=active?.id==='library-search',caret=active?.selectionStart;let html='';
 if(panel==='components'){
  const saved=store.all().filter(n=>n.component&&!n.componentId);const list=COMPONENTS.filter(([kind,label,cat])=>(category==='all'||cat===category)&&(!search||label.toLowerCase().includes(search.toLowerCase())));
  html=panelHeader('Elements')+searchBox('Search elements')+`<div class="panel-tabs"><button data-component-tab="all" class="${componentTab==='all'?'active':''}">Library</button><button data-component-tab="saved" class="${componentTab==='saved'?'active':''}">My components <small>${saved.length||''}</small></button></div><div class="panel-scroll">`;
  if(componentTab==='all')html+=`<div class="category-chips">${[['all','All'],['basic','Basic'],['forms','Forms'],['cards','Cards']].map(([k,v])=>`<button data-category="${k}" class="chip ${category===k?'active':''}">${v}</button>`).join('')}</div><section class="library-section"><h3>Everyday essentials <span>${list.length} elements</span></h3><div class="component-grid">${list.map(([kind,label])=>`<button class="component-card" data-component="${kind}" draggable="true" title="Insert ${label}"><div class="mini-preview">${mini(kind)}</div><span>${label}</span></button>`).join('')}</div></section><section class="library-section"><h3>Typography <span>Editable styles</span></h3><button class="text-style-card" data-text-preset="heading"><span style="font-size:23px;letter-spacing:-.7px;color:#9c8ba9">A fresh perspective.</span><small>Heading · Inter 24</small></button><button class="text-style-card" data-text-preset="body"><span style="font-size:11px;line-height:1.6;color:#a393b0">The little details make<br>all the difference.</span><small>Body · Inter 14</small></button></section><div class="library-tip">${icon('sparkle',13)} Made to make it yours.<br>Drag elements onto a screen, then edit every detail.</div>`;
  else html+=saved.length?saved.map(n=>`<button class="screen-card" data-instance="${n.id}"><span style="color:var(--accent)">${icon('component',24)}</span><div><h3>${esc(n.name)}</h3><p>Click to insert a linked instance</p></div></button>`).join(''):'<div class="info-note">Select an element or group, then choose <b>Create component</b> in the inspector. Linked instances can be updated together.</div>';
  html+='</div><div class="library-footer"><strong>Mireva essentials</strong>Small pieces. Endless possibilities.</div>';
 }
 else if(panel==='templates'){
 const templates=[['wellness','Serein · Wellness','Mindful moments, beautifully made.','#ebe5f6'],['finance','Pocket · Finance','A little clarity for your money.','#e4eaf1'],['travel','Somewhere · Travel','Make room for a new adventure.','#f4eadd'],['shop','Everyday · Store','Good things, thoughtfully selected.','#e9ede3'],['work','Daylight · Workspace','Less friction. Better teamwork.','#e9e4f2'],['food','Gather · Recipes','Fresh ideas for your table.','#f5e8df']];
 html=panelHeader('Templates')+searchBox('Find your starting point')+'<div class="panel-scroll"><div class="section-eyebrow">A little inspiration</div>'+templates.filter(t=>!search||t.join(' ').toLowerCase().includes(search.toLowerCase())).map(([kind,title,description,bg])=>`<button class="template-card" data-template="${kind}"><div class="template-art" style="background:${bg}">${[0,1,2].map(i=>'<div><i></i><b></b><i></i><i style="width:45%"></i><em></em></div>').join('')}</div><h3>${title}</h3><p>${description}</p></button>`).join('')+'</div>';
 }
 else if(panel==='shapes')html=panelHeader('Shapes')+'<div class="panel-scroll"><div class="section-eyebrow">Draw on the canvas</div><div class="component-grid">'+[['rect','rectangle','Rectangle'],['ellipse','ellipse','Ellipse'],['line','line','Line'],['pen','pen','Freehand path'],['frame','frame','Screen'],['text','text','Text']].map(([tool,ic,name])=>`<button class="component-card" data-tool="${tool}"><div class="mini-preview" style="color:#b09bc9">${icon(ic,30)}</div><span>${name}</span></button>`).join('')+'</div><div class="library-tip">Hold Shift to keep proportions. Use the edge or corner grips to resize. Hold Space to pan.</div><div class="modal-section"><h3>Arrange</h3><button class="button full small" data-cmd="group">'+icon('group',15)+'Group selection</button></div></div>';
 else if(panel==='text')html=panelHeader('Text')+'<div class="panel-scroll"><button class="button primary full" data-tool="text">'+icon('plus',16)+'Add text</button><div class="section-eyebrow" style="margin-top:25px">Start with a style</div>'+[['display','Display',38],['heading','Heading',24],['subheading','Subheading',18],['body','Body text',14],['label','Label',11]].map(([preset,title,size])=>`<button class="text-style-card" data-text-preset="${preset}"><span style="font-size:${Math.min(size,32)}px;${preset==='display'?'font-family:Georgia':''}">${title}</span><small>${preset==='display'?'Georgia':'Inter'} · ${size} px</small></button>`).join('')+'<div class="library-tip">Double-click any text element to edit directly on the canvas.</div></div>';
 else if(panel==='icons')html=panelHeader('Icons')+searchBox('Search icons')+`<div class="panel-scroll"><div class="section-eyebrow">A thoughtful little detail</div><div class="icon-grid">${Object.keys(ICONS).filter(k=>!search||k.includes(search.toLowerCase())).map(k=>`<button data-insert-icon="${k}" title="${k}" aria-label="Insert ${k} icon">${icon(k)}</button>`).join('')}</div></div>`;
 else if(panel==='themes')html=panelHeader('Brand & themes')+'<div class="panel-scroll"><div class="section-eyebrow">Set the mood</div>'+THEMES.map((t,i)=>`<div class="theme-card"><button data-theme="${i}"><h3>${t.name} ${activeTheme().name===t.name?'✓':''}</h3><div class="theme-colors">${[t.primary,t.secondary,t.ink,t.paper,t.muted].map(c=>`<i style="background:${c}"></i>`).join('')}</div><small>Apply across this project</small></button></div>`).join('')+'<div class="modal-section"><h3>Project colors</h3><div class="swatch-row" style="flex-wrap:wrap">'+[...new Set(store.all().map(n=>n.fill).filter(c=>c&&c!=='transparent'))].slice(0,24).map(c=>`<button data-swatch="${c}" style="background:${c}" title="${c}"></button>`).join('')+'</div><button class="button small full" data-cmd="extract-palette" style="margin-top:17px">'+icon('image',15)+'Extract palette from image</button></div></div>';
 else if(panel==='media'){
  const assets=[...new Map(store.all().filter(n=>n.type==='image'&&n.src).map(n=>[n.src,n])).values()];html=panelHeader('Images & assets')+'<div class="panel-scroll"><button class="media-drop" data-cmd="import-image">'+icon('upload')+'<strong>Upload an image</strong>PNG, JPEG, WebP or GIF<br>Or drop a file onto the canvas</button><h3 style="margin-bottom:14px">In this project</h3><div class="asset-grid">'+assets.map(n=>`<button data-reuse-image="${n.id}" title="${esc(n.name)}"><img src="${n.src}" alt="${esc(n.name)}"></button>`).join('')+'</div>'+(!assets.length?'<p class="info-note">Your uploaded images appear here. Images are embedded in your project, so they travel with your design.</p>':'')+'<div class="modal-section"><h3>From inspiration to interface</h3><button class="button full" data-cmd="scan-screenshot">'+icon('sparkle',15)+'Reconstruct a screenshot</button><p class="info-note" style="margin-top:12px">Use a configured vision model to reconstruct screenshots or sketches into editable elements. Uploads are sent only after confirmation.</p></div></div>';
 }
 else if(panel==='compose')html=panelHeader('Compose')+`<div class="panel-scroll"><div class="compose-hero"><span>${icon('sparkle',25)}</span><h3>What’s on your mind?</h3><p>A few words can be the beginning<br>of something wonderful.</p></div><textarea id="compose-prompt" class="compose-text" placeholder="A calm wellness app with guided meditations, daily sessions and soft lavender colors…">${esc(composePrompt)}</textarea><div class="device-choice">${[['mobile','phone','Mobile'],['tablet','tablet','Tablet'],['desktop','laptop','Desktop']].map(([k,ic,v])=>`<button data-device="${k}" class="${composeDevice===k?'active':''}">${icon(ic)}${v}</button>`).join('')}</div><label class="label-block">Aesthetic</label><select id="compose-theme" class="panel-select">${THEMES.map((t,i)=>`<option value="${i}" ${composeTheme===i?'selected':''}>${t.name}</option>`).join('')}</select><label class="label-block">Generation mode</label><select id="compose-method" class="panel-select"><option value="local" ${composeMethod==='local'?'selected':''}>Local layout composer · no model</option><option value="model" ${composeMethod==='model'?'selected':''}>Connected AI model</option></select><button class="button primary full" data-cmd="generate">${icon('sparkle',16)}Compose 3 screens</button><div class="library-tip">${composeMethod==='local'?'Local mode creates editable layouts from six template families and your chosen palette. It is deterministic, not an AI model.':'Connected mode requires the collaboration server with a model endpoint configured. Your prompt is sent to that provider.'}</div><div class="modal-section"><button class="button small full" data-cmd="scan-screenshot">${icon('image',15)}Start from a screenshot</button></div></div>`;
 else if(panel==='screens')html=panelHeader('Screens')+`<div class="panel-scroll">${frames().map(n=>`<button class="screen-card ${editor.selection.has(n.id)?'selected':''}" data-focus-frame="${n.id}"><div class="screen-thumb">${svgExport(store,[n.id])}</div><div><h3>${esc(n.name)}</h3><p>${n.w} × ${n.h} ${store.get('project')?.startFrame===n.id?'· Start screen':''}</p></div></button>`).join('')}<button class="button full" data-cmd="new-screen">${icon('plus',16)}Add a screen</button></div>`;
 else if(panel==='layers'){html=panelHeader('Layers')+searchBox('Find a layer')+`<div class="panel-tabs"><button class="active">Layers</button><button data-panel="screens">Screens</button></div><div id="layer-viewport" class="layer-viewport" role="tree" aria-label="Document layers"><div id="layer-spacer" style="position:relative"><div id="layer-window" style="position:absolute;left:0;right:0;top:0"></div></div></div><div class="layer-count">${store.all().length} elements · drag to reorder</div>`;}
 else if(panel==='comments'){
  const comments=store.all('comment'),threads=comments.filter(c=>!c.thread&&(showResolved||!c.resolved)).sort((a,b)=>b.createdAt-a.createdAt);html=panelHeader('Comments')+`<div class="panel-tabs"><button data-comments-filter="open" class="${!showResolved?'active':''}">Open</button><button data-comments-filter="all" class="${showResolved?'active':''}">All comments</button></div><div class="panel-scroll"><button class="button full small" data-tool="comment" ${canComment()?'':'disabled'}>${icon('plus',15)}Pin a comment</button><div style="height:17px"></div>${threads.map(c=>`<article class="comment-thread ${c.resolved?'resolved':''}" id="comment-${c.id}"><div class="comment-meta"><span class="avatar">${esc(c.author?.[0]||'D')}</span><div><b>${esc(c.author||'Designer')}</b><time>${new Date(c.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></div></div><p class="comment-body">${esc(c.text)}</p>${comments.filter(r=>r.thread===c.id).sort((a,b)=>a.createdAt-b.createdAt).map(r=>`<div class="reply"><b>${esc(r.author)}</b><p>${esc(r.text)}</p></div>`).join('')}<div class="comment-actions"><button data-focus-comment="${c.id}">Go to pin</button>${canComment()?`<button data-resolve-comment="${c.id}">${c.resolved?'Reopen':'Resolve'}</button>`:''}</div>${canComment()?`<textarea id="reply-${c.id}" placeholder="Add a reply…" aria-label="Reply to comment"></textarea><button class="button small" data-reply="${c.id}" style="margin-top:7px">Reply</button>`:''}</article>`).join('')}${!threads.length?'<div class="empty-properties" style="padding:20px 0"><div class="empty-icon">'+icon('comment')+'</div><h3>A space for good feedback.</h3><p>Pin a comment to a screen.<br>Replies stay with the design.</p></div>':''}</div>`;
 }
 library.innerHTML=html;if(retain){const el=$('#library-search');el?.focus();try{el?.setSelectionRange(caret,caret);}catch{}}
 if(panel==='layers')renderLayers();
}
function renderLayers(){const viewport=$('#layer-viewport');if(!viewport)return;layerRows=[];const seen=new Set();const walk=(parent,depth)=>{for(const n of [...store.children(parent)].reverse()){if(seen.has(n.id))continue;seen.add(n.id);const children=store.children(n.id);if(!search||n.name.toLowerCase().includes(search.toLowerCase()))layerRows.push({n,depth,children:children.length});if(!collapsed.has(n.id)||search)walk(n.id,depth+1);}};walk('',0);$('#layer-spacer').style.height=layerRows.length*30+'px';viewport.scrollTop=layerScroll;const render=()=>{layerScroll=viewport.scrollTop;const start=Math.max(0,Math.floor(layerScroll/30)-8),count=Math.ceil(viewport.clientHeight/30)+20;$('#layer-window').style.top=start*30+'px';$('#layer-window').innerHTML=layerRows.slice(start,start+count).map(({n,depth,children})=>`<div class="layer-row ${editor.selection.has(n.id)?'selected':''} ${n.hidden?'hidden-node':''}" data-layer="${n.id}" role="treeitem" aria-selected="${editor.selection.has(n.id)}" style="padding-left:${8+depth*13}px" draggable="true"><button data-collapse="${n.id}" aria-label="Expand or collapse">${children?icon(collapsed.has(n.id)?'chevron':'down',11):''}</button>${icon(n.component?'component':n.type==='frame'?'phone':n.type==='group'?'folder':n.type==='rect'?'rectangle':n.type==='text'?'text':n.type==='image'?'image':n.type==='ellipse'?'ellipse':n.type==='hotspot'?'link':'rectangle',13)}<span class="layer-name">${esc(n.name)}</span><button class="layer-action" data-visibility="${n.id}" title="${n.hidden?'Show':'Hide'}">${icon(n.hidden?'hidden':'eye',11)}</button><button class="layer-action" data-lock="${n.id}" title="${n.locked?'Unlock':'Lock'}">${icon(n.locked?'lock':'unlock',11)}</button></div>`).join('');};viewport.onscroll=render;render();}
function field(label,prop,value,type='number',full=false){return `<label class="field ${full?'full':''}"><span>${label}</span><input data-prop="${prop}" type="${type}" value="${esc(value??'')}" aria-label="${prop}" ${type==='number'?'step="any"':''} ${canEdit()?'':'disabled'}></label>`;}
function selectField(prop,value,options){return `<select data-prop="${prop}" aria-label="${prop}" ${canEdit()?'':'disabled'}>${options.map(o=>{const[v,t]=Array.isArray(o)?o:[o,o];return`<option value="${v}" ${v===value?'selected':''}>${t}</option>`;}).join('')}</select>`;}
function colorField(prop,color){const normalized=/^#[a-f0-9]{6}$/i.test(color||'')?color:'#ffffff';return `<div class="color-field"><input type="color" data-prop="${prop}" value="${normalized}" aria-label="${prop} color" ${canEdit()?'':'disabled'}><input type="text" data-prop="${prop}" value="${esc(color||'transparent')}" aria-label="${prop} hex code" ${canEdit()?'':'disabled'}><span>100%</span></div>`;}
function renderInspector(){renderInspectorBase();if(!editor||!canEdit())return;const ns=selected();if(ns.length&&ns.every(n=>['rect','ellipse','line','path'].includes(n.type))){const el=document.createElement('section');el.className='inspector-section vector-inspector';el.innerHTML='<h3>Vector geometry</h3><div class="vector-operations">'+(ns.length===1?'<button data-cmd="vector-edit">Edit anchor points</button>':[['union','Union'],['intersection','Intersect'],['difference','Subtract'],['xor','Exclude']].map(([k,v])=>'<button data-cmd="boolean-'+k+'">'+v+'</button>').join(''))+'</div><p class="muted">Bézier handles · Boolean tolerance 0.25 px. Source operands stay in Layers, hidden and undoable.</p>';$('#inspector').append(el);}}
function renderInspectorBase(){
 const ns=selected(),n=ns[0],root=$('#inspector');let html='';
 if(!canEdit())html+='<div class="read-only-banner">'+(sync.role==='commenter'?'Comment access · select elements and leave feedback.':'View access · editing is disabled.')+'</div>';
 if(mode==='handoff'){
  html+=`<div class="inspector-header">${icon('code')}<h3>Developer handoff</h3></div><div class="inspector-section"><h3>${n?esc(n.name):'Select an element'}</h3><p class="info-note">Inspect dimensions and styles. Export an interactive, dependency-free HTML prototype.</p></div>`;
  if(n)html+=`<div class="inspector-section"><h3>CSS <button class="section-action" data-cmd="copy-css">Copy</button></h3><pre class="code-block">${esc(nodeCSS(n).split(';').filter(Boolean).map(s=>s+';').join('\n'))}</pre></div>`;
  html+=`<div class="inspector-section"><h3>Project colors</h3><div class="swatch-row" style="flex-wrap:wrap">${[...new Set(store.all().flatMap(n=>[n.fill,n.color]).filter(c=>c&&c!=='transparent'))].slice(0,20).map(c=>`<button data-swatch="${c}" title="${c}" style="background:${c}"></button>`).join('')}</div></div><div class="inspector-footer"><button class="button primary full" data-cmd="export-html">${icon('code',15)}Export HTML prototype</button><p class="info-note" style="margin-top:13px">Handoff uses absolute positioning. It preserves the designed screen sizes; it is not a responsive application generator.</p></div>`;root.innerHTML=html;return;
 }
 if(!n){
 html+=`<div class="inspector-header">${icon(mode==='prototype'?'link':'settings')}<h3>${mode==='prototype'?'Interaction design':'Design properties'}</h3><span>⌘</span></div><div class="empty-properties"><div class="empty-icon">${icon('select')}</div><h3>Every detail, considered.</h3><p>Select an element to make it yours.<br>Position, style, and connect your ideas.</p></div><div class="inspector-section"><h3>Project theme <button class="section-action" data-panel="themes">Edit</button></h3><div class="swatch-row">${Object.values(activeTheme()).filter(c=>c.startsWith('#')).map(c=>`<span class="swatch" style="background:${c}"></span>`).join('')}</div><p class="info-note" style="margin-top:12px">${activeTheme().name}</p></div><div class="inspector-section"><h3>Screens <button class="section-action" data-cmd="new-screen">＋</button></h3>${frames().map(f=>`<button class="row-between" style="width:100%" data-focus-frame="${f.id}"><span>${esc(f.name)}</span>${icon('chevron',13)}</button>`).join('')}</div><div class="inspector-section"><h3>Canvas</h3><label class="row-between">Smart snapping<input type="checkbox" id="snap-setting" ${editor.snap?'checked':''}></label><label class="row-between">Snap to 8 px grid<input type="checkbox" id="grid-setting" ${editor.grid?'checked':''}></label></div><div class="inspector-footer"><button class="button full small" data-cmd="preview">${icon('play',14)}Play your prototype</button></div>`;root.innerHTML=html;return;
 }
 const kind=ns.length>1?`${ns.length} elements`:n.type==='frame'?'Screen':n.type==='rect'?'Rectangle':n.type[0].toUpperCase()+n.type.slice(1);
 html+=`<div class="inspector-header">${icon(n.component?'component':n.type==='frame'?'phone':n.type==='text'?'text':'rectangle')}<h3>${kind}</h3><button class="icon-button" data-cmd="selection-menu" aria-label="Selection menu">${icon('more',16)}</button></div>`;
 if(mode==='prototype'){
 html+=`<div class="inspector-section"><h3>Interaction</h3><p class="info-note" style="margin-bottom:17px">Make this element part of the story.</p><label class="label-block">Action</label>${selectField('action',n.action||'',[['','None'],['navigate','Navigate to screen'],['overlay','Open overlay'],['back','Go back'],['close','Close overlay'],['url','Open link'],['toggle','Toggle play / pause']])}${['navigate','overlay'].includes(n.action)?`<label class="label-block">Destination screen</label>${selectField('target',n.target||'',[['','Choose a screen'],...frames().map(f=>[f.id,esc(f.name)])])}`:''}${n.action==='url'?`<label class="label-block">Destination URL</label>${field('↗','url',n.url||'https://','text',true)}`:''}<label class="label-block">Trigger</label>${selectField('trigger',n.trigger||'click',[['click','On click / tap'],['hover','On hover'],['delay','After delay']])}<label class="label-block">Transition</label>${selectField('transition',n.transition||'fade',[['fade','Dissolve'],['slide','Slide in'],['none','Instant']])}<div class="property-grid" style="margin-top:15px">${field('ms','duration',n.duration??250)}${field('wait','delay',n.delay??1000)}</div></div>`;
 if(n.type==='frame')html+=`<div class="inspector-section"><h3>Flow starting point</h3><button class="button full" data-cmd="set-start">${icon('home',15)}${store.get('project')?.startFrame===n.id?'Start screen ✓':'Set as start screen'}</button></div>`;
 html+=`<div class="inspector-section"><h3>Try the flow</h3><button class="button primary full" data-cmd="preview">${icon('play',15)}Preview interaction</button><p class="info-note" style="margin-top:12px">Connections are shown on the canvas. A transparent hotspot can make any region clickable.</p><button class="button full small" data-cmd="add-hotspot" style="margin-top:13px">${icon('link',14)}Add a hotspot</button></div>`;root.innerHTML=html;root.querySelectorAll('select').forEach(s=>s.style.width='100%');return;
 }
 html+=`<div class="inspector-section"><h3>Layout <button class="section-action" data-cmd="fit-selection">${icon('fit',13)}</button></h3><div class="align-toolbar">${[['left','alignleft'],['center','aligncenter'],['right','alignright'],['top','aligntop'],['middle','alignmiddle'],['bottom','alignbottom']].map(([k,ic])=>`<button data-align="${k}" title="Align ${k}" aria-label="Align ${k}">${icon(ic)}</button>`).join('')}</div><div class="property-grid">${field('X','x',Math.round(n.x*10)/10)}${field('Y','y',Math.round(n.y*10)/10)}${field('W','w',Math.round(n.w*10)/10)}${field('H','h',Math.round(n.h*10)/10)}${field('↻','rotation',Math.round(n.rotation||0))}${field('⌜','radius',n.radius||0)}</div></div>`;
 if(ns.length===1)html+=`<div class="inspector-section" style="padding-top:13px;padding-bottom:13px"><div class="property-grid">${field('Name','name',n.name,'text',true)}</div></div>`;
 if(['text','button','input'].includes(n.type))html+=`<div class="inspector-section"><h3>Typography</h3><div class="field" style="margin-bottom:9px">${selectField('fontFamily',n.fontFamily||'Inter',['Inter','Georgia','Arial','Verdana','monospace'])}</div><div class="property-grid">${field('Size','fontSize',n.fontSize)}<label class="field">${selectField('fontWeight',String(n.fontWeight||400),[['400','Regular'],['500','Medium'],['600','Semibold'],['700','Bold'],['800','Extra bold']])}</label>${field('Line','lineHeight',n.lineHeight||1.35)}${field('↔','letterSpacing',n.letterSpacing||0)}</div><div class="font-options"><button data-toggle-prop="italic" class="${n.italic?'active':''}" title="Italic"><i>I</i></button><button data-toggle-prop="underline" class="${n.underline?'active':''}" title="Underline"><u>U</u></button><button data-text-align="left" class="${n.align==='left'?'active':''}" title="Align text left">${icon('alignleft',14)}</button><button data-text-align="center" class="${n.align==='center'?'active':''}" title="Center text">${icon('aligncenter',14)}</button><button data-text-align="right" class="${n.align==='right'?'active':''}" title="Align text right">${icon('alignright',14)}</button></div><label class="label-block">Content</label><textarea data-prop="text" aria-label="Text content" ${canEdit()?'':'disabled'}>${esc(n.text)}</textarea><label class="label-block">Text color</label>${colorField('color',n.color)}</div>`;
 if(!['text','icon','group'].includes(n.type))html+=`<div class="inspector-section"><h3>Fill <button class="section-action" data-cmd="transparent-fill">${icon('minus',13)}</button></h3>${colorField('fill',n.fill)}<div class="row-between"><span>Style</span>${selectField('gradient',n.gradient||'none',[['none','Solid'],['vertical','Vertical gradient'],['horizontal','Horizontal gradient']])}</div>${n.gradient&&n.gradient!=='none'?colorField('fill2',n.fill2):''}<div class="property-grid">${field('%','opacity',Math.round((n.opacity??1)*100),'number',true)}</div></div>`;
 if(n.type==='icon')html+=`<div class="inspector-section"><h3>Icon color</h3>${colorField('color',n.color)}<button class="button full small" data-panel="icons">Browse icons</button></div>`;
 html+=`<div class="inspector-section"><h3>Border</h3>${colorField('stroke',n.stroke)}<div class="property-grid">${field('px','strokeWidth',n.strokeWidth||0,'number',true)}</div></div>`;
 if(n.type==='path')html+=`<div class="inspector-section"><h3>Vector path</h3><textarea data-prop="path" aria-label="SVG path data">${esc(n.path)}</textarea><p class="info-note" style="margin-top:8px">Editable SVG path commands in local coordinates.</p></div>`;
 if(n.type==='group'||n.type==='frame')html+=`<div class="inspector-section"><h3>Auto layout</h3><div class="row-between"><span>Direction</span>${selectField('layout',n.layout||'none',[['none','Free position'],['row','Horizontal'],['column','Vertical']])}</div><div class="property-grid">${field('Gap','gap',n.gap??16)}${field('Pad','padding',n.padding??16)}</div><div class="row-between" style="margin-top:12px"><span>Alignment</span>${selectField('layoutAlign',n.layoutAlign||'start',[['start','Start'],['center','Center'],['stretch','Stretch']])}</div><label class="row-between" style="margin-top:15px">Clip content<input data-prop="clip" type="checkbox" ${n.clip?'checked':''}></label></div>`;
 if(n.parent)html+=`<div class="inspector-section"><h3>Responsive constraints</h3><div class="row-between"><span>Horizontal</span>${selectField('constraintX',n.constraintX||'left',[['left','Left'],['center','Center'],['right','Right'],['stretch','Left + right'],['scale','Scale']])}</div><div class="row-between"><span>Vertical</span>${selectField('constraintY',n.constraintY||'top',[['top','Top'],['center','Center'],['bottom','Bottom'],['stretch','Top + bottom'],['scale','Scale']])}</div></div>`;
 html+=`<div class="inspector-section"><h3>Effects & visibility</h3><label class="row-between">Drop shadow<input type="checkbox" data-prop="shadow" ${n.shadow?'checked':''}></label><label class="row-between">Locked<input type="checkbox" data-prop="locked" ${n.locked?'checked':''}></label><label class="row-between">Hidden<input type="checkbox" data-prop="hidden" ${n.hidden?'checked':''}></label></div>`;
 html+=`<div class="inspector-footer">${n.component?`<button class="button secondary full small" data-cmd="update-instances">${icon('component',14)}Update linked instances</button>`:n.componentId?`<button class="button full small" data-cmd="detach-instance">Detach instance</button>`:`<button class="button full small" data-cmd="make-component">${icon('component',14)}Create component</button>`}<button class="button full small" data-cmd="export" style="margin-top:9px">${icon('download',14)}Export selection</button></div>`;
 root.innerHTML=html;
}
function editSelection(values,label='Edit properties'){
 if(!canEdit())throw Error('Your invitation cannot edit the design');store.transact(label,()=>{for(const n of selected()){if(n.locked&&values.locked!==false)continue;const oldW=n.w,oldH=n.h;store.set(n.id,values);if(['frame','group'].includes(n.type)&&(values.w||values.h))resizeChildren(store,n.id,oldW,oldH,values.w||oldW,values.h||oldH,n.type==='group');if(['layout','gap','padding','layoutAlign','w','h'].some(k=>k in values))reflow(store,n.id);const masters=store.all().filter(m=>m.component&&(m.id===n.id||store.isAncestor(m.id,n.id)));for(const m of masters)syncInstances(store,m.id);}});
}
function setMode(next){mode=next;editor.prototypeMode=mode==='prototype';$$('[data-mode]').forEach(e=>e.classList.toggle('active',e.dataset.mode===mode));renderInspector();renderer.invalidate();}
function updatePresence(peers){editor.peers=peers;renderer.invalidate();const users=[{name:identity.name,color:identity.color},...peers.values()];$('#presence-cluster').innerHTML=users.slice(0,4).map(p=>`<span class="avatar" style="background:${p.color}25;color:${p.color}" title="${esc(p.name)}">${esc(p.name[0].toUpperCase())}</span>`).join('')+(users.length>4?`<span class="avatar">+${users.length-4}</span>`:'');}
function updateConnection(status,role){const text={local:'Local workspace',connecting:'Connecting…',online:role==='owner'||role==='editor'?'Live collaboration':role==='commenter'?'Live · commenter':'Live · view only',offline:'Offline · changes queued',blocked:'Sync blocked · saved locally',revoked:'Invitation revoked'}[status]||status;$('#connection-status').textContent=text;$('#connection-status').title=sync?.config?`${sync.config.server} · ${sync.queue.length} pending operations`:text;if(editor){renderInspector();updateHeader();}}
async function saveNow(){if(initializing)return;const id=documentId,snapshot=store.snapshot(),extras={outbox:clone(sync?.queue||[]),collaboration:sync?.config?{id:sync.config.id,server:sync.config.server}:null,camera:renderer?{...renderer.camera}:null};saveChain=saveChain.catch(()=>{}).then(()=>vault.save(id,snapshot,extras));try{await saveChain;saveError=false;$('#save-state').innerHTML='<i></i> '+(sync?.status==='online'&&!sync.queue.length?'Saved & synced':'Saved to this device');}catch(e){saveError=true;$('#save-state').textContent='Not saved · storage unavailable';toast('Local save failed. Export your project now. '+e.message,true);}}
function scheduleSave(){clearTimeout(saveTimer);$('#save-state').textContent='Saving…';saveTimer=setTimeout(saveNow,200);}
function onStoreChange(event){if(initializing)return;updateHeader();scheduleSave();clearTimeout(renderTimer);renderTimer=setTimeout(()=>{if(!editingText&&!document.activeElement?.matches('[data-prop]'))renderInspector();if(['layers','screens','comments','media'].includes(panel))renderPanel();},110);}
function showDialog(title,body,{wide=false}={}){const d=$('#modal');d.classList.toggle('wide',wide);$('#modal-content').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-cmd="close-dialog" aria-label="Close dialog">${icon('close',18)}</button></div><div class="modal-body">${body}</div>`;if(!d.open)d.showModal();icons(d);}
function closeDialog(){if(askResolve){askResolve(null);askResolve=null;}$('#modal').close();focusCanvas();}
function ask(title,label,value='',{multiline=false,button='Save'}={}){return new Promise(resolve=>{askResolve=resolve;showDialog(title,`<form id="ask-form" class="modal-form"><label>${esc(label)}${multiline?`<textarea id="ask-value" rows="4" required>${esc(value)}</textarea>`:`<input id="ask-value" value="${esc(value)}" required autocomplete="off">`}</label><div class="modal-actions"><button type="button" class="button" data-cmd="close-dialog">Cancel</button><button type="submit" class="button primary">${button}</button></div></form>`);setTimeout(()=>{$('#ask-value').focus();$('#ask-value').select();},30);});}
function openText(id){finishText();if(!canEdit())return;editingText=new RichTextEditor(store,renderer,id,{onClose:()=>{editingText=null;renderInspector();renderer.invalidate();},onPresence:text=>sync?.presence({...sync.lastPresenceData,...identity,text}),onError:message=>toast(message,true)});}
function finishText(){const active=editingText;if(active){editingText=null;active.close();}}

async function openProjects(){await saveNow();projectList=(await vault.list()).sort((a,b)=>b.updatedAt-a.updatedAt);showDialog('Your creative workspace',`<p class="modal-description">A home for your next big idea. Projects are saved on this device. Shared rooms also sync with your collaboration server.</p><div class="dashboard-actions"><button class="button primary" data-cmd="new-project">${icon('plus',15)}New project</button><button class="button" data-cmd="import">${icon('upload',15)}Import project</button></div><div class="project-grid"><button class="new-project-card" data-cmd="new-project">${icon('plus')}<span>Something new starts here</span></button>${projectList.map(p=>{let cover='';try{const temp=new DocumentStore();temp.load(p.snapshot);const fs=temp.children('').filter(n=>n.type==='frame');cover=fs.length?svgExport(temp,fs.slice(0,3).map(n=>n.id)):'';}catch{}return `<article class="project-card"><div class="project-cover" data-open-project="${p.id}">${cover||icon('frame',32)}</div><div class="project-card-info"><h3>${esc(p.name)}</h3><p>${p.collaboration?'Shared workspace':'Local project'} · ${new Date(p.updatedAt).toLocaleDateString()}</p><div class="project-card-actions"><button data-open-project="${p.id}">Open</button><button data-duplicate-project="${p.id}">Duplicate</button><button data-delete-project="${p.id}" class="delete-project">${icon('trash',13)}</button></div></div></article>`;}).join('')}</div>`,{wide:true});}
async function openProject(id){const p=await vault.get(id);if(!p)throw Error('Project not found');await saveNow();sync.disconnect();sessionStorage.removeItem('mireva-room');documentId=id;store.load(p.snapshot);await vault.setting('lastDocument',id);editor.select([]);closeDialog();if(p.camera){renderer.camera=p.camera;renderer.invalidate();}else fitAll();if(p.collaboration)toast('Opened the locally saved copy. Use its invitation link to reconnect.');renderPanel();renderInspector();}
async function newProject(){const name=await ask('Make something wonderful','Project name','Untitled project',{button:'Create project'});if(!name)return;await saveNow();sync.disconnect();sessionStorage.removeItem('mireva-room');store.records.clear();store.clock=0;store.undoStack=[];store.redoStack=[];documentId=uid('doc');store.transact('Create project',()=>store.add({entity:'project',name,theme:THEMES[0].name,device:'mobile',deleted:false},'project'));await vault.setting('lastDocument',documentId);editor.select([]);renderer.sceneDirty=true;fitAll();setPanel('templates');renderInspector();await saveNow();}

function screenDialog(){showDialog('A screen for your idea',`<p class="modal-description">Choose a starting size. You can change the dimensions and responsive constraints in the inspector.</p><div class="export-grid">${[['mobile','phone','Mobile','360 × 744'],['tablet','tablet','Tablet','834 × 1112'],['desktop','laptop','Desktop','1440 × 900'],['custom','frame','Custom canvas','Your dimensions']].map(([preset,ic,title,sub])=>`<button class="export-card" data-preset="${preset}">${icon(ic)}<strong>${title}</strong><span>${sub}</span></button>`).join('')}</div>`);}
async function addScreen(preset){if(!canEdit())throw Error('Editing permission is required');let w,h;if(preset==='custom'){const result=await ask('Custom screen','Width × height in pixels','1200 × 800',{button:'Create screen'});if(!result)return;const values=result.split(/[x×, ]+/).map(Number).filter(Boolean);if(values.length!==2||values.some(v=>!Number.isFinite(v)||v<10||v>20000))throw Error('Enter a width and height between 10 and 20,000');[w,h]=values;}let id;store.transact('Add screen',()=>{id=blankFrame(store,preset==='custom'?'desktop':preset,frames().length?rightEdge():0,0);if(w&&h)store.set(id,{w,h,name:'Custom screen'});if(!store.get('project')?.startFrame)store.set('project',{startFrame:id});});closeDialog();editor.select([id]);fitAll();renderPanel();}
async function importFile(file,purpose='normal'){
 if(!file)return;if(!canEdit())throw Error('Editing permission is required');
 if(purpose==='scan'||purpose==='palette'){scanImage=await readImage(file);if(purpose==='palette'){const palette=await extractPalette(scanImage.src);showDialog('Colors, found in your image',`<p class="modal-description">Dominant colors extracted locally in a worker. Nothing was uploaded.</p><img class="scan-image" src="${scanImage.src}" alt="Palette source"><div class="swatch-row" style="justify-content:center;gap:13px;flex-wrap:wrap">${palette.map(p=>`<button data-swatch="${p.color}" style="width:39px;height:39px;background:${p.color}" title="${p.color}"></button>`).join('')}</div><p class="info-note" style="text-align:center;margin-top:16px">Select an element, then click a color to apply it.</p>`);return;}showScan();return;}
 if(file.name.toLowerCase().endsWith('.sketch')){const design=await decodeSketch(await file.arrayBuffer());const roots=applyGenerated(store,design,frames().length?rightEdge():0);editor.select(roots);fitAll();toast(design.warnings.length?'Imported with conversion notes: '+design.warnings.join('; '):'Design archive imported',!!design.warnings.length);return;}
 if(file.name.toLowerCase().endsWith('.mireva.zip')){const snapshot=await decodePackage(await file.arrayBuffer());await saveNow();sync.disconnect();sessionStorage.removeItem('mireva-room');documentId=uid('doc');store.load(snapshot);editor.select([]);fitAll();await saveNow();toast('Portable package imported');return;}
 if(file.name.toLowerCase().endsWith('.fig'))throw Error('Binary project files are not a documented interchange format. Import the public REST JSON with geometry=paths, or export editable SVG.');
 if(file.name.toLowerCase().endsWith('.mireva')||file.name.toLowerCase().endsWith('.json')){
  if(file.size>40_000_000)throw Error('Project file is too large');const snapshot=JSON.parse(await file.text());if(snapshot.format!=='mireva-studio'){const design=decodeFigma(snapshot),roots=applyGenerated(store,design,frames().length?rightEdge():0);editor.select(roots);fitAll();toast(design.warnings.length?'Converted with notes: '+design.warnings.join('; '):'Editable layers imported',!!design.warnings.length);return;}validateSnapshot(snapshot);await saveNow();sync.disconnect();sessionStorage.removeItem('mireva-room');documentId=uid('doc');store.load(snapshot);await vault.setting('lastDocument',documentId);editor.select([]);fitAll();renderPanel();await saveNow();toast('Project imported');return;
 }
 if(file.type==='image/svg+xml'||file.name.toLowerCase().endsWith('.svg')){const{root,warnings}=importSVG(store,await file.text(),{x:frames().length?rightEdge():0});editor.select([root]);editor.fitSelection();toast(warnings.length?'SVG imported. Unsupported features: '+warnings.join(', '):'SVG imported as editable elements',warnings.length>0);return;}
 const img=await readImage(file),pos=insertion(),scale=Math.min(1,320/img.w);let id;store.transact('Import image',()=>id=store.add(node('image',{...pos,w:img.w*scale,h:img.h*scale,src:img.src,name:file.name,fill:'transparent',radius:10,order:nextOrder(pos.parent)})));editor.select([id]);toast('Image embedded in your project');
}
function chooseFile(purpose='normal'){importPurpose=purpose;$('#file-input').accept=purpose==='scan'||purpose==='palette'||purpose==='image'?'image/png,image/jpeg,image/webp,image/gif':'.mireva,.mireva.zip,.sketch,.json,.svg,image/png,image/jpeg,image/webp,image/gif';$('#file-input').value='';$('#file-input').click();}
function addComponent(kind){if(!canEdit())throw Error('Editing permission is required');const pos=insertion();let id;store.transact('Insert component',()=>{id=insertComponent(store,kind,pos.parent,pos.x,pos.y,activeTheme());store.set(id,{order:nextOrder(pos.parent)});});editor.select([id]);editor.setTool('select');focusCanvas();}
function addText(preset){const size={display:38,heading:24,subheading:18,body:14,label:11}[preset]||24,pos=insertion();let id;store.transact('Add text',()=>id=store.add(node('text',{...pos,w:preset==='display'?310:260,h:size*2.8,text:preset==='body'?'The little details make all the difference.':preset==='label'?'A SMALL BUT IMPORTANT DETAIL':'A fresh perspective.',fontSize:size,fontFamily:preset==='display'?'Georgia':'Inter',fontWeight:preset==='heading'||preset==='subheading'?600:400,color:activeTheme().ink,fill:'transparent',order:nextOrder(pos.parent)})));editor.select([id]);focusCanvas();}
function useTemplate(kind){if(!canEdit())throw Error('Editing permission is required');let ids;if(kind==='wellness'){const temp=new DocumentStore();seedProject(temp);ids=applyGenerated(store,{nodes:temp.all().map(n=>{const{_stamps,...v}=clone(n);return v;})},frames().length?rightEdge():0);}else{const prompts={finance:'A finance budget banking mobile app',travel:'A travel booking and discovery app',shop:'A thoughtful ecommerce product store',work:'A project dashboard and team task app',food:'A recipe and food discovery app'},themes={finance:2,travel:3,shop:1,work:0,food:3};ids=composeScreens(store,prompts[kind],{device:'mobile',theme:THEMES[themes[kind]],x:frames().length?rightEdge():0});}if(!store.get('project')?.startFrame)store.set('project',{startFrame:ids[0]});editor.select(ids.filter(id=>store.get(id)?.type==='frame'));fitAll();toast('Three editable screens, ready to make your own');closeDialog();}
function applyTheme(index){const old=activeTheme(),theme=THEMES[index];store.transact('Apply '+theme.name,()=>{const keys=['primary','secondary','ink','paper','muted'];for(const n of store.all()){const v={};for(const prop of['fill','fill2','color','stroke']){const key=keys.find(k=>n[prop]?.toLowerCase()===old[k].toLowerCase());if(key)v[prop]=theme[key];}if(Object.keys(v).length)store.set(n.id,v);}store.set('project',{theme:theme.name});});renderPanel();renderInspector();toast('Applied '+theme.name);}
async function generate(){const button=$('[data-cmd="generate"]');composePrompt=$('#compose-prompt')?.value||composePrompt;if(!composePrompt.trim())throw Error('Describe the interface you want to create');busy(button,true);try{let ids;if(composeMethod==='model'){if(!sync.config)throw Error('Connect a shared room in Share before using the server model');const design=await sync.generate(composePrompt,composeDevice);ids=applyGenerated(store,design,frames().length?rightEdge():0);}else ids=composeScreens(store,composePrompt,{device:composeDevice,theme:THEMES[composeTheme],count:composeCount,x:frames().length?rightEdge():0});editor.select(ids.filter(id=>store.get(id)?.type==='frame'));fitAll();toast(composeMethod==='model'?'Generated editable screens':'Composed three editable screens with the local layout engine');}finally{busy(button,false);}}
function showScan(){showDialog('From inspiration to interface',`<p class="modal-description">Reconstruct a screenshot or hand-drawn wireframe into editable layers using your configured vision model.</p>${scanImage?`<img class="scan-image" src="${scanImage.src}" alt="Source screenshot">`:'<button class="media-drop" data-cmd="choose-scan">'+icon('upload')+'<strong>Choose a screenshot or sketch</strong>PNG, JPEG or WebP</button>'}<div class="modal-form"><label>Instructions<textarea id="scan-prompt" rows="3">Reconstruct this interface as editable layers. Preserve the layout, text, spacing, colors and visual hierarchy.</textarea></label></div><div class="notice warning" style="margin-top:17px">Clicking “Reconstruct” sends this image and your instructions to the model configured on your server. Local import alone creates one image layer, not editable extracted controls.</div><div class="modal-actions"><button class="button" data-cmd="choose-scan">Choose image</button><button class="button primary" data-cmd="reconstruct" ${scanImage?'':'disabled'}>${icon('sparkle',15)}Reconstruct</button></div>`);}
async function reconstruct(){if(!scanImage)throw Error('Choose an image first');if(!sync.config)throw Error('Connect to your collaboration server in Share. A vision model must be configured there.');const btn=$('[data-cmd="reconstruct"]');busy(btn,true);try{const design=await sync.generate($('#scan-prompt').value,'mobile',scanImage.src),ids=applyGenerated(store,design,frames().length?rightEdge():0);closeDialog();editor.select(ids);fitAll();toast('Reconstructed editable layers. Review the model output for accuracy.');}finally{busy(btn,false);}}
async function openShare(){
 const config=sync.config,status=sync.status;
 if(!config){showDialog('Good ideas grow together',`<p class="modal-description">Create a shared workspace for live editing, cursors, comments, and version history. Your collaborators connect to the same server.</p><div class="notice">Run <code>npm start</code> from the included source folder, then use its address below. Sharing is real network collaboration, not a simulated set of avatars.</div><div class="modal-form"><label>Your display name<input id="share-name" value="${esc(identity.name)}" maxlength="40"></label><label>Collaboration server<input id="share-server" type="url" value="${esc(preferences.server||(location.protocol.startsWith('http')?location.origin:'http://localhost:4173'))}" placeholder="https://your-server.example"></label><label>Server creation key · only if required<input id="share-create-key" type="password" autocomplete="off" placeholder="Leave blank for the local server"></label></div><div class="modal-actions"><button class="button" data-cmd="close-dialog">Keep designing locally</button><button class="button primary" data-cmd="create-room">${icon('share',15)}Create shared workspace</button></div>`);return;}
 let invites=[];if(sync.role==='owner'){try{invites=(await sync.invites()).invites;}catch(e){toast(e.message,true);}}
 const peerList=[...sync.peers.values()];
 showDialog('A shared space for your ideas',`<p class="modal-description">${status==='online'?'Connected to your team. Changes sync as you work.':'The connection is '+esc(status)+'. Local edits stay on this device until synchronization succeeds.'}</p><div class="notice">${esc(sync.config.server)}<br>Room ${esc(sync.config.id)} · ${esc(sync.role)} access</div>${sync.role==='owner'?`<h3 style="margin-bottom:13px">Invite someone</h3><div class="invite-row"><input id="invite-label" placeholder="Invitation label, e.g. Product team" aria-label="Invitation label"><select id="invite-role" aria-label="Invitation role"><option value="editor">Can edit</option><option value="commenter">Can comment</option><option value="viewer">Can view</option></select><button class="button primary" data-cmd="create-invite">Create link</button></div><p class="info-note" style="margin-top:9px">Links are bearer credentials, valid for 30 days. Anyone with a link gets that role; no account or email delivery is implied.</p>`:'<p class="info-note">Only the room owner can create or revoke invitation links.</p>'}${lastInvite?`<div class="link-box"><input id="invite-link" readonly value="${esc(lastInvite)}" aria-label="Invitation URL"><button class="button" data-cmd="copy-invite">${icon('copy',15)}Copy</button></div>`:''}<div class="modal-section"><h3>Here now · ${peerList.length+1}</h3><div class="member-row"><span class="avatar">${esc(identity.name[0])}</span><div>${esc(identity.name)} <small>You</small></div><span class="role-pill">${esc(sync.role)}</span></div>${peerList.map(p=>`<div class="member-row"><span class="avatar" style="background:${p.color}25;color:${p.color}">${esc(p.name[0])}</span><div>${esc(p.name)}<small>Live session</small></div><span class="role-pill">${p.role}</span></div>`).join('')}</div>${sync.role==='owner'?`<div class="modal-section"><h3>Manage access</h3>${invites.filter(i=>i.role!=='owner').map(i=>`<div class="member-row"><span>${icon(i.revoked?'lock':'link',16)}</span><div>${esc(i.label)}<small>${i.revoked?'Revoked':i.expires<Date.now()?'Expired':'Expires '+new Date(i.expires).toLocaleDateString()}</small></div><span class="role-pill">${i.role}</span>${!i.revoked?`<button data-revoke-invite="${i.id}">Revoke</button>`:''}</div>`).join('')||'<p class="info-note">No invitation links created yet.</p>'}<button class="button small" ${sync.config.account?'hidden':''} data-cmd="owner-link" style="margin-top:12px">Copy owner recovery link</button><p class="info-note" style="margin-top:9px">Keep your owner link private. Owner access is retained in this browser tab’s session; save the recovery link before closing it.</p></div>`:''}<div class="modal-actions"><button class="button" data-cmd="disconnect">Disconnect · keep local copy</button><button class="button primary" data-cmd="close-dialog">Done</button></div>`);
}
async function createRoom(){const btn=$('[data-cmd="create-room"]'),server=$('#share-server').value.trim().replace(/\/$/,'');const url=new URL(server);if(!['http:','https:'].includes(url.protocol))throw Error('Use an HTTP or HTTPS server');busy(btn,true);try{identity.name=$('#share-name').value.trim().slice(0,40)||'Designer';preferences.server=server;await saveNow();const b=await sync.create(server,store.snapshot(),$('#share-create-key').value);documentId='room_'+b.id;sessionStorage.setItem('mireva-room',JSON.stringify(sync.config));await vault.setting('lastDocument',documentId);await vault.setting('identity',identity);await vault.setting('preferences',preferences);const invite=await sync.invite('editor','Team editing');lastInvite=sync.shareLink(invite.token);await saveNow();await openShare();toast('Shared workspace created');}finally{busy(btn,false);}}
async function copyText(text,message='Copied'){try{await navigator.clipboard.writeText(text);toast(message);}catch{showDialog('Copy this text',`<p class="modal-description">Clipboard access is unavailable in this browser context. Select and copy the text below.</p><textarea style="width:100%;min-height:150px" id="manual-copy">${esc(text)}</textarea>`);$('#manual-copy').select();}}
async function createInvite(){const invite=await sync.invite($('#invite-role').value,$('#invite-label').value);lastInvite=sync.shareLink(invite.token);await openShare();toast('Invitation created');}
async function disconnect(){await saveNow();const name=store.get('project')?.name;sync.disconnect();sessionStorage.removeItem('mireva-room');documentId=uid('doc');store.set('project',{name:name+' · local copy'});await vault.setting('lastDocument',documentId);await saveNow();lastInvite='';closeDialog();toast('Disconnected. A local copy has been kept.');}
async function commentAt(world,frameId){if(!canComment())throw Error('This invitation cannot comment');const text=await ask('A thought worth sharing','Your comment','',{multiline:true,button:'Post comment'});if(!text)return;const frame=renderer.scene().find(i=>i.n.id===frameId),p=frame?point(inverse(frame.matrix),world.x,world.y):world;store.transact('Add comment',()=>store.add({entity:'comment',text,frame:frameId,x:p.x,y:p.y,author:identity.name,authorId:sync.grantId||store.actor,thread:'',resolved:false,deleted:false,createdAt:Date.now()}));setPanel('comments');editor.setTool('select');}
function reply(id){const input=$('#reply-'+id),text=input?.value.trim();if(!text)return;const parent=store.get(id);store.transact('Reply to comment',()=>store.add({entity:'comment',text,frame:parent.frame,x:parent.x,y:parent.y,author:identity.name,authorId:sync.grantId||store.actor,thread:id,resolved:false,deleted:false,createdAt:Date.now()}));renderPanel();}
async function openHistory(){localVersions=await vault.versions(documentId);sharedVersions=[];if(sync.config&&sync.status==='online'){try{sharedVersions=(await sync.versions()).versions;}catch(e){toast(e.message,true);}}showDialog('A little room to look back',`<p class="modal-description">Keep named checkpoints as your design evolves. Restoring a version creates new, undoable edits instead of rewinding the collaboration clock.</p><button class="button primary" data-cmd="checkpoint">${icon('plus',15)}Save a checkpoint</button><div class="modal-section"><h3>${sync.config?'Shared checkpoints':'Saved checkpoints'}</h3>${(sync.config?sharedVersions:localVersions).map(v=>`<div class="history-row">${icon('clock')}<div><strong>${esc(v.name)}</strong><small>${new Date(v.createdAt).toLocaleString()}</small></div><button data-restore-version="${v.id}" data-shared="${!!sync.config}">Restore</button></div>`).join('')||'<p class="info-note">No checkpoints yet. Save one before making a big change.</p>'}</div><div class="modal-section"><h3>Recent local edits</h3>${store.undoStack.slice(-12).reverse().map(e=>`<div class="history-row">${icon('undo')}<div><strong>${esc(e.label)}</strong><small>${e.changes.length} affected elements</small></div></div>`).join('')||'<p class="info-note">Your editing history starts with your first change.</p>'}</div>`);}
async function checkpoint(){const name=await ask('Keep this moment','Checkpoint name','Design review '+new Date().toLocaleDateString());if(!name)return;await saveNow();if(sync.config){if(sync.queue.length)throw Error('Wait for pending edits to sync before saving a shared checkpoint');await sync.checkpoint(name);}else await vault.checkpoint(documentId,store.snapshot(),name);await openHistory();toast('Checkpoint saved');}
async function restoreVersion(id,shared){if(!canEdit())throw Error('Editing permission is required');if(!confirm('Restore this checkpoint? This creates new edits and can be undone.'))return;const version=shared?(await sync.version(id)):localVersions.find(v=>v.id===id);if(!version)throw Error('Checkpoint not found');restoreAsEdits(store,version.snapshot);editor.select([]);closeDialog();fitAll();toast('Checkpoint restored as a new edit');}
function openExport(){showDialog('Ready for its next chapter',`<p class="modal-description">Take your work anywhere. Images and fonts used by the system remain local; uploaded images are embedded.</p><div class="invite-row" style="margin-bottom:19px"><select id="export-scope" style="flex:1;max-width:none" aria-label="Export scope"><option value="selection" ${exportScope==='selection'?'selected':''}>Selection${editor.selection.size?' · '+editor.selection.size+' elements':' · all screens when empty'}</option><option value="all" ${exportScope==='all'?'selected':''}>All screens</option><option value="screen" ${exportScope==='screen'?'selected':''}>Current screen</option></select><select id="export-scale" aria-label="PNG export scale"><option value="1" ${exportScale===1?'selected':''}>PNG 1×</option><option value="2" ${exportScale===2?'selected':''}>PNG 2×</option><option value="3" ${exportScale===3?'selected':''}>PNG 3×</option></select></div><div class="export-grid">${[['export-png','image','PNG image','High-resolution raster image.'],['export-svg','pen','SVG vector','Scalable shapes, paths, and text.'],['export-html','code','HTML prototype','Interactive screens with navigation.'],['export-json','folder','Mireva document','Complete editable project and assets.'],['export-package','folder','Portable ZIP package','Validated editable document and embedded assets.']].map(([cmd,ic,title,desc])=>`<button class="export-card" data-cmd="${cmd}">${icon(ic)}<strong>${title}</strong><span>${desc}</span></button>`).join('')}</div><p class="info-note" style="margin-top:19px">SVG and PNG use your chosen scope. Native documents and HTML prototypes include the full project. The HTML prototype does not contain collaboration credentials.</p>`);}
function exportIds(){return exportScope==='all'?[]:exportScope==='screen'?[activeFrame()?.id].filter(Boolean):[...editor.selection];}
function filename(){return(store.get('project')?.name||'Mireva design').replace(/[^\p{L}\p{N}_ -]/gu,'').trim()||'Mireva design';}
async function doExport(kind){if(kind==='json'){download(filename()+'.mireva',JSON.stringify(store.snapshot(),null,2),'application/json');toast('Editable project exported');}if(kind==='svg'){download(filename()+'.svg',svgExport(store,exportIds()),'image/svg+xml');toast('SVG exported');}if(kind==='png'){toast('Rendering PNG…');const blob=await pngExport(store,exportIds(),exportScale);download(filename()+'.png',blob);toast('PNG exported');}if(kind==='html'){download(filename()+'.html',htmlExport(store),'text/html');toast('Standalone HTML prototype exported');}}
function preview(){finishText();if(!frames().length)throw Error('Add a screen to preview your design');const start=(editor.selection.size?activeFrame()?.id:null)||store.get('project')?.startFrame||frames()[0].id;$('#prototype-frame').srcdoc=htmlExport(store,{startFrame:start});$('#preview-title').textContent=store.get('project')?.name||'Prototype';$('#preview-dialog').showModal();}
function settings(){showDialog('Make yourself at home',`<div class="modal-form"><label>Your display name<input id="settings-name" value="${esc(identity.name)}" maxlength="40"></label><label>Cursor color<input id="settings-color" type="color" value="${identity.color}" style="height:35px;width:70px"></label><label>Editor appearance<select id="settings-theme"><option value="light" ${preferences.theme==='light'?'selected':''}>Light · a little clarity</option><option value="dark" ${preferences.theme==='dark'?'selected':''}>Dark · after hours</option></select></label><label>Collaboration server<input id="settings-server" value="${esc(preferences.server)}" placeholder="http://localhost:4173"></label></div><label class="toggle-row">Smart alignment guides<input id="settings-snap" type="checkbox" ${editor.snap?'checked':''}></label><label class="toggle-row">Snap to 8 px grid<input id="settings-grid" type="checkbox" ${editor.grid?'checked':''}></label><div class="modal-section"><h3>Rendering engine</h3><p class="info-note">${esc(renderer.mode)} · ${renderer.stats.total||0} layers<br>${renderer.mode==='WebGPU'?'Native GPU shapes with retained text/path/image atlases.':esc(renderer.fallbackReason||'Canvas compatibility mode')+'. The same document and editing tools remain available.'}</p></div><div class="modal-section"><h3>AI provider configuration</h3><p class="info-note">Set <code>AI_URL</code>, <code>AI_MODEL</code>, and <code>AI_KEY</code> in the server environment. Keys stay on the server. No provider is configured or billed by this download.</p></div><div class="modal-actions"><button class="button primary" data-cmd="save-settings">Save preferences</button></div>`);}
async function saveSettings(){identity={name:$('#settings-name').value.trim().slice(0,40)||'Designer',color:$('#settings-color').value};preferences={theme:$('#settings-theme').value,server:$('#settings-server').value.trim(),snap:$('#settings-snap').checked,grid:$('#settings-grid').checked};await vault.setting('identity',identity);await vault.setting('preferences',preferences);document.body.classList.toggle('dark',preferences.theme==='dark');editor.snap=preferences.snap;editor.grid=preferences.grid;updatePresence(sync.peers);editor.presence();closeDialog();toast('Preferences saved');}

const QUICK_ACTIONS=[['new-screen','Add a screen','F'],['new-project','New project',''],['projects','Your projects',''],['preview','Preview prototype','Ctrl Enter'],['export','Export design','Ctrl Shift E'],['share','Share workspace',''],['copy','Copy selection','Ctrl C'],['paste','Paste elements','Ctrl V'],['duplicate','Duplicate selection','Ctrl D'],['group','Group selection','Ctrl G'],['ungroup','Ungroup','Ctrl Shift G'],['bring-front','Bring to front',']'],['send-back','Send to back','['],['distribute-x','Distribute horizontally',''],['distribute-y','Distribute vertically',''],['make-component','Create reusable component',''],['fit','Fit all screens','Shift 1'],['fit-selection','Fit selection','Shift 2'],['rename','Rename layer','Ctrl R'],['history','Version history',''],['settings','Preferences',''],['help','Keyboard shortcuts','?']];
function help(){showDialog('A few small shortcuts',`<p class="modal-description">Less reaching. More creating. Use Ctrl on Windows/Linux or ⌘ on a Mac.</p><div class="shortcut-grid">${[['Select','V'],['Pan','H / Space + drag'],['Rectangle / ellipse','R / O'],['Text / freehand','T / P'],['Line / screen','L / F'],['Comment','C'],['Multi-select','Shift + click'],['Select inside a group','Ctrl + click'],['Keep proportions','Shift + resize'],['Zoom','Ctrl + wheel / pinch'],['Move 1 px / 10 px','Arrows / Shift + arrows'],['Undo / redo','Ctrl Z / Ctrl Shift Z'],['Copy / paste / duplicate','Ctrl C / V / D'],['Group / ungroup','Ctrl G / Ctrl Shift G'],['Fit all / selection','Shift 1 / Shift 2'],['Find any command','Ctrl K']].map(([a,b])=>`<div><span>${a}</span><kbd>${b}</kbd></div>`).join('')}</div><div class="modal-section"><h3>Designed to stay yours</h3><p class="info-note">Designs save to this browser with IndexedDB. Export a .mireva file for a portable backup. Share uses the included Node server, with genuine live cursors, comments, role-based invitations and persistent edits. Local Compose is a template engine; connected AI needs your own provider.</p></div>`);}
function commandPalette(){showDialog('Find your next move',`<div class="library-search" style="margin:0 0 14px">${icon('search')}<input id="command-search" placeholder="Search commands…" autocomplete="off"></div><div id="command-results"></div>`);renderCommands('');setTimeout(()=>$('#command-search')?.focus(),20);}
function renderCommands(q){$('#command-results').innerHTML=QUICK_ACTIONS.filter(a=>a[1].toLowerCase().includes(q.toLowerCase())).map(([cmd,label,key])=>`<button class="command-row" data-command-choice="${cmd}"><span>${label}</span><kbd>${key}</kbd></button>`).join('')||'<p class="info-note">No matching commands</p>';}
function contextMenu(x,y){const menu=$('#context-menu');menu.innerHTML=[['copy','Copy','Ctrl C'],['paste','Paste','Ctrl V'],['duplicate','Duplicate','Ctrl D'],['group','Group selection','Ctrl G'],['ungroup','Ungroup','⇧ Ctrl G'],['rename','Rename',''],['bring-front','Bring to front',']'],['send-back','Send to back','['],['lock-selection','Lock / unlock',''],['hide-selection','Hide / show',''],['make-component','Create component',''],['delete','Delete','Del']].map(([cmd,label,key])=>`<button data-cmd="${cmd}" role="menuitem"><span>${label}</span><kbd>${key}</kbd></button>`).join('');menu.hidden=false;menu.style.left=Math.min(x,innerWidth-230)+'px';menu.style.top=Math.max(8,Math.min(y,innerHeight-420))+'px';}
function captureClipboard(){const roots=topSelection(store,[...editor.selection]);if(!roots.length)throw Error('Select something to copy');const nodes=roots.flatMap(id=>[store.get(id),...store.descendants(id)]).map(n=>{const{id,_stamps,...values}=clone(n);return{id,...values};});return{format:'mireva-clipboard',roots,nodes};}
async function copySelection(){clipboard=captureClipboard();try{await navigator.clipboard.writeText(JSON.stringify(clipboard));}catch{}toast('Selection copied');}
async function pasteSelection(){if(!canEdit())throw Error('Editing permission is required');let data=clipboard;try{const text=await navigator.clipboard.readText();if(text.startsWith('{')){const parsed=JSON.parse(text);if(parsed.format==='mireva-clipboard')data=parsed;}}catch{}if(!data?.nodes?.length)throw Error('Copy elements from a Mireva project first');if(data.nodes.length>5000)throw Error('Paste at most 5,000 layers at a time');const ids=new Map(data.nodes.map(n=>[n.id,uid()]));store.transact('Paste elements',()=>{for(const n of data.nodes){const{id,...v}=clone(n);v.parent=ids.get(v.parent)||(store.get(v.parent)?v.parent:'');v.target=ids.get(v.target)||v.target||'';if(data.roots.includes(id)){v.x+=24;v.y+=24;v.order=nextOrder(v.parent);}store.add(v,ids.get(id));}});editor.select(data.roots.map(id=>ids.get(id)));}
function arrange(front){store.transact(front?'Bring to front':'Send to back',()=>{for(const id of topSelection(store,[...editor.selection])){const n=store.get(id),siblings=store.children(n.parent);store.set(id,{order:(front?Math.max(...siblings.map(s=>s.order)):Math.min(...siblings.map(s=>s.order)))+(front?1:-1)});}});}
async function rename(){const n=firstSelected();if(!n)return;const name=await ask('Give it a name','Layer name',n.name);if(name)store.set(n.id,{name});}
function addHotspot(){const pos=insertion();let id;store.transact('Add hotspot',()=>id=store.add(node('hotspot',{...pos,w:140,h:60,name:'Interaction hotspot',fill:'transparent',order:nextOrder(pos.parent),action:'navigate',target:frames().find(f=>f.id!==pos.parent)?.id||'',trigger:'click',transition:'fade'})));editor.select([id]);setMode('prototype');}
async function exec(cmd){
 if(cmd==='export-package'){download((store.get('project')?.name||'design')+'.mireva.zip',portableArchive(store),'application/zip');return;}if(cmd==='workspace'){finishText();await workspace.show();return;}if(cmd==='vector-pen'){finishText();vector.startPen();return;}if(cmd==='vector-edit'){finishText();vector.start([...editor.selection][0]);return;}if(cmd.startsWith('boolean-')){await vector.combine(cmd.slice(8));return;}
finishText();$('#context-menu').hidden=true;switch(cmd){
 case'projects':return openProjects();case'new-project':return newProject();case'rename-project':{const name=await ask('The beginning of something','Project name',store.get('project')?.name);if(name)store.set('project',{name});break;}
 case'undo':store.undo();editor.select([...editor.selection]);break;case'redo':store.redo();editor.select([...editor.selection]);break;
 case'share':return openShare();case'export':return openExport();case'preview':return preview();case'new-screen':return screenDialog();case'help':return help();
 case'zoom-out':renderer.zoom(renderer.camera.z/1.2);break;case'zoom-in':renderer.zoom(renderer.camera.z*1.2);break;case'zoom-menu':showDialog('A different perspective',`<div class="export-grid">${[25,50,75,100,150,200].map(n=>`<button class="button" data-zoom="${n}">${n}%</button>`).join('')}</div><div class="modal-actions"><button class="button" data-cmd="fit">Fit all screens</button><button class="button" data-cmd="fit-selection">Fit selection</button></div>`);break;
 case'fit':closeDialog();fitAll();break;case'fit-selection':closeDialog();if(editor.selection.size)editor.fitSelection();else fitAll();break;
 case'wireframe':renderer.wireframe=!renderer.wireframe;$('#wireframe-button').classList.toggle('active',renderer.wireframe);renderer.invalidate();break;
 case'comments':setPanel('comments');break;case'toggle-inspector':document.body.classList.toggle('show-inspector');break;case'close-library':document.body.classList.remove('show-library');break;
 case'command-palette':return commandPalette();case'history':return openHistory();case'settings':return settings();case'close-dialog':closeDialog();break;case'close-preview':$('#preview-dialog').close();$('#prototype-frame').srcdoc='';break;
 case'import':chooseFile('normal');break;case'import-image':chooseFile('image');break;case'extract-palette':chooseFile('palette');break;case'scan-screenshot':scanImage=null;showScan();break;case'choose-scan':chooseFile('scan');break;
 case'generate':return generate();case'reconstruct':return reconstruct();case'create-room':return createRoom();case'create-invite':return createInvite();case'copy-invite':return copyText(lastInvite,'Invitation link copied');case'owner-link':return copyText(sync.shareLink(),'Private owner recovery link copied');case'disconnect':return disconnect();
 case'checkpoint':return checkpoint();case'export-png':return doExport('png');case'export-svg':return doExport('svg');case'export-html':return doExport('html');case'export-json':return doExport('json');case'save-settings':return saveSettings();
 case'selection-menu':{const r=$('[data-cmd="selection-menu"]').getBoundingClientRect();contextMenu(r.right-220,r.bottom);break;}
 case'copy-css':if(firstSelected())return copyText(nodeCSS(firstSelected()),'CSS copied');break;
 case'set-start':if(firstSelected()?.type==='frame')store.set('project',{startFrame:firstSelected().id});break;
 case'add-hotspot':return addHotspot();case'transparent-fill':editSelection({fill:'transparent'});break;
 case'group':editor.select([group(store,[...editor.selection])]);break;case'ungroup':editor.select([...editor.selection].flatMap(id=>ungroup(store,id)));break;
 case'make-component':if(firstSelected())makeComponent(store,firstSelected().id);else throw Error('Select an element or group first');break;
 case'update-instances':if(firstSelected())syncInstances(store,firstSelected().id);break;
 case'detach-instance':store.transact('Detach instance',()=>{for(const id of editor.selection)for(const n of [store.get(id),...store.descendants(id)])store.set(n.id,{componentId:''});});break;
 case'duplicate':editor.select(duplicate(store,[...editor.selection]));break;case'delete':store.transact('Delete selection',()=>{for(const id of editor.editableRoots())store.delete(id);});editor.select([]);break;
 case'copy':return copySelection();case'cut':await copySelection();return exec('delete');case'paste':return pasteSelection();case'select-all':editor.select(store.children('').filter(n=>!n.hidden&&!n.locked).map(n=>n.id));break;
 case'bring-front':arrange(true);break;case'send-back':arrange(false);break;case'distribute-x':distribute(store,[...editor.selection],'x');break;case'distribute-y':distribute(store,[...editor.selection],'y');break;
 case'rename':return rename();case'lock-selection':editSelection({locked:!selected().every(n=>n.locked)});break;case'hide-selection':editSelection({hidden:!selected().every(n=>n.hidden)});break;
 default:throw Error('Unknown command: '+cmd);
 }updateHeader();renderInspector();if(panel==='layers')renderLayers();}
const safely=fn=>(...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>{console.error(e);toast(e.message||String(e),true);});
document.addEventListener('click',safely(async e=>{
 const el=e.target.closest('button,[data-layer],[data-open-project],[data-comment]');if(!el||el.disabled)return;const d=el.dataset;
 if(d.commandChoice){closeDialog();return exec(d.commandChoice);}if(d.cmd)return exec(d.cmd);
 if(d.panel)return setPanel(d.panel);if(d.mode)return setMode(d.mode);if(d.tool){editor.setTool(d.tool);focusCanvas();return;}
 if(d.component)return addComponent(d.component);if(d.componentTab){componentTab=d.componentTab;return renderPanel();}if(d.category){category=d.category;return renderPanel();}
 if(d.textPreset)return addText(d.textPreset);if(d.template)return useTemplate(d.template);if(d.theme!==undefined)return applyTheme(+d.theme);if(d.device){composeDevice=d.device;return renderPanel();}
 if(d.insertIcon){const pos=insertion();let id;store.transact('Insert icon',()=>id=store.add(node('icon',{...pos,w:32,h:32,icon:d.insertIcon,name:d.insertIcon+' icon',fill:'transparent',color:activeTheme().primary,order:nextOrder(pos.parent)})));editor.select([id]);return;}
 if(d.instance){editor.select(instantiate(store,d.instance));return;}
 if(d.reuseImage){const id=duplicate(store,[d.reuseImage])[0],pos=insertion();store.set(id,pos);editor.select([id]);return;}
 if(d.swatch){if(!editor.selection.size){await copyText(d.swatch,'Color copied');return;}editSelection({[firstSelected().type==='text'||firstSelected().type==='icon'?'color':'fill']:d.swatch});renderInspector();return;}
 if(d.align){alignNodes(store,[...editor.selection],d.align);return renderInspector();}
 if(d.toggleProp){editSelection({[d.toggleProp]:!firstSelected()?.[d.toggleProp]});return renderInspector();}if(d.textAlign){editSelection({align:d.textAlign});return renderInspector();}
 if(d.collapse){collapsed.has(d.collapse)?collapsed.delete(d.collapse):collapsed.add(d.collapse);return renderLayers();}
 if(d.visibility){store.set(d.visibility,{hidden:!store.get(d.visibility).hidden});return renderLayers();}if(d.lock){store.set(d.lock,{locked:!store.get(d.lock).locked});return renderLayers();}
 if(d.layer){const s=new Set(editor.selection);if(e.shiftKey){s.has(d.layer)?s.delete(d.layer):s.add(d.layer);editor.select([...s]);}else editor.select([d.layer]);return;}
 if(d.focusFrame){editor.select([d.focusFrame]);editor.fitSelection();return;}
 if(d.comment||d.focusComment){const c=store.get(d.comment||d.focusComment);if(c?.frame){editor.select([c.frame]);editor.fitSelection();}setPanel('comments');setTimeout(()=>document.querySelector(`[data-focus-comment="${c?.id}"]`)?.scrollIntoView({block:'nearest'}),30);return;}
 if(d.commentsFilter){showResolved=d.commentsFilter==='all';return renderPanel();}if(d.resolveComment){const c=store.get(d.resolveComment);store.set(c.id,{resolved:!c.resolved});return renderPanel();}if(d.reply)return reply(d.reply);
 if(d.preset)return addScreen(d.preset);if(d.zoom){renderer.zoom(+d.zoom/100);closeDialog();return;}
 if(d.openProject)return openProject(d.openProject);
 if(d.duplicateProject){const p=await vault.get(d.duplicateProject),snapshot=clone(p.snapshot);snapshot.records.project.name+=' copy';await vault.save(uid('doc'),snapshot);return openProjects();}
 if(d.deleteProject){if(d.deleteProject===documentId)throw Error('Open a different project before deleting this one');if(confirm('Delete this local project? Shared server rooms are not deleted.'))await vault.delete(d.deleteProject);return openProjects();}
 if(d.revokeInvite){if(confirm('Revoke this invitation and disconnect its active sessions?')){await sync.revoke(d.revokeInvite);return openShare();}}
 if(d.restoreVersion)return restoreVersion(d.restoreVersion,d.shared==='true');
}));
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#context-menu'))$('#context-menu').hidden=true;});
document.addEventListener('input',e=>{if(e.target.id==='library-search'){search=e.target.value;renderPanel();}if(e.target.id==='compose-prompt')composePrompt=e.target.value;if(e.target.id==='command-search')renderCommands(e.target.value);});
document.addEventListener('change',safely(async e=>{const t=e.target;if(t.matches('[data-prop]')){let v=t.type==='checkbox'?t.checked:t.type==='number'||t.dataset.prop==='fontWeight'?Number(t.value):t.value;if(t.dataset.prop==='opacity')v=clamp(v/100,0,1);if(['w','h','fontSize','lineHeight'].includes(t.dataset.prop))v=Math.max(.1,+v);editSelection({[t.dataset.prop]:v});renderInspector();}
 if(t.id==='compose-theme')composeTheme=+t.value;if(t.id==='compose-method'){composeMethod=t.value;renderPanel();}if(t.id==='export-scope')exportScope=t.value;if(t.id==='export-scale')exportScale=+t.value;
 if(t.id==='snap-setting')editor.snap=t.checked;if(t.id==='grid-setting')editor.grid=t.checked;
 if(t.id==='file-input'&&t.files[0]){const file=t.files[0];t.value='';await importFile(file,importPurpose);}
}));
document.addEventListener('submit',e=>{if(e.target.id!=='ask-form')return;e.preventDefault();const v=$('#ask-value').value.trim(),resolve=askResolve;askResolve=null;$('#modal').close();resolve?.(v);});
$('#modal').addEventListener('cancel',()=>{askResolve?.(null);askResolve=null;});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
document.addEventListener('dragstart',e=>{const c=e.target.closest('[data-component]'),l=e.target.closest('[data-layer]');if(c)e.dataTransfer.setData('application/x-mireva-component',c.dataset.component);if(l)e.dataTransfer.setData('application/x-mireva-layer',l.dataset.layer);});
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.some(t=>t==='Files'||t.startsWith('application/x-mireva'))){e.preventDefault();if(e.target.closest('#canvas-host'))$('#canvas-host').classList.add('drop-active');}});
document.addEventListener('dragleave',e=>{if(e.target.id==='canvas-host')$('#canvas-host').classList.remove('drop-active');});
document.addEventListener('drop',safely(async e=>{const dt=e.dataTransfer;$('#canvas-host').classList.remove('drop-active');if(!dt)return;e.preventDefault();if(dt.files.length){for(const file of dt.files)await importFile(file,'normal');return;}const kind=dt.getData('application/x-mireva-component'),layer=dt.getData('application/x-mireva-layer'),target=e.target.closest('[data-layer]');if(kind&&e.target.closest('#canvas-host')){const world=renderer.world(editor.position(e)),frame=editor.frameAt(world),p=frame?point(inverse(frame.matrix),world.x,world.y):world;let id;store.transact('Drop component',()=>id=insertComponent(store,kind,frame?.n.id||'',p.x,p.y,activeTheme()));editor.select([id]);}
 if(layer&&target&&layer!==target.dataset.layer){const n=store.get(layer),t=store.get(target.dataset.layer);if(n.parent!==t.parent)throw Error('Reorder layers within the same parent. Use grouping to change nesting.');const siblings=store.children(t.parent),i=siblings.findIndex(s=>s.id===t.id);store.set(layer,{order:(t.order+(siblings[i+1]?.order??t.order+2))/2});renderLayers();}
}));
document.addEventListener('keydown',safely(async e=>{const typing=e.target.matches('input,textarea,select,[contenteditable="true"]');if(e.key==='Escape'){$('#context-menu').hidden=true;if(!$('#modal').open&&!$('#preview-dialog').open){editor.cancel();editor.setTool('select');editor.select([]);}return;}if(typing)return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if($('#modal').open||$('#preview-dialog').open)return;let cmd;
 if(mod){cmd={z:e.shiftKey?'redo':'undo',y:'redo',c:'copy',v:'paste',x:'cut',d:'duplicate',g:e.shiftKey?'ungroup':'group',a:'select-all',k:'command-palette',r:'rename',enter:'preview',s:e.shiftKey?'export-json':'save',e:e.shiftKey?'export':null}[k];}
 else if(e.shiftKey&&k==='!')cmd='fit';else if(e.shiftKey&&(k==='@'||k==='2'))cmd='fit-selection';else if(e.shiftKey&&k==='1')cmd='fit';
 else if(k==='delete'||k==='backspace')cmd='delete';else if(k==='[')cmd='send-back';else if(k===']')cmd='bring-front';else if(k==='?')cmd='help';
 if(cmd){e.preventDefault();if(cmd==='save'){await saveNow();toast('Saved to this device');}else await exec(cmd);return;}
 if(k===' '){e.preventDefault();editor.space=true;$('#canvas-host').style.cursor='grab';return;}
 if(e.key.startsWith('Arrow')&&editor.selection.size&&canEdit()){e.preventDefault();const step=e.shiftKey?10:1,dx=e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0,dy=e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0;store.transact('Nudge selection',()=>{for(const id of editor.editableRoots()){const n=store.get(id);store.set(id,{x:n.x+dx,y:n.y+dy});}});return;}
 if(!mod&&e.shiftKey&&k==='p'){e.preventDefault();vector.startPen();return;}if(!mod){const tool={v:'select',h:'hand',f:'frame',r:'rect',o:'ellipse',l:'line',p:'pen',t:'text',c:'comment'}[k];if(tool){e.preventDefault();editor.setTool(tool);}}
}));
document.addEventListener('keyup',e=>{if(e.key===' '&&editor){editor.space=false;$('#canvas-host').style.cursor='';}});
window.addEventListener('blur',()=>{if(editor){editor.space=false;$('#canvas-host').style.cursor='';editor.cancel();}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveNow();});
window.addEventListener('beforeunload',e=>{if(sync?.queue.length||saveError){e.preventDefault();e.returnValue='';}});

async function initialize(){
 icons();let saved=null,roomConfig=null;try{await vault.open();identity=await vault.setting('identity')||identity;preferences={...preferences,...await vault.setting('preferences')};const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('room')&&(hash.has('token')||hash.get('account')==='1')){roomConfig={id:hash.get('room'),token:hash.get('token'),account:hash.get('account')==='1',server:hash.get('server')||location.origin};if(!/^[a-zA-Z0-9_-]+$/.test(roomConfig.id)||!['http:','https:'].includes(new URL(roomConfig.server).protocol))throw Error('Invalid invitation URL');sessionStorage.setItem('mireva-room',JSON.stringify(roomConfig));history.replaceState(null,'',location.pathname+location.search);}else roomConfig=JSON.parse(sessionStorage.getItem('mireva-room')||'null');documentId=roomConfig?'room_'+roomConfig.id:await vault.setting('lastDocument')||documentId;saved=await vault.get(documentId);}catch(e){toast('Local storage or invitation could not be read: '+e.message,true);}
 if(saved)store.load(saved.snapshot);else seedProject(store);
 renderer=new Renderer($('#canvas-host'),store,{onFrame:stats=>{editor?.renderOverlay();editingText?.position();vector?.render();$('#zoom-value').textContent=Math.round(renderer.camera.z*100)+'%';$('#render-stats').textContent=`${stats.visible} visible / ${stats.total} layers`;$('#render-stats').title=`Last CPU submission: ${stats.ms.toFixed(2)} ms${stats.drawCalls?' · '+stats.drawCalls+' GPU batches':''}. Not GPU execution time.`;},onMode:(name,reason)=>{$('#renderer-status').innerHTML='<i></i> '+name;$('#renderer-status').title=reason||'Native instanced shapes · retained text and image atlases';}});
 editor=new EditorController(renderer,store,{onSelect:()=>{renderInspector();if(panel==='layers')renderLayers();},onTool:()=>renderTools(),onText:openText,onVector:id=>vector.start(id),onComment:safely(commentAt),onContext:contextMenu,onPresence:data=>sync?.presence({...data,...identity}),onError:e=>toast(e,true),canEdit});
 vector=new VectorEditor(store,renderer,editor,{canEdit,onError:e=>toast(e,true),onChange:renderInspector});
 sync=new CollaborationClient(store,{accountHeaders:()=>account.headers(),onStatus:updateConnection,onPresence:updatePresence,onQueue:()=>saveNow(),onError:e=>toast(e,true)});
 workspace=new WorkspaceUI(account,{store,sync,editor,dialog:showDialog,toast,close:closeDialog,onImport:()=>{fitAll();renderPanel();renderInspector();},onOpen:async id=>{await saveNow();if(id){documentId='room_'+id;sessionStorage.setItem('mireva-room',JSON.stringify(sync.config));editor.select([]);fitAll();await vault.setting('lastDocument',documentId);await saveNow();}else if(!sync.config){sessionStorage.removeItem('mireva-room');} }});
 store.canWrite=(id,values)=>{if(canEdit())return true;const old=store.get(id),entity=values.entity||old?.entity;return sync.role==='commenter'&&entity==='comment'&&(!old||old.authorId===sync.grantId)&&Object.keys(values).every(k=>['entity','text','frame','x','y','author','authorId','thread','resolved','deleted','createdAt'].includes(k));};
 editor.snap=preferences.snap;editor.grid=preferences.grid;document.body.classList.toggle('dark',preferences.theme==='dark');store.on(onStoreChange);editor.setTool('select');renderPanel();renderInspector();updateHeader();updatePresence(sync.peers);await renderer.init();await new Promise(r=>requestAnimationFrame(r));
 if(saved?.camera){renderer.camera=saved.camera;renderer.invalidate();}else fitAll();
 await workspace.initialize();
 if(roomConfig){try{if(roomConfig.account){account.server=roomConfig.server;await account.refresh();}await sync.connect(roomConfig,{fresh:!saved,queue:saved?.outbox||[]});editor.select([]);if(!saved)fitAll();}catch(e){toast('Could not join: '+e.message+'. Your local document is still available.',true);sync.role='viewer';sync.setStatus('offline');}}
 initializing=false;await vault.setting('lastDocument',documentId).catch(()=>{});await saveNow();updateHeader();renderPanel();renderInspector();sync.presence({...identity,cursor:null,selection:[]});
 window.mireva={store,renderer,editor,sync,vector,workspace,account,vault,exec,saveNow,exportSVG:()=>svgExport(store),exportHTML:()=>htmlExport(store),get state(){return{documentId,panel,mode,identity,preferences};}};window.__MIREVA_READY__=true;
}
initialize().catch(e=>{console.error(e);toast('The editor could not start: '+e.message,true);$('#save-state').textContent='Startup error · '+e.message;});

window.addEventListener('hashchange',()=>{const h=new URLSearchParams(location.hash.slice(1));if(h.has('room')&&(h.has('token')||h.get('account')==='1'))saveNow().catch(()=>{}).finally(()=>location.reload());});
